import { Header, Footer, JsonLd } from '../components';
import { site, staffingOffer, leadQuestions, staffingFitNote } from '../data';
export const metadata = { title: `Contact ${site.brand}`, description: 'Request a Philippines staffing plan. Share the role, tasks, tools, shift, and review needs for a Filipino assistant.' };
export default function Contact() {
 const siteAny = site as any;
 const siteUrl = siteAny.url || `https://${String(site.domain).toLowerCase()}`;
 const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'ContactPage', name: `Contact ${site.brand}`, url: `${siteUrl}/contact` }, { '@type': 'Organization', name: site.brand, url: siteUrl }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Contact', item: `${siteUrl}/contact` }] }] };
 return <><Header/><main className="section"><JsonLd data={schema} /><div className="container two"><div><p className="eyebrow">Philippines staffing intake</p><h1>Request a Filipino assistant plan</h1><p className="lead">Tell us what work you want handled. We will use the tasks, tools, shift, and review needs to scope a role for talent recruited and hired in the Philippines.</p><div className="card"><h2>What our staffing team can help map</h2><ul className="list">{staffingOffer.included.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="card"><h2>Questions that make the plan better</h2><ul className="list">{leadQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><p className="callout"><b>Custom staffing fit:</b> {staffingFitNote}</p></div><form className="card" action="/thank-you"><label>Name<br/><input required name="name" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Email<br/><input required name="email" type="email" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Company / website<br/><input name="company" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What role or work do you want staffed?<br/><textarea name="tasks" rows={6} style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What matters most?<br/><select name="concern" style={{width:'100%', padding:12, margin:'6px 0 14px'}}><option>Finding the right Filipino staff member</option><option>Quality checks and reporting</option><option>Philippines shift and workday overlap</option><option>Tool access and data safety</option><option>Adding work after the first role</option></select></label><button className="btn" type="submit">Request staffing plan</button></form></div></main><Footer/></>;
}
