import type { ResearchPost } from './data';

const sources = {
  sba: { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'role expectations and management planning' },
  nist: { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'risk identification, protection, response, and recovery' },
  ftc: { name: 'Federal Trade Commission: Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'data handling and security practices' },
  ilo: { name: 'International Labour Organization: Working time and work-life balance', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'working-time and sustainable scheduling evidence' },
  cisa: { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'authentication, updates, and phishing resistance' },
  privacy: { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy-risk governance and context' },
  gpo: { name: 'U.S. Government Publishing Office', url: 'https://www.govinfo.gov/', note: 'finding authoritative public records' },
};
type Key = keyof typeof sources;
type Spec = { slug: string; title: string; question: string; thesis: string; angle: string; keys: [Key, Key, Key] };

const specs: Spec[] = [
  { slug: 'research-question-selection-for-daily-articles', title: 'Research question selection for daily articles', question: 'How should a Philippines-based virtual assistant narrow a daily article request into one answerable reader question?', thesis: 'A daily article should answer one decision question rather than collect adjacent facts.', angle: 'question selection', keys: ['sba','nist','gpo'] },
  { slug: 'source-date-checks-for-virtual-assistant-research', title: 'Source-date checks for virtual assistant research', question: 'What date evidence should a remote research handoff preserve before an article is drafted?', thesis: 'Publication, update, access, and effective dates answer different questions and should not be collapsed.', angle: 'source chronology', keys: ['nist','cisa','gpo'] },
  { slug: 'evidence-boundaries-for-assistant-prepared-briefs', title: 'Evidence boundaries for assistant-prepared briefs', question: 'What should a brief prove before an editor trusts it?', thesis: 'A brief should make claim scope, source fit, uncertainty, and owner decisions visible before drafting begins.', angle: 'brief acceptance', keys: ['sba','gpo','privacy'] },
  { slug: 'handoff-latency-in-philippines-research-support', title: 'Handoff latency in Philippines research support', question: 'When does a time-zone handoff create research risk rather than useful coverage?', thesis: 'A handoff is useful when context arrives with the work; elapsed clock time alone is not a quality measure.', angle: 'handoff continuity', keys: ['ilo','sba','nist'] },
  { slug: 'privacy-scope-in-remote-content-research', title: 'Privacy scope in remote content research', question: 'Which records should a virtual assistant receive while researching an article?', thesis: 'Minimum necessary source material reduces exposure while preserving the evidence needed for the assigned question.', angle: 'privacy scope', keys: ['privacy','ftc','nist'] },
  { slug: 'reviewer-calibration-for-daily-article-queues', title: 'Reviewer calibration for daily article queues', question: 'How can editors distinguish a factual miss from a disagreement about interpretation?', thesis: 'Calibration works when reviewers compare the same claim, source passage, scope, and disposition before judging a larger queue.', angle: 'reviewer calibration', keys: ['sba','nist','gpo'] },
  { slug: 'workload-signals-in-remote-research-operations', title: 'Workload signals in remote research operations', question: 'Which queue signals show that daily article volume is outrunning review capacity?', thesis: 'Queue age, correction type, and unresolved exceptions reveal pressure more honestly than online hours or raw item counts.', angle: 'workload evidence', keys: ['ilo','sba','nist'] },
  { slug: 'access-reviews-for-daily-article-support', title: 'Access reviews for daily article support', question: 'What access should be revisited when a research lane changes?', thesis: 'Access should follow the current task and evidence need, not the original role label or generalized trust.', angle: 'access review', keys: ['nist','ftc','cisa'] },
  { slug: 'claim-scope-in-virtual-assistant-market-research', title: 'Claim scope in virtual assistant market research', question: 'How can an assistant report market information without turning a small sample into a market fact?', thesis: 'Define population, period, source method, and unknowns before summarizing any market observation.', angle: 'market evidence', keys: ['gpo','nist','privacy'] },
  { slug: 'exception-routing-in-research-article-production', title: 'Exception routing in research article production', question: 'Which research exceptions should stop a draft before publication?', thesis: 'A missing source, conflicting definition, sensitive record, or unsupported conclusion needs a visible owner route.', angle: 'exception routing', keys: ['sba','nist','ftc'] },
];

const paragraph = (s: Spec) => `For OverseasVirtualAssistant.com, ${s.angle} is a real operating question because a Philippines-based virtual assistant may prepare research while the client retains editorial, commercial, privacy, and approval authority. ${s.thesis} The useful unit is an observable claim, handoff, brief, access decision, queue item, or exception—not a vague impression of effort. Begin by recording the intended reader decision, the work included, the evidence available, and the person who resolves disagreement. This makes the article’s niche central without inventing company results or treating a local routine as a statement about every Filipino worker.`;

const makePost = (s: Spec): ResearchPost => {
  const src = s.keys.map(k => sources[k]);
  return {
    slug: s.slug, title: `Research note: ${s.title}`, published: '2026-08-18',
    excerpt: `${s.question} Evidence-led analysis for businesses planning Philippines-based virtual assistant support.`,
    methodology: `Research question: ${s.question} This article compares the question with three reputable public sources and proposes a bounded review of daily article support work. The source findings, local evidence design, and editorial interpretation are separated. It does not measure a workforce, promise an outcome, or replace owner or professional judgment.`,
    headlineStat: { value: '1', label: 'decision question examined', source: 'Explicit research scope for this article' },
    keyStats: [{ value: '3', label: 'claim-relevant public sources' }, { value: '1', label: 'bounded local review proposed' }, { value: '0', label: 'unsupported performance claims' }],
    takeaways: [s.thesis, 'Record the unit, period, source scope, and reviewer disposition before interpreting a result.', 'Keep sensitive access, commitments, and exceptions with the authorized owner.'],
    sections: [
      { heading: 'The question in context', body: paragraph(s) + ` The first source in this review is used for ${src[0].note}; the second and third establish the information, risk, or authority boundary. These sources do not answer the company’s local decision by themselves. They help define what a responsible article can claim. A research assistant can gather public material, compare definitions, and mark uncertainty. The owner still decides whether the conclusion fits the business, audience, and current operating conditions. This distinction is especially important when daily publication creates pressure to make every request sound complete. A complete handoff may instead say that the evidence is insufficient, the question needs narrowing, or another reviewer is required.`, table: [['Scope field','Record'],['Question','The exact reader or owner decision'],['Unit','One claim, brief, handoff, or exception'],['Owner','Who resolves material conflict'],['Exclusion','What the assistant must route back']] },
      { heading: 'Evidence design for a remote research lane', body: `Use a dated sample that includes ordinary items and exceptions. For each item, preserve the input, source or record consulted, action taken, result, and reviewer disposition. The source set is relevant because ${src[0].name} addresses ${src[0].note}, ${src[1].name} addresses ${src[1].note}, and ${src[2].name} addresses ${src[2].note}. Do not count a link as support until its scope matches the sentence using it. If the sample is small, state how it was selected and avoid treating it as representative of every business or every Philippines-based assistant. A clear sample can show that the brief needs a narrower question, stronger evidence, another reviewer, or less delegated authority.`, table: [['Evidence field','Why it matters'],['Selection rule','Shows what entered the sample'],['Source fit','Connects the claim to actual evidence'],['Disposition','Separates accepted, corrected, pending, escalated'],['Limit','Prevents local observation becoming universal claim']] },
      { heading: 'Interpretation and boundaries', body: `${s.thesis} is operational analysis, not a sourced statistic. A repeated correction can signal a weak brief or source rule; it is not a label for a person. An unresolved exception is a routing event, not permission to improvise. When the topic involves personal information, account access, payments, employment, customer promises, or specialist advice, stop at the boundary and involve the responsible owner. The article should also distinguish a fact from an inference: a source may describe a principle, while a local review may show that one queue lacks a field or that one handoff lost context. Those findings cannot be merged into a claim about the whole market or workforce.`, table: [['Finding type','Action'],['Supported','Keep wording within source scope'],['Mixed','Separate cases and explain difference'],['Unclear','Collect narrower evidence'],['Outside authority','Escalate before publication']] },
      { heading: 'What would change the decision', body: `A useful research conclusion names a reopening signal. For ${s.angle}, that might be a changed task definition, a new source version, a different audience, a new data field, a repeated correction pattern, or an exception that the current owner cannot resolve. Record the signal before the next article so the routine does not drift silently. This is also where time-zone planning matters: a handoff should state what is complete, what is blocked, and what the next owner must decide. The assistant can prepare a concise evidence package and protect the source trail; the editor can narrow the thesis or pause publication. A small, reversible decision is stronger than an impressive but unsupported conclusion.`, table: [['Reopening signal','Response'],['Task changed','Reconfirm scope and access'],['Source changed','Refresh date and claim fit'],['Correction repeated','Review brief or acceptance rule'],['Exception unresolved','Pause and escalate']] },
      { heading: 'Implications for the daily publishing routine', body: `The research result should change one visible part of the routine, not become a slogan. If the question is accepted, put its wording in the brief and require the researcher to quote the relevant source scope. If evidence is mixed, add a review field that records the disagreement instead of asking the writer to smooth it over. If access is too broad, redesign the task around public sources or masked client records. If the queue is too full for review, reduce the batch or move the publication date rather than lowering the evidence standard invisibly. These are practical implications for a company creating daily articles with Philippines-based support: the assistant prepares, links, dates, compares, and escalates; the editorial owner decides what can be published. The routine should preserve rejected questions and corrected claims so the same ambiguity does not return tomorrow.`, table: [['Routine change','Observable evidence'],['Brief update','Question and exclusion are explicit'],['Source rule','Claim passages are retained'],['Access change','Only needed records are available'],['Queue decision','Review capacity is acknowledged']] },
      { heading: 'Conclusion', body: `The evidence-led answer is to make the decision smaller, the record clearer, and the owner route visible. ${s.thesis} is useful only when the article preserves what the sources say, what the local sample shows, and what remains an editorial choice. The three sources support the stated evidence boundaries, not a guarantee about service performance. Recheck the conclusion when the task, source environment, access level, schedule, or audience changes. A Philippines-based virtual assistant can prepare a traceable research package; the authorized editor remains responsible for material interpretation and publication.`, table: [['Conclusion test','Pass condition'],['Niche relevance','Issue affects scoped remote support'],['Original reasoning','Question is not a renamed generic guide'],['Evidence fit','Sources support the actual claims'],['Bounded decision','Next step and escalation owner are clear']] },
    ],
    sourceNotes: `Source notes: ${src.map(x => x.url).join('; ')} support the stated evidence boundaries. Local review criteria are editorial analysis, not workforce statistics.`, sources: src, internalLinks: ['/research', '/services/research-and-data-support'],
    faqs: [{ question: 'Does this research promise a result?', answer: 'No. It defines a bounded question and a way to inspect evidence; it does not promise performance or business outcomes.' }, { question: 'Why keep the Philippines context?', answer: 'The context ties the analysis to the company’s actual service audience without making claims about an entire workforce.' }],
    relatedResearch: ['/research', '/research/research-workflow-design-for-virtual-assistants'], image: { src: '/images/thumbnails/generated/editorial-source-registers-for-daily-articles.webp', alt: `Research illustration for ${s.title}` }, cta: 'Want this question turned into a clearly scoped staffing lane? Share the work, evidence, and approval boundaries with our staffing team.'
  };
};

export const august18ResearchPosts = specs.map(makePost);
