import type { BlogPost } from './data';

type Spec = { slug: string; title: string; excerpt: string; published: string; lane: string; audience: string; steps: string[]; boundary: string; decision: string };
const source = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'planning and managing a small-business team' };
const securitySource = { name: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity practices' };

const specs: Spec[] = [
  { slug: 'virtual-assistant-invoice-preparation', title: 'Invoice preparation support from a virtual assistant', excerpt: 'Organize approved billing details into draft invoices that an owner can check before anything is sent.', published: '2026-08-14', lane: 'invoice preparation', audience: 'service businesses that bill from completed work', steps: ['Match the draft to an approved client and service record.', 'Flag missing terms or approval details.', 'Keep a clear draft status until review.'], boundary: 'Do not send invoices, change terms, apply payments, or decide whether a charge is valid.', decision: 'The owner approves, corrects, and sends the bill.' },
  { slug: 'philippines-virtual-assistant-calendar-coordination', title: 'Calendar coordination with a Philippines virtual assistant', excerpt: 'Make meeting requests easier to manage by separating availability checks from commitments.', published: '2026-08-14', lane: 'calendar coordination', audience: 'owners whose meetings involve several people and time zones', steps: ['Use stated working windows and buffers.', 'Offer only times the calendar rules allow.', 'Record pending replies and conflicts in one place.'], boundary: 'Do not accept an important meeting, move a protected block, or disclose private calendar details without permission.', decision: 'The calendar owner decides which commitments take priority.' },
  { slug: 'virtual-assistant-crm-duplicate-review', title: 'CRM duplicate review for a virtual assistant', excerpt: 'Clean repeated contact records carefully while preserving evidence and leaving uncertain merges for review.', published: '2026-08-14', lane: 'CRM duplicate review', audience: 'sales and service teams with growing contact databases', steps: ['Compare approved fields and record the match reason.', 'Keep conflicting records separate until someone decides.', 'Log every merge or hold for later review.'], boundary: 'Do not guess identity, overwrite history, or export a contact list for another use.', decision: 'A named CRM owner approves uncertain matches and irreversible changes.' },
  { slug: 'philippines-virtual-assistant-customer-record-updates', title: 'Customer-record updates from a Philippines virtual assistant', excerpt: 'Keep customer details current from approved requests without turning data entry into an unverified account change.', published: '2026-08-14', lane: 'customer-record updates', audience: 'small teams maintaining customer profiles across shared systems', steps: ['Use the approved request as the source for each field.', 'Leave a note when a request conflicts with the current record.', 'Send sensitive or unusual changes to the record owner.'], boundary: 'Do not reveal private data or change account permissions outside the approved process.', decision: 'The authorized account owner decides whether a disputed update is accepted.' },
  { slug: 'virtual-assistant-vendor-quote-comparison', title: 'Vendor quote comparison a virtual assistant can prepare', excerpt: 'Put comparable supplier information in one review sheet while purchasing judgment stays with the business owner.', published: '2026-08-14', lane: 'vendor quote comparison', audience: 'small companies collecting options for an approved purchase', steps: ['Use the same requested specifications for each quote.', 'Show what each supplier included and left unanswered.', 'Link each figure and condition to its source.'], boundary: 'Do not negotiate, select a supplier, disclose one vendor\'s terms to another, or approve a purchase.', decision: 'The owner chooses the supplier and authorizes the next conversation.' },
  { slug: 'philippines-virtual-assistant-refund-request-triage', title: 'Refund-request triage from a Philippines virtual assistant', excerpt: 'Sort refund questions by the approved policy and evidence so the right person can make a timely decision.', published: '2026-08-14', lane: 'refund-request triage', audience: 'customer teams handling returns, cancellations, or service complaints', steps: ['Record the request, reference, and stated reason.', 'Match it to the current policy without interpreting gaps.', 'Escalate exceptions with the relevant history.'], boundary: 'Do not promise a refund, make a policy exception, or ask for unnecessary payment information.', decision: 'The designated support owner makes the refund or exception decision.' },
  { slug: 'virtual-assistant-property-listing-administration', title: 'Property-listing administration for a virtual assistant', excerpt: 'Keep listing details, inquiry notes, and appointment requests organized while licensed decisions remain with the real-estate professional.', published: '2026-08-14', lane: 'property-listing administration', audience: 'real-estate teams managing recurring listing and inquiry work', steps: ['Use the approved listing record as the source.', 'Separate an inquiry from a qualified prospect or showing.', 'Flag missing facts before a listing is changed.'], boundary: 'Do not give legal or property advice, set terms, or represent an unapproved listing detail.', decision: 'The licensed or designated owner controls listing claims and commitments.' },
  { slug: 'philippines-virtual-assistant-ecommerce-order-review', title: 'Ecommerce order review with a Philippines virtual assistant', excerpt: 'Surface address issues, holds, and missing fulfillment details before an order reaches the next approved step.', published: '2026-08-14', lane: 'ecommerce order review', audience: 'online stores with repeat orders and a shared fulfillment queue', steps: ['Check the order against current fulfillment rules.', 'Mark missing details instead of guessing.', 'Keep customer-facing actions separate from internal review.'], boundary: 'Do not alter payment status, promise delivery, issue a refund, or change an order without authorization.', decision: 'The store owner or operations lead decides exceptions.' },
  { slug: 'virtual-assistant-meeting-notes-and-actions', title: 'Meeting notes and action tracking for a virtual assistant', excerpt: 'Turn an approved meeting record into clear owners and follow-up without inventing decisions that were not made.', published: '2026-08-14', lane: 'meeting notes and action tracking', audience: 'small teams that lose follow-up items after client or staff meetings', steps: ['Separate decisions, open questions, and suggestions.', 'Attach each action to the owner named in the record.', 'Send uncertain wording back for confirmation.'], boundary: 'Do not record confidential material outside the approved system or treat a suggestion as a decision.', decision: 'The meeting owner confirms the final notes and commitments.' },
  { slug: 'philippines-virtual-assistant-travel-itinerary-support', title: 'Travel-itinerary support from a Philippines virtual assistant', excerpt: 'Assemble approved travel details into a readable itinerary while the traveler controls bookings and changes.', published: '2026-08-14', lane: 'travel-itinerary support', audience: 'busy owners coordinating work travel across several reservations', steps: ['Use booking confirmations as the source for every detail.', 'Show local time zones and unresolved gaps plainly.', 'Keep a change log when an approved reservation is updated.'], boundary: 'Do not book, cancel, choose an itinerary, or store passport details outside approved controls.', decision: 'The traveler or authorized coordinator approves every reservation and change.' },
  { slug: 'virtual-assistant-receipt-categorization', title: 'Receipt categorization support for a virtual assistant', excerpt: 'Sort receipts into a reviewable bookkeeping queue without presenting a category guess as an accounting conclusion.', published: '2026-08-14', lane: 'receipt categorization', audience: 'small businesses preparing records for a bookkeeper or accountant', steps: ['Attach each receipt to the relevant transaction when available.', 'Use the approved category list and mark uncertainty.', 'Keep missing or unreadable receipts in an exception queue.'], boundary: 'Do not file taxes, approve expenses, move money, or provide accounting advice.', decision: 'A qualified bookkeeper or owner confirms categories and final records.' },
  { slug: 'philippines-virtual-assistant-appointment-reminder-support', title: 'Appointment reminder support from a Philippines virtual assistant', excerpt: 'Prepare approved reminders and track replies without turning a reminder into professional advice.', published: '2026-08-14', lane: 'appointment reminder support', audience: 'practices and service businesses managing scheduled appointments', steps: ['Use the current approved reminder wording.', 'Record delivery and reply status without extra personal detail.', 'Escalate changes, cancellations, and unanswered questions.'], boundary: 'Do not give professional advice, disclose private information, or promise an appointment outcome.', decision: 'The practice or service owner handles rescheduling and substantive questions.' },
  { slug: 'virtual-assistant-document-naming-and-filing', title: 'Document naming and filing a virtual assistant can handle', excerpt: 'Give shared files predictable names and locations so a team can retrieve them without widening access.', published: '2026-08-14', lane: 'document naming and filing', audience: 'teams whose working files have grown across shared folders', steps: ['Apply the approved naming pattern and destination.', 'Record duplicates or unclear ownership for review.', 'Keep restricted material in its existing approved location.'], boundary: 'Do not delete originals, change permissions, or decide a document\'s retention period.', decision: 'The record owner approves archival, deletion, and access changes.' },
  { slug: 'philippines-virtual-assistant-insurance-record-follow-up', title: 'Insurance-record follow-up from a Philippines virtual assistant', excerpt: 'Track requested certificates and policy documents while leaving coverage interpretation to the qualified owner.', published: '2026-08-14', lane: 'insurance-record follow-up', audience: 'small companies collecting recurring vendor or facility records', steps: ['Record the requested document, version, and due date.', 'Mark received files ready for review rather than approved.', 'Escalate expired, conflicting, or missing records.'], boundary: 'Do not interpret coverage, certify compliance, or advise someone to accept a risk.', decision: 'The owner or qualified adviser reviews coverage and decides.' },
  { slug: 'virtual-assistant-event-registration-support', title: 'Event-registration support for a virtual assistant', excerpt: 'Keep attendee details and approved event communications organized without promising access or attendance.', published: '2026-08-14', lane: 'event-registration support', audience: 'small teams running workshops, classes, or community events', steps: ['Use approved registration fields and message templates.', 'Separate incomplete registrations from confirmed attendance.', 'Send access questions and exceptions to the event owner.'], boundary: 'Do not change eligibility, disclose attendee data, or promise a seat, result, or recording.', decision: 'The event owner controls eligibility, capacity, and exceptions.' },
  { slug: 'philippines-virtual-assistant-hr-record-administration', title: 'HR-record administration from a Philippines virtual assistant', excerpt: 'Organize approved personnel records and reminders with care for privacy and owner-only employment decisions.', published: '2026-08-14', lane: 'HR-record administration', audience: 'small employers keeping routine people-operations records organized', steps: ['Use the designated system and approved fields only.', 'Record missing acknowledgements without drawing conclusions.', 'Escalate sensitive requests to the responsible HR contact.'], boundary: 'Do not hire, discipline, interpret employment law, or share personnel information broadly.', decision: 'The employer and qualified advisers retain employment decisions.' },
  { slug: 'virtual-assistant-inventory-count-reconciliation', title: 'Inventory-count reconciliation a virtual assistant can organize', excerpt: 'Compare count sheets with system records and surface discrepancies before anyone changes stock records.', published: '2026-08-14', lane: 'inventory-count reconciliation', audience: 'stores and small operations teams tracking physical stock', steps: ['Match counts to a dated location and item list.', 'Separate counting differences from damaged or missing stock.', 'Attach the source and send exceptions to the inventory owner.'], boundary: 'Do not adjust stock, accuse a worker, or place an order based on a discrepancy.', decision: 'The inventory owner investigates and approves any record change.' },
  { slug: 'philippines-virtual-assistant-client-document-collection', title: 'Client-document collection from a Philippines virtual assistant', excerpt: 'Track requested files and unanswered questions so a service team can review a complete client handoff.', published: '2026-08-14', lane: 'client-document collection', audience: 'consultants and service teams waiting on client-provided information', steps: ['List each requested file, format, owner, and due date.', 'Mark a file received without calling it correct or complete.', 'Keep unanswered questions visible in the handoff.'], boundary: 'Do not alter client documents, infer consent, or provide advice from an unreviewed file.', decision: 'The service owner decides whether the materials are sufficient.' },
  { slug: 'virtual-assistant-local-business-directory-research', title: 'Local-business directory research for a virtual assistant', excerpt: 'Build a sourced list of public business details while the owner decides fit, contact, and outreach.', published: '2026-08-14', lane: 'local-business directory research', audience: 'small companies mapping potential partners or service providers', steps: ['Define location, business type, and fields before research.', 'Save the public source and date for each entry.', 'Separate a sourced fact from an unconfirmed assumption.'], boundary: 'Do not imply endorsement, collect restricted personal data, or contact businesses without authorization.', decision: 'The owner decides which businesses fit and whether outreach is appropriate.' },
  { slug: 'philippines-virtual-assistant-contract-renewal-reminders', title: 'Contract-renewal reminders from a Philippines virtual assistant', excerpt: 'Keep notice dates and review owners visible so a business can consider renewals before a deadline.', published: '2026-08-14', lane: 'contract-renewal reminders', audience: 'small teams managing recurring supplier or client agreements', steps: ['Record the source, renewal date, notice window, and decision owner.', 'Distinguish an upcoming date from an approved renewal.', 'Send the review queue early enough for the owner to act.'], boundary: 'Do not interpret a contract, negotiate terms, or renew or cancel an agreement.', decision: 'The agreement owner or legal adviser makes the renewal decision.' },
  { slug: 'virtual-assistant-shared-inbox-triage', title: 'Shared-inbox triage a virtual assistant can support', excerpt: 'Sort incoming messages by approved labels and ownership so important requests do not disappear in a busy inbox.', published: '2026-08-14', lane: 'shared-inbox triage', audience: 'small service teams managing a common customer or operations inbox', steps: ['Apply labels from the approved triage guide.', 'Keep urgent or ambiguous messages visible to the owner.', 'Draft only within the approved response boundary.'], boundary: 'Do not delete evidence, make promises, answer regulated questions, or send an unapproved reply.', decision: 'The inbox owner controls substantive replies and escalations.' },
  { slug: 'philippines-virtual-assistant-service-request-intake', title: 'Service-request intake from a Philippines virtual assistant', excerpt: 'Turn incoming requests into a consistent review record without promising that the work has been accepted.', published: '2026-08-14', lane: 'service-request intake', audience: 'home-service and professional-service businesses receiving varied requests', steps: ['Capture requested service, location, timing, and source.', 'Mark missing information and route safety or scope questions.', 'Separate a request from an accepted job or appointment.'], boundary: 'Do not quote, diagnose, promise availability, or accept work outside the approved process.', decision: 'The service owner decides scope, fit, timing, and acceptance.' },
];

const makePost = (spec: Spec, index: number): BlogPost => ({
  slug: spec.slug, title: spec.title, excerpt: spec.excerpt, minutes: 8 + (index % 5), updated: spec.published,
  takeaways: [`Start ${spec.lane} with one defined output and a named reviewer.`, 'Give the assistant a current example, the source of truth, and a clear stop rule.', 'Review early work before adding another system, customer type, or decision.'],
  sections: [
    { heading: 'Define the first work lane', body: `${spec.title} works best when ${spec.audience} starts with a small, visible assignment. ${spec.excerpt} Write down the trigger, required inputs, finished output, and person who accepts the result.`, bullets: spec.steps },
    { heading: 'Make the handoff reviewable', body: `For ${spec.lane}, show one completed example and name the source of truth. Ask the assistant to record missing information rather than filling gaps from guesswork. A short exception note is more useful than a confident but unsupported answer.` },
    { heading: 'Keep decisions with the owner', body: `${spec.boundary} The assistant can prepare information and route the question, but preparation is not approval. ${spec.decision}` },
    { heading: 'Review access as the work changes', body: 'Start with the minimum accounts needed for this assignment. Use individual logins where possible, turn on multi-factor authentication, and review access when the task lane expands or ends.' },
  ],
  faqs: [{ question: `What should the first ${spec.lane} assignment include?`, answer: 'Use one repeatable output, a current example, the source of truth, a named reviewer, and a written stop rule for exceptions.' }, { question: 'What stays with the business owner?', answer: spec.decision }],
  sources: [source, securitySource],
});

export const aug14BlogPosts: BlogPost[] = specs.map(makePost);
