import type { BlogPost } from './data';

type AugustSpec = {
  slug: string;
  title: string;
  excerpt: string;
  focus: string;
  audience: string;
  firstSteps: string[];
  watch: string;
};

const source = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'planning and managing a small-business team' };
const securitySource = { name: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity practices' };

const specs: AugustSpec[] = [
  { slug: 'virtual-assistant-invoice-preparation', title: 'Invoice preparation tasks a virtual assistant can handle', excerpt: 'Organize invoice inputs, draft records, and follow-up notes while keeping approval and payment authority with the business owner.', focus: 'invoice preparation', audience: 'service businesses that need cleaner billing administration', firstSteps: ['Collect approved client, project, and billing details in one source of truth.', 'Use a draft status until an authorized person checks the amount and terms.', 'Return missing purchase orders, hours, or delivery notes as explicit questions.'], watch: 'Never let preparation access become payment authority. The assistant can assemble and flag a draft; the owner or designated finance lead must approve and release it.' },
  { slug: 'philippines-virtual-assistant-real-estate-listing-admin', title: 'Real-estate listing administration for a Philippines virtual assistant', excerpt: 'Delegate listing data, photo coordination, inquiry notes, and appointment preparation without handing over licensed advice or final property decisions.', focus: 'real-estate listing administration', audience: 'real-estate teams with repetitive listing and inquiry work', firstSteps: ['Create a property record with the approved facts and a last-checked date.', 'Separate formatting and coordination from pricing, representation, and legal claims.', 'Route uncertain property details to the responsible agent before publication.'], watch: 'An assistant should not invent listing claims, interpret contracts, negotiate, or provide advice reserved for a licensed professional.' },
  { slug: 'virtual-assistant-client-intake-organization', title: 'Client intake organization for a virtual assistant', excerpt: 'Make new-client information easier to review by delegating collection, sorting, reminders, and missing-field follow-up.', focus: 'client intake organization', audience: 'consultants, agencies, and service firms handling recurring inquiries', firstSteps: ['Ask only the questions needed for the next decision.', 'Label incomplete records instead of guessing at a client’s needs.', 'Give the owner a short summary of urgency, fit questions, and missing information.'], watch: 'Keep promises, eligibility decisions, sensitive advice, and final acceptance with the authorized owner.' },
  { slug: 'philippines-virtual-assistant-property-management-coordination', title: 'Property-management coordination with a Philippines virtual assistant', excerpt: 'Use remote support for maintenance requests, vendor updates, resident messages, and record organization while preserving emergency and legal escalation paths.', focus: 'property-management coordination', audience: 'property managers balancing resident communication and vendor follow-through', firstSteps: ['Classify requests by urgency, property, vendor, and next owner.', 'Use approved updates that describe status without promising an outcome.', 'Keep a dated record of every handoff and unresolved safety concern.'], watch: 'Emergency conditions, habitability questions, leases, disputes, and commitments should go directly to the responsible manager or professional.' },
  { slug: 'virtual-assistant-podcast-production-admin', title: 'Podcast production administration a virtual assistant can support', excerpt: 'Delegate guest coordination, asset naming, show-note preparation, and calendar follow-up while the host retains editorial and publishing decisions.', focus: 'podcast production administration', audience: 'independent hosts and small media teams', firstSteps: ['Maintain one guest record with contact status, release paperwork, and recording details.', 'Prepare notes from approved source material and mark anything needing host confirmation.', 'Use a handoff that lists missing assets, deadlines, and the next decision.'], watch: 'Do not publish a guest statement, edit for meaning, or reuse private material without the host’s approval.' },
  { slug: 'philippines-virtual-assistant-medical-office-scheduling', title: 'Medical-office scheduling support from a Philippines virtual assistant', excerpt: 'Coordinate appointments, reminders, and non-clinical records work with privacy-aware access and clear clinical escalation.', focus: 'medical-office scheduling support', audience: 'healthcare offices seeking dependable administrative coverage', firstSteps: ['Define which appointment types may be booked and which need staff review.', 'Use the office’s approved identity and privacy checks before sharing details.', 'Send symptoms, clinical questions, and urgent concerns to qualified office staff.'], watch: 'A virtual assistant must not diagnose, triage clinically, interpret records, or make promises about care.' },
  { slug: 'virtual-assistant-construction-project-admin', title: 'Construction project administration for a virtual assistant', excerpt: 'Keep subcontractor documents, delivery updates, meeting notes, and open questions organized without transferring site or contract authority.', focus: 'construction project administration', audience: 'small contractors and project managers', firstSteps: ['Track each document or update against a project, responsible person, and due date.', 'Flag conflicting drawings, scope changes, and missing approvals instead of resolving them by guesswork.', 'Give the project lead a concise list of decisions waiting on them.'], watch: 'Safety instructions, change orders, technical judgments, and contractual commitments remain with qualified project leadership.' },
  { slug: 'philippines-virtual-assistant-recruiting-coordinator', title: 'Recruiting coordination with a Philippines virtual assistant', excerpt: 'Delegate interview scheduling, candidate record updates, and respectful follow-up while keeping selection and employment decisions with the hiring team.', focus: 'recruiting coordination', audience: 'small employers managing a steady flow of applicants', firstSteps: ['Use a consistent candidate record and record only job-relevant information.', 'Send approved scheduling messages and preserve candidate time-zone context.', 'Escalate accommodation requests, sensitive questions, and selection decisions.'], watch: 'Do not make promises about employment, reject candidates using unapproved criteria, or handle sensitive information beyond the agreed role.' },
  { slug: 'virtual-assistant-membership-community-support', title: 'Membership-community support a virtual assistant can provide', excerpt: 'Handle welcome messages, access questions, event reminders, and issue routing while the community owner controls policy and moderation decisions.', focus: 'membership-community support', audience: 'course creators and membership businesses', firstSteps: ['Build a small answer library from current, approved member guidance.', 'Tag questions by access, billing, technical, and conduct categories.', 'Escalate disputes, safety concerns, refunds outside policy, and moderation judgments.'], watch: 'The assistant should not promise access, reveal member information, or make enforcement decisions without the community owner.' },
  { slug: 'philippines-virtual-assistant-logistics-coordination', title: 'Logistics coordination for a Philippines virtual assistant', excerpt: 'Track shipments, confirmations, delivery exceptions, and supplier messages with a clear owner for commitments and customer promises.', focus: 'logistics coordination', audience: 'small ecommerce and product businesses', firstSteps: ['Keep order, carrier, supplier, and exception references together.', 'Use status language that distinguishes a request, a confirmation, and a completed delivery.', 'Escalate damaged goods, customs questions, and missed commitments quickly.'], watch: 'Do not alter commercial terms, promise delivery dates, or approve credits without the designated owner.' },
  { slug: 'virtual-assistant-nonprofit-donor-administration', title: 'Donor administration support for a nonprofit', excerpt: 'Organize acknowledgements, event records, contact updates, and reporting inputs while protecting donor privacy and stewardship decisions.', focus: 'donor administration', audience: 'small nonprofits with lean fundraising teams', firstSteps: ['Use a controlled donor record and record the source of every update.', 'Prepare acknowledgement drafts from approved language and current gift records.', 'Separate data cleanup from decisions about appeals, eligibility, or donor relationships.'], watch: 'Keep restricted information, fundraising promises, tax language, and sensitive donor conversations with authorized nonprofit staff.' },
  { slug: 'philippines-virtual-assistant-course-enrollment-admin', title: 'Course-enrollment administration with a Philippines virtual assistant', excerpt: 'Support enrollment records, learner reminders, access questions, and completion tracking without changing course policy or grading decisions.', focus: 'course-enrollment administration', audience: 'online educators and training providers', firstSteps: ['Match each request to a learner record and the current enrollment policy.', 'Use approved responses for access, schedule, and technical questions.', 'Give instructors a separate list of grading, accommodation, or progress decisions.'], watch: 'Do not alter grades, promise certification, or disclose learner information outside the authorized support path.' },
  { slug: 'virtual-assistant-home-services-dispatch', title: 'Home-services dispatch support a virtual assistant can manage', excerpt: 'Coordinate service requests, appointment windows, technician notes, and customer updates with clear boundaries around diagnosis and quotes.', focus: 'home-services dispatch', audience: 'plumbers, electricians, cleaners, and other local service companies', firstSteps: ['Capture the customer’s location, requested service, access notes, and preferred window.', 'Use approved language for arrival windows and route changes.', 'Escalate safety details, technical diagnosis, and work outside the standard scope.'], watch: 'A remote assistant should not diagnose a hazard, quote unapproved work, or make a promise the field team has not confirmed.' },
  { slug: 'philippines-virtual-assistant-wholesale-order-admin', title: 'Wholesale order administration from a Philippines virtual assistant', excerpt: 'Keep purchase-order details, confirmations, backorders, and account notes organized while an authorized salesperson owns commercial commitments.', focus: 'wholesale order administration', audience: 'small distributors and manufacturers', firstSteps: ['Match every order line to the approved catalog and customer record.', 'Track confirmation, allocation, shipment, and exception states separately.', 'Return substitutions, discounts, and credit requests for approval.'], watch: 'Do not change terms, approve a substitute, or promise inventory without the responsible commercial owner.' },
  { slug: 'virtual-assistant-insurance-office-admin', title: 'Administrative support for an insurance office', excerpt: 'Delegate document collection, appointment coordination, and record follow-up while keeping coverage interpretation and advice with licensed staff.', focus: 'insurance-office administration', audience: 'insurance offices that need organized non-advisory support', firstSteps: ['Use a checklist for required documents and a secure method for receiving them.', 'Label records by client, policy, request, and next action.', 'Route coverage questions and urgent claims to the licensed or authorized team.'], watch: 'Do not interpret coverage, recommend a policy, or give claims advice beyond approved administrative language.' },
  { slug: 'philippines-virtual-assistant-event-coordination', title: 'Event coordination support with a Philippines virtual assistant', excerpt: 'Manage invitee records, vendor confirmations, schedules, and attendee questions while the event owner controls commitments and changes.', focus: 'event coordination', audience: 'businesses and organizations running recurring events', firstSteps: ['Keep one event timeline with a responsible owner for every dependency.', 'Use approved attendee and vendor messages with the latest schedule.', 'Record open decisions separately from confirmed arrangements.'], watch: 'Do not confirm an unapproved spend, change a safety arrangement, or make accessibility promises without the event lead.' },
  { slug: 'virtual-assistant-legal-intake-administration', title: 'Legal intake administration a virtual assistant can support', excerpt: 'Organize initial information, conflict-check inputs, scheduling, and document requests without offering legal advice or deciding whether a matter is accepted.', focus: 'legal intake administration', audience: 'law firms and legal service teams', firstSteps: ['Collect only the firm-approved intake fields through the approved channel.', 'Mark missing facts and conflicts for attorney or authorized staff review.', 'Separate scheduling and document organization from legal analysis.'], watch: 'Do not assess merits, quote legal outcomes, create an attorney-client relationship, or advise a prospective client.' },
  { slug: 'philippines-virtual-assistant-saas-customer-onboarding', title: 'SaaS customer-onboarding support from a Philippines virtual assistant', excerpt: 'Guide customers through approved setup steps, meeting coordination, and account questions while product and security exceptions remain with specialists.', focus: 'SaaS customer onboarding', audience: 'small software companies with growing customer volume', firstSteps: ['Use a customer checklist tied to the plan and implementation stage.', 'Record completed setup steps and unresolved questions in the customer record.', 'Route security, data migration, and product-limit questions to the technical owner.'], watch: 'Never request passwords, promise unsupported functionality, or change customer data without the approved process.' },
  { slug: 'virtual-assistant-financial-advisor-admin', title: 'Administrative support for a financial-advisor practice', excerpt: 'Coordinate meetings, organize approved documents, and track follow-up requests while regulated advice and account decisions stay with the advisor.', focus: 'financial-advisor administration', audience: 'financial practices needing dependable client-service administration', firstSteps: ['Use the practice’s secure document process and identity checks.', 'Track requests by client, advisor, due date, and approval state.', 'Separate document completeness from advice, recommendations, and transactions.'], watch: 'Do not recommend investments, interpret account information, or communicate a transaction as approved without the advisor.' },
  { slug: 'philippines-virtual-assistant-customer-success-follow-up', title: 'Customer-success follow-up with a Philippines virtual assistant', excerpt: 'Prepare check-ins, capture adoption questions, and track promised next steps without letting a coordinator make product or renewal commitments.', focus: 'customer-success follow-up', audience: 'service and software companies managing ongoing client relationships', firstSteps: ['Summarize the last customer outcome before proposing the next touchpoint.', 'Track questions, owner, due date, and promised response separately.', 'Escalate dissatisfaction, churn signals, credits, and scope changes to the account owner.'], watch: 'Do not promise savings, outcomes, renewals, or custom work without the authorized account owner.' },
  { slug: 'virtual-assistant-hr-records-administration', title: 'HR records administration a virtual assistant can support', excerpt: 'Keep employee-document requests, meeting scheduling, and record updates organized while employment decisions and confidential conversations stay with HR leadership.', focus: 'HR records administration', audience: 'small employers with recurring people-operations paperwork', firstSteps: ['Use a restricted record with a defined retention and naming rule.', 'Track document status without copying sensitive details into ordinary chat.', 'Route leave, performance, accommodation, and employment questions to the authorized HR contact.'], watch: 'Do not make employment decisions, interpret policy for a specific dispute, or disclose employee information outside the approved HR process.' },
  { slug: 'philippines-virtual-assistant-restaurant-reservation-admin', title: 'Restaurant reservation administration from a Philippines virtual assistant', excerpt: 'Coordinate reservations, guest questions, event notes, and schedule changes with approved details and a clear path for unusual requests.', focus: 'restaurant reservation administration', audience: 'restaurants and hospitality businesses handling busy booking periods', firstSteps: ['Keep party size, date, time, contact method, and special notes in the booking record.', 'Use the current seating and cancellation guidance when replying.', 'Escalate accessibility needs, large events, complaints, and requests outside policy.'], watch: 'Do not promise a table, waive a policy, or disclose guest information without the manager’s approval.' },
];

const makePost = (spec: AugustSpec, index: number): BlogPost => ({
  slug: spec.slug,
  title: spec.title,
  excerpt: spec.excerpt,
  minutes: 8 + (index % 5),
  updated: '2026-08-13',
  takeaways: [
    `Define the finished output for ${spec.focus} before access is granted.`,
    'Give the assistant examples, a source of truth, and a named person for exceptions.',
    'Review early work for accuracy, tone, completeness, and safe escalation.',
  ],
  sections: [
    { heading: 'Set the first assignment', body: `${spec.title} is easiest to delegate when ${spec.audience} starts with one visible work lane. ${spec.excerpt} Name the trigger, the information available at the start, the finished output, and the person who accepts it.`, bullets: spec.firstSteps },
    { heading: 'Make the handoff specific', body: `For ${spec.focus}, a good handoff gives context without asking the assistant to infer policy. Show a completed example, identify the current source of truth, and state what to do when a record is incomplete. The goal is a useful first pass that a manager can review quickly.` },
    { heading: 'Review the first real items', body: 'Review a small group of live items before widening the assignment. Check whether the record is accurate, whether the message is appropriate, and whether the next person can act without repeating the investigation. If the same question appears twice, improve the handoff rather than expecting silent guesswork.' },
    { heading: 'Protect decisions and access', body: `${spec.watch} Use individual accounts where possible, enable multi-factor authentication, and give access only to the systems needed for this assignment. Recheck permissions when the task lane changes.` },
    { heading: 'Close with an owner-ready update', body: `A useful end-of-day update for ${spec.focus} lists completed items, blocked items, unresolved questions, and the next owner. That small discipline keeps work moving across time zones while leaving judgment and accountability with the right person.` },
  ],
  faqs: [
    { question: 'What should be delegated first?', answer: 'Start with repeatable, reviewable preparation that has a clear output and a safe pause point when context is missing.' },
    { question: 'Who keeps the final decision?', answer: 'The business owner or an authorized professional should keep sensitive commitments, exceptions, regulated advice, and final approvals.' },
  ],
  sources: [source, securitySource],
  internalLinks: ['/services', '/contact'],
  cta: 'Need help defining the role? Share the task lane, tools, schedule, and owner rules with our staffing team.',
});

export const aug13BlogPosts: BlogPost[] = specs.map(makePost);
