import type { BlogPost } from './data';

type AugustSpec = {
  slug: string; title: string; excerpt: string; updated: string; focus: string;
  audience: string; firstSteps: string[]; watch: string;
};

const source = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'planning and managing a small-business team' };
const securitySource = { name: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity practices' };

const specs: AugustSpec[] = [
  { slug: 'virtual-assistant-calendar-triage', title: 'Calendar triage a virtual assistant can handle', excerpt: 'Turn meeting requests into organized options, clear conflicts, and an owner-approved schedule.', updated: '2026-08-13', focus: 'calendar triage', audience: 'founders and client-service teams with crowded calendars', firstSteps: ['Define meeting types, protected time, and who may approve exceptions.', 'Ask for the minimum information needed before offering a slot.', 'Return conflicts as a short decision list rather than moving meetings silently.'], watch: 'Do not accept commitments, cancel priority meetings, or infer availability rules without the calendar owner.' },
  { slug: 'philippines-virtual-assistant-lead-research', title: 'Lead-research support from a Philippines virtual assistant', excerpt: 'Organize public business information into reviewable prospect records without overstating fit or making outreach promises.', updated: '2026-08-13', focus: 'lead research', audience: 'small B2B teams building a focused prospect list', firstSteps: ['Define the target customer and the fields that count as evidence.', 'Record source links and dates so a reviewer can check each entry.', 'Separate researched facts from hypotheses about need or buying intent.'], watch: 'Do not invent contact details, imply endorsement, or send outreach without the responsible owner.' },
  { slug: 'virtual-assistant-inbox-routing', title: 'Inbox routing for a virtual assistant', excerpt: 'Sort incoming messages by owner, urgency, and next action while preserving the sender’s context.', updated: '2026-08-13', focus: 'inbox routing', audience: 'service businesses handling recurring customer and vendor email', firstSteps: ['Create a small label set based on decisions the team actually makes.', 'Mark messages that need an owner response instead of drafting a guess.', 'Keep an exception queue for sensitive, urgent, or unclear requests.'], watch: 'Do not delete, promise, negotiate, or disclose private information outside approved handling rules.' },
  { slug: 'philippines-virtual-assistant-crm-cleanup', title: 'CRM cleanup with a Philippines virtual assistant', excerpt: 'Improve duplicate detection, field completeness, and follow-up visibility without changing relationship history by guesswork.', updated: '2026-08-13', focus: 'CRM cleanup', audience: 'small sales teams whose customer records have drifted', firstSteps: ['Agree on the source of truth for names, companies, and status fields.', 'Flag probable duplicates for review instead of merging uncertain records.', 'Log every substantive change and preserve the original context.'], watch: 'Do not erase history, alter ownership, or label a prospect qualified without the sales owner.' },
  { slug: 'virtual-assistant-client-meeting-notes', title: 'Client meeting notes a virtual assistant can prepare', excerpt: 'Convert approved recordings or notes into decisions, owners, and open questions that a client team can act on.', updated: '2026-08-13', focus: 'client meeting notes', audience: 'consultancies and agencies that need dependable follow-through', firstSteps: ['Use a consistent structure for decisions, actions, risks, and unresolved points.', 'Mark uncertain wording for review rather than presenting it as a commitment.', 'Send the draft to the meeting owner before external circulation.'], watch: 'Do not create commitments, interpret legal language, or distribute confidential notes to an unapproved audience.' },
  { slug: 'philippines-virtual-assistant-travel-coordination', title: 'Travel coordination support from a Philippines virtual assistant', excerpt: 'Assemble itinerary options, confirmations, and traveler details while the traveler controls final choices and changes.', updated: '2026-08-13', focus: 'travel coordination', audience: 'busy professionals and small teams arranging business travel', firstSteps: ['Record constraints such as dates, location, accessibility, and approved preferences.', 'Keep options distinct from confirmed reservations and show cancellation conditions.', 'Use a final approval checkpoint before booking or changing anything.'], watch: 'Do not book, spend, disclose passport information, or make safety judgments without authorization.' },
  { slug: 'virtual-assistant-ecommerce-catalog-maintenance', title: 'Ecommerce catalog maintenance for a virtual assistant', excerpt: 'Keep product attributes, approved copy, and inventory notes consistent across a small online catalog.', updated: '2026-08-13', focus: 'catalog maintenance', audience: 'product businesses managing frequent catalog updates', firstSteps: ['Set a field-by-field source of truth and a review status for every change.', 'Compare proposed edits with approved product information.', 'Separate formatting corrections from claims about performance or compliance.'], watch: 'Do not invent specifications, change commercial terms, or publish an unapproved product claim.' },
  { slug: 'philippines-virtual-assistant-review-response-drafts', title: 'Review-response drafts with a Philippines virtual assistant', excerpt: 'Prepare calm, context-aware replies to customer reviews for owner approval before anything is published.', updated: '2026-08-13', focus: 'review-response drafts', audience: 'local and online businesses receiving regular customer feedback', firstSteps: ['Gather the order or visit context without exposing private details.', 'Match the draft to approved tone and escalation language.', 'Keep complaints needing investigation separate from routine thanks.'], watch: 'Do not argue with a customer, promise compensation, or publish a response without approval.' },
  { slug: 'virtual-assistant-vendor-onboarding-records', title: 'Vendor onboarding records a virtual assistant can organize', excerpt: 'Track approved vendor documents, contacts, renewal dates, and outstanding questions in one reviewable record.', updated: '2026-08-13', focus: 'vendor onboarding records', audience: 'small companies working with a growing group of suppliers', firstSteps: ['List required documents and the person responsible for each review.', 'Store source links and renewal dates alongside the vendor record.', 'Flag missing insurance, tax, or contract items for the authorized owner.'], watch: 'Do not approve a vendor, interpret a contract, or certify compliance on someone else’s behalf.' },
  { slug: 'philippines-virtual-assistant-social-media-inbox', title: 'Social-media inbox support from a Philippines virtual assistant', excerpt: 'Sort questions, comments, and messages into approved response lanes without turning a coordinator into a spokesperson.', updated: '2026-08-13', focus: 'social-media inbox support', audience: 'small brands with active social channels', firstSteps: ['Build a current answer library from approved public information.', 'Label sales, service, safety, and reputation-sensitive messages separately.', 'Escalate anything that needs a factual investigation or public statement.'], watch: 'Do not debate, disclose customer information, make claims, or publish sensitive replies without the brand owner.' },
  { slug: 'virtual-assistant-course-content-coordination', title: 'Course-content coordination for a virtual assistant', excerpt: 'Keep lesson assets, reviewer comments, links, and release dependencies organized for an educator.', updated: '2026-08-13', focus: 'course-content coordination', audience: 'educators and training teams managing recurring lesson updates', firstSteps: ['Track each asset by lesson, owner, status, and approved version.', 'Separate copyediting notes from instructional or assessment decisions.', 'Give the instructor a short release-readiness list.'], watch: 'Do not change learning outcomes, grades, accessibility commitments, or published lessons without the instructor.' },
  { slug: 'philippines-virtual-assistant-membership-renewal-admin', title: 'Membership renewal administration from a Philippines virtual assistant', excerpt: 'Organize renewal reminders, account questions, and exception requests while policy and retention decisions remain with the owner.', updated: '2026-08-13', focus: 'membership renewal administration', audience: 'membership businesses with recurring account follow-up', firstSteps: ['Use the current member status and renewal policy as the source of truth.', 'Separate routine reminders from cancellation, refund, and access exceptions.', 'Record the next owner and due date for every unresolved case.'], watch: 'Do not change access, promise a refund, or negotiate an exception without authorization.' },
  { slug: 'virtual-assistant-purchase-order-tracking', title: 'Purchase-order tracking a virtual assistant can manage', excerpt: 'Keep order acknowledgements, delivery milestones, and discrepancies visible to the person responsible for buying.', updated: '2026-08-13', focus: 'purchase-order tracking', audience: 'small operations teams managing recurring supplier orders', firstSteps: ['Match every update to the approved order and supplier contact.', 'Distinguish requested, acknowledged, shipped, and received states.', 'Escalate quantity, quality, and timing discrepancies with source documents.'], watch: 'Do not authorize a purchase, accept a substitute, or approve an invoice discrepancy.' },
  { slug: 'philippines-virtual-assistant-appointment-reminders', title: 'Appointment reminders with a Philippines virtual assistant', excerpt: 'Coordinate clear reminders and rescheduling requests while protecting the provider’s policy and the client’s private details.', updated: '2026-08-13', focus: 'appointment reminders', audience: 'professional practices and service providers with recurring appointments', firstSteps: ['Use the approved reminder timing, identity check, and message template.', 'Record confirmation, cancellation, and no-response states separately.', 'Route clinical, legal, or technical questions to qualified staff.'], watch: 'Do not give advice, reveal unnecessary details, or promise an appointment outcome outside the provider’s rules.' },
  { slug: 'virtual-assistant-business-document-indexing', title: 'Business-document indexing for a virtual assistant', excerpt: 'Make contracts, policies, certificates, and working files easier to find without changing their meaning or access rights.', updated: '2026-08-13', focus: 'document indexing', audience: 'small businesses with shared drives that have outgrown informal filing', firstSteps: ['Choose stable names for document type, owner, date, and status.', 'Link the index to the source file and preserve version history.', 'Flag unclear ownership or retention questions for management.'], watch: 'Do not edit legal meaning, delete records, or widen access to sensitive documents.' },
  { slug: 'philippines-virtual-assistant-newsletter-coordination', title: 'Newsletter coordination from a Philippines virtual assistant', excerpt: 'Assemble approved links, audience segments, and review notes so an owner can send a clear newsletter on schedule.', updated: '2026-08-13', focus: 'newsletter coordination', audience: 'small organizations publishing regular customer updates', firstSteps: ['Collect copy and links from named sources and check that they are current.', 'Maintain a separate list of audience, consent, and exclusion rules.', 'Prepare a review checklist for claims, links, names, and formatting.'], watch: 'Do not add unsupported claims, alter consent settings, or send a campaign without the authorized publisher.' },
  { slug: 'virtual-assistant-service-quote-intake', title: 'Service-quote intake a virtual assistant can organize', excerpt: 'Capture the facts a service team needs before preparing a quote, while scope and commercial decisions stay with the responsible expert.', updated: '2026-08-13', focus: 'service-quote intake', audience: 'local service businesses receiving varied project requests', firstSteps: ['Ask for the approved intake fields and supporting photos or documents.', 'Mark unknowns clearly and summarize what still needs a site or expert review.', 'Route the completed intake to the person who sets scope and terms.'], watch: 'Do not diagnose, estimate, quote, or promise availability without the responsible service owner.' },
  { slug: 'philippines-virtual-assistant-customer-record-updates', title: 'Customer-record updates with a Philippines virtual assistant', excerpt: 'Keep contact details, preferences, and service history current through documented, reviewable updates.', updated: '2026-08-13', focus: 'customer-record updates', audience: 'small service teams that rely on accurate customer context', firstSteps: ['Verify the source and date of every requested change.', 'Keep sensitive fields limited to the approved system and access group.', 'Flag conflicting information instead of silently choosing one version.'], watch: 'Do not expose private data, merge uncertain identities, or change service status without authorization.' },
  { slug: 'virtual-assistant-business-trip-expense-prep', title: 'Business-trip expense preparation for a virtual assistant', excerpt: 'Gather receipts, match them to approved trips, and prepare a review packet without taking over reimbursement decisions.', updated: '2026-08-13', focus: 'expense preparation', audience: 'small teams with frequent travel and scattered receipts', firstSteps: ['Use a trip record with traveler, dates, purpose, and approval reference.', 'Separate missing receipts and unusual items from complete entries.', 'Return a review-ready packet to the person who approves reimbursement.'], watch: 'Do not approve expenses, alter receipts, or infer tax treatment from incomplete information.' },
  { slug: 'philippines-virtual-assistant-operations-dashboard-updates', title: 'Operations-dashboard updates from a Philippines virtual assistant', excerpt: 'Collect approved status inputs and highlight missing updates so managers can see the work that needs attention.', updated: '2026-08-13', focus: 'operations-dashboard updates', audience: 'small teams coordinating work across several service lanes', firstSteps: ['Define each status and the source that supports it.', 'Show stale, missing, and blocked items separately from completed work.', 'Add an owner and next action to every exception.'], watch: 'Do not fabricate progress, change targets, or present an interpretation as a measured result.' },
  { slug: 'virtual-assistant-community-event-follow-up', title: 'Community-event follow-up a virtual assistant can coordinate', excerpt: 'Organize attendee notes, promised resources, and next conversations after an event while the host controls relationship decisions.', updated: '2026-08-13', focus: 'community-event follow-up', audience: 'networking groups and small organizations hosting useful events', firstSteps: ['Match each note to the attendee’s consented contact record.', 'Separate promised resources from ideas that still need approval.', 'Create a short follow-up queue with owner and due date.'], watch: 'Do not add people to a list, disclose attendee details, or make partnership promises without approval.' },
  { slug: 'philippines-virtual-assistant-local-listing-updates', title: 'Local-listing updates with a Philippines virtual assistant', excerpt: 'Keep approved business hours, contact details, and service descriptions consistent across local directories while an owner approves public changes.', updated: '2026-08-13', focus: 'local-listing updates', audience: 'local businesses managing several public directory profiles', firstSteps: ['Compare each listing with the approved business record and note the source date.', 'Queue mismatches with the exact field and proposed correction.', 'Ask the owner to review changes involving claims, categories, or service areas.'], watch: 'Do not create a listing, publish an unverified claim, or alter a public profile without the authorized owner.' },
];

const makePost = (spec: AugustSpec, index: number): BlogPost => ({
  slug: spec.slug, title: spec.title, excerpt: spec.excerpt, minutes: 8 + (index % 5), updated: spec.updated,
  takeaways: [`Define the finished output for ${spec.focus} before access is granted.`, 'Give the assistant examples, a source of truth, and a named person for exceptions.', 'Review early work for accuracy, tone, completeness, and safe escalation.'],
  sections: [
    { heading: 'Set the first assignment', body: `${spec.title} is easiest to delegate when ${spec.audience} starts with one visible work lane. ${spec.excerpt} Name the trigger, the information available at the start, the finished output, and the person who accepts it.`, bullets: spec.firstSteps },
    { heading: 'Make the handoff specific', body: `For ${spec.focus}, a good handoff gives context without asking the assistant to infer policy. Show a completed example, identify the current source of truth, and state what to do when a record is incomplete. The goal is a useful first pass that a manager can review quickly.` },
    { heading: 'Review the first real items', body: 'Review a small group of live items before widening the assignment. Check whether the record is accurate, whether the message is appropriate, and whether the next person can act without repeating the investigation. If the same question appears twice, improve the handoff rather than expecting silent guesswork.' },
    { heading: 'Protect decisions and access', body: `${spec.watch} Use individual accounts where possible, enable multi-factor authentication, and give access only to the systems needed for this assignment. Recheck permissions when the task lane changes.` },
  ],
  faqs: [
    { question: `What should the first ${spec.focus} assignment include?`, answer: `Start with one repeatable output, a current example, the source of truth, and a named reviewer. Keep exceptions visible until the owner sees a reliable pattern.` },
    { question: 'How should a business review the work?', answer: 'Review accuracy, completeness, tone, and escalation. A short feedback loop is more useful than a vague request to be careful.' },
    { question: 'What access is appropriate?', answer: 'Only the systems and fields needed for the agreed task. Keep approvals, sensitive records, and consequential decisions with the authorized owner.' },
  ],
  sources: [source, securitySource],
});

export const aug13BlogPosts: BlogPost[] = specs.map(makePost);
