import type { BlogPost } from './data';

type Spec = {
  slug: string; title: string; excerpt: string; updated: '2026-08-17';
  audience: string; output: string; checks: string[]; boundary: string; owner: string;
  faq: string;
};

const sba = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'small-business team planning' };
const nist = { name: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity practices' };

const specs: Spec[] = [
  { slug: 'philippines-virtual-assistant-content-brief-intake', title: 'Content-brief intake with a Philippines virtual assistant', excerpt: 'Turn a site owner’s rough article request into a reviewable brief without letting missing strategy become invented direction.', updated: '2026-08-17', audience: 'small businesses that have article ideas arriving through email, calls, or shared notes', output: 'a brief containing the reader, question, purpose, evidence needs, and approval owner', checks: ['Capture the requested audience and decision the article should support.', 'Separate supplied facts from questions that still need research.', 'Flag conflicting instructions before an outline is drafted.'], boundary: 'Do not choose a claim, promise search performance, or turn a vague idea into an approved assignment.', owner: 'The site owner approves the brief and its editorial angle.', faq: 'Start with the reader question, intended action, source material, and one named reviewer.' },
  { slug: 'virtual-assistant-editorial-calendar-maintenance', title: 'Editorial-calendar maintenance a virtual assistant can handle', excerpt: 'Keep article ideas, owners, deadlines, and status visible so a publishing calendar remains a planning tool rather than a promise of output.', updated: '2026-08-17', audience: 'site owners coordinating recurring blog work across writers, reviewers, and subject experts', output: 'a dated calendar with status, owner, dependency, and next action', checks: ['Use a single status vocabulary for idea, briefed, drafting, review, and ready.', 'Record why a date moved instead of silently overwriting history.', 'Keep blocked topics visible with a named unblocker.'], boundary: 'Do not move a deadline to hide risk, mark an article ready, or publish without the required review.', owner: 'The editorial owner decides priority, timing, and readiness.', faq: 'A useful calendar shows the next action and blocker, not only a title and date.' },
  { slug: 'philippines-virtual-assistant-source-registers-for-blogging', title: 'Source-register upkeep from a Philippines virtual assistant', excerpt: 'Create a traceable record of links, access dates, and claims so article review can distinguish evidence from an appealing but unsupported sentence.', updated: '2026-08-17', audience: 'blog teams researching operational questions for owners and service buyers', output: 'a source register linking each important claim to a public reference and review note', checks: ['Record the page title, URL, access date, and claim supported.', 'Mark a source as context, evidence, or an unresolved lead.', 'Keep conflicting sources side by side for an editor to resolve.'], boundary: 'Do not treat a search snippet as proof, fabricate a citation, or make a legal or financial conclusion.', owner: 'The editor or qualified subject owner decides whether evidence is sufficient.', faq: 'A source register is strongest when another reviewer can retrace every material claim.' },
  { slug: 'virtual-assistant-blog-outline-review', title: 'Blog-outline review a virtual assistant can prepare', excerpt: 'Stress-test an article outline against the reader’s real decision before drafting time is spent on a weak or generic structure.', updated: '2026-08-17', audience: 'service businesses whose articles need to answer practical hiring and delegation questions', output: 'an outline showing the question answered, sequence of sections, examples, and open evidence gaps', checks: ['Check that each heading advances the main reader decision.', 'Add a concrete scenario and a boundary where the topic needs one.', 'List repeated ideas that should be combined or removed.'], boundary: 'Do not rewrite a subject expert’s position, add unsupported expertise, or approve the outline as final copy.', owner: 'The editor owns the thesis and accepts the outline for drafting.', faq: 'Review an outline for reader logic, specificity, evidence gaps, and role boundaries before prose.' },
  { slug: 'philippines-virtual-assistant-article-fact-check-queue', title: 'Article fact-check queues for a Philippines virtual assistant', excerpt: 'Route factual checks by claim type and evidence so an assistant can reduce avoidable errors without pretending to be the subject-matter approver.', updated: '2026-08-17', audience: 'small content teams publishing guidance about remote staffing and business operations', output: 'a claim queue with source, check type, result, and escalation status', checks: ['Separate dates, definitions, process claims, and recommendations.', 'Record the exact wording checked and the source used.', 'Escalate claims that depend on jurisdiction, contract terms, or professional advice.'], boundary: 'Do not certify legal, tax, medical, employment, or security advice.', owner: 'The editor and relevant qualified reviewer resolve material uncertainty.', faq: 'Queue claims by risk and evidence type, then leave a clear trail for the final reviewer.' },
  { slug: 'virtual-assistant-blog-draft-comment-triage', title: 'Blog-draft comment triage a virtual assistant can support', excerpt: 'Turn scattered draft comments into grouped, actionable review items without flattening disagreements into silent edits.', updated: '2026-08-17', audience: 'owners reviewing articles with a writer, subject expert, and quality reviewer', output: 'a comment log grouped by factual, structural, clarity, and approval issues', checks: ['Preserve the original comment and identify the section it concerns.', 'Group duplicates while retaining distinct reasons.', 'Mark unresolved disagreements for the named decision owner.'], boundary: 'Do not resolve a substantive disagreement by personal preference or delete an inconvenient review record.', owner: 'The editor decides which comments change the article.', faq: 'Triage should make comments easier to decide, not decide them by hiding disagreement.' },
  { slug: 'philippines-virtual-assistant-blog-qa-sampling', title: 'Blog quality sampling with a Philippines virtual assistant', excerpt: 'Use a small, consistent sample of finished articles to spot recurring misses before adding more publishing volume.', updated: '2026-08-17', audience: 'site owners who need a repeatable review rhythm for practical blog guidance', output: 'a dated sample record covering accuracy, usefulness, links, formatting, and boundaries', checks: ['Use the same checklist across a small set of recent articles.', 'Record examples rather than only assigning a pass or fail.', 'Separate a one-off typo from a process pattern.'], boundary: 'Do not claim that a sample proves every article is correct or replace expert review for high-risk topics.', owner: 'The editorial owner decides corrective action and release readiness.', faq: 'Sampling is useful when its limits are explicit and each finding points to a fix.' },
  { slug: 'virtual-assistant-blog-revision-log', title: 'Blog revision logs a virtual assistant can maintain', excerpt: 'Preserve why an article changed so owners can review factual and editorial decisions without comparing every version by hand.', updated: '2026-08-17', audience: 'business blogs that update evergreen guidance as processes and evidence change', output: 'a revision log with date, section, reason, reviewer, and source for each material change', checks: ['Describe the change in plain language and link its evidence.', 'Distinguish typo fixes from changes to a recommendation or claim.', 'Keep the prior approved version identifiable.'], boundary: 'Do not rewrite history, delete an approved record, or decide that a material change is harmless.', owner: 'The editor approves substantive revisions and their publication date.', faq: 'Log material changes with their reason and reviewer so future updates remain accountable.' },
  { slug: 'philippines-virtual-assistant-internal-link-relevance-review', title: 'Internal-link relevance review from a Philippines virtual assistant', excerpt: 'Map useful next reads between staffing guides without forcing links that distract from the reader’s immediate question.', updated: '2026-08-17', audience: 'Overseas Virtual Assistant readers comparing role scope, onboarding, access, and daily operations', output: 'a link map showing source article, destination, anchor intent, and relevance note', checks: ['Link only when the destination answers a natural next question.', 'Use descriptive anchor text that matches the destination.', 'Flag outdated or thin destinations instead of routing readers into them.'], boundary: 'Do not add links for volume, misrepresent a page’s content, or alter unrelated articles without approval.', owner: 'The site owner or editor approves link placement and destination changes.', faq: 'A good internal link reduces the reader’s next-step uncertainty and accurately describes its destination.' },
  { slug: 'virtual-assistant-blog-image-alt-text-review', title: 'Blog image alt-text review a virtual assistant can prepare', excerpt: 'Keep article image descriptions useful to screen-reader users while separating accessibility text from decorative or promotional copy.', updated: '2026-08-17', audience: 'small sites adding diagrams, screenshots, or team-work visuals to staffing guides', output: 'alt text and a decorative-image recommendation tied to each article image', checks: ['Describe the information the image contributes, not every visual detail.', 'Use an empty decorative alternative when the image adds no content.', 'Flag text inside an image that needs an accessible equivalent.'], boundary: 'Do not invent what a photo depicts, stuff keywords into alt text, or replace accessibility review with a search claim.', owner: 'The editor or site owner approves the final image treatment.', faq: 'Describe the image’s purpose for the reader; omit decorative detail that adds no meaning.' },
  { slug: 'philippines-virtual-assistant-blog-update-opportunities', title: 'Blog update opportunities a Philippines virtual assistant can identify', excerpt: 'Find aging guidance worth reviewing by comparing its claims, reader intent, and current references rather than refreshing pages on a timer.', updated: '2026-08-17', audience: 'owners maintaining a growing library of virtual-assistant hiring and operations guides', output: 'a prioritized update queue with reason, affected section, evidence need, and owner', checks: ['Look for expired dates, changed tools, broken references, and unclear boundaries.', 'Separate a worthwhile update from a cosmetic rewrite.', 'Prioritize pages whose advice could mislead a current buyer or operator.'], boundary: 'Do not change published advice, date, or title merely to look current.', owner: 'The editor decides whether an update is needed and what it should change.', faq: 'Prioritize updates by reader risk and evidence change, not by age alone.' },
  { slug: 'virtual-assistant-blog-reader-question-mining', title: 'Reader-question mining for a virtual assistant blog', excerpt: 'Organize recurring questions from approved public channels into useful article opportunities without treating anecdote as universal demand.', updated: '2026-08-17', audience: 'staffing sites trying to answer the practical questions buyers ask before delegating work', output: 'a question bank with source, audience, decision stage, and proposed editorial treatment', checks: ['Keep the original question separate from its summary.', 'Group similar questions only when their decisions are genuinely the same.', 'Record what evidence would be needed before making a recommendation.'], boundary: 'Do not expose private messages, invent a trend, or turn one person’s situation into a universal claim.', owner: 'The content owner chooses which questions become public guidance.', faq: 'Use question mining to discover reader language while preserving context and privacy.' },
  { slug: 'philippines-virtual-assistant-blog-search-intent-briefs', title: 'Search-intent briefs from a Philippines virtual assistant', excerpt: 'Clarify what a searcher needs to decide before an article is planned, keeping keyword language subordinate to a useful staffing answer.', updated: '2026-08-17', audience: 'service businesses planning articles around overseas hiring and delegated operations', output: 'a brief with query language, reader situation, answer promise, exclusions, and success test', checks: ['Describe the underlying decision rather than listing related phrases.', 'Identify what the article should not claim or compare.', 'Write a success test based on reader usefulness and completeness.'], boundary: 'Do not promise rankings, stuff phrases into copy, or choose a topic solely because it has a broad label.', owner: 'The editor approves the audience, thesis, and scope.', faq: 'An intent brief explains the reader’s situation and decision, not just the words in a query.' },
  { slug: 'virtual-assistant-blog-content-repurpose-map', title: 'Content-repurpose mapping a virtual assistant can organize', excerpt: 'Map one approved staffing insight to appropriate supporting formats without copying an article into a thinner duplicate.', updated: '2026-08-17', audience: 'small teams turning an approved guide into an email, checklist, or sales enablement reference', output: 'a format map showing the source idea, new audience need, required edits, and approval owner', checks: ['Identify what context the new format must retain.', 'Mark claims that need rechecking after the format changes.', 'Keep each derivative useful on its own without duplicating the source body.'], boundary: 'Do not publish a derivative, quote beyond permission, or imply a new format is independently researched.', owner: 'The content owner approves reuse scope and final wording.', faq: 'Repurpose the decision and context, not a copied body with a new heading.' },
  { slug: 'philippines-virtual-assistant-editorial-risk-register', title: 'Editorial risk registers with a Philippines virtual assistant', excerpt: 'Make sensitive claims, missing evidence, and unclear role boundaries visible before a practical business article reaches publication.', updated: '2026-08-17', audience: 'blogs explaining staffing, customer support, bookkeeping support, and delegated business work', output: 'a risk register with claim, consequence, mitigation, and decision owner', checks: ['Mark claims involving privacy, money, employment, safety, or professional advice.', 'Pair each risk with a concrete review or exclusion.', 'Escalate risks whose answer depends on jurisdiction or contract facts.'], boundary: 'Do not assign a risk rating as a substitute for qualified advice or publish a mitigation that was not reviewed.', owner: 'The editor and qualified owner decide how high-risk material is handled.', faq: 'A risk register helps reviewers focus on where an article could mislead or overstep.' },
  { slug: 'virtual-assistant-blog-publishing-checklist', title: 'Blog publishing checklists a virtual assistant can prepare', excerpt: 'Gather the small release checks that protect readers from broken routes, missing dates, weak links, and unfinished review.', updated: '2026-08-17', audience: 'site owners publishing practical articles on a recurring schedule', output: 'a release checklist covering content approval, metadata, links, accessibility, and route checks', checks: ['Confirm the title, date, canonical, and article body agree.', 'Test links and verify required sources are present.', 'Record exceptions rather than checking a box for an unverified item.'], boundary: 'Do not declare publication complete when an owner approval or material check is missing.', owner: 'The publishing owner gives final release approval.', faq: 'Keep checks short, observable, and tied to an owner who can resolve failures.' },
  { slug: 'philippines-virtual-assistant-blog-content-brief-library', title: 'Content-brief library upkeep from a Philippines virtual assistant', excerpt: 'Keep approved article briefs findable and comparable so recurring blog work does not restart from scattered conversations.', updated: '2026-08-17', audience: 'teams with a backlog of staffing topics and several people contributing to article planning', output: 'a searchable brief library with status, audience, thesis, sources, and owner', checks: ['Use stable fields so briefs can be compared without rewriting them.', 'Mark superseded briefs and retain the reason for the change.', 'Check a new idea against existing theses before adding it.'], boundary: 'Do not merge distinct reader problems merely to reduce the backlog or mark an unapproved idea as active.', owner: 'The editorial owner controls scope, priority, and archive decisions.', faq: 'A brief library reduces repeated planning when each record keeps its thesis and approval state.' },
  { slug: 'virtual-assistant-blog-topic-deduplication', title: 'Blog-topic deduplication a virtual assistant can support', excerpt: 'Compare proposed topics by reader decision and thesis so a new title does not quietly repeat an existing staffing guide.', updated: '2026-08-17', audience: 'content owners with overlapping ideas about hiring, onboarding, access, and assistant operations', output: 'a comparison note showing overlap, distinct angle, and recommendation to merge, defer, or proceed', checks: ['Compare the reader problem, not just the words in two titles.', 'Check examples and conclusion for substantive overlap.', 'Keep a distinct topic when the decision, audience, or role boundary differs.'], boundary: 'Do not kill a useful topic because it shares a broad keyword or rename a duplicate and call it original.', owner: 'The editor decides topic identity and canonical coverage.', faq: 'Deduplicate by thesis and reader decision; title similarity alone is not enough.' },
  { slug: 'philippines-virtual-assistant-blog-editorial-handoff', title: 'Editorial handoffs from a Philippines virtual assistant', excerpt: 'Give a writer or reviewer a compact, accurate handoff that preserves the reader question, evidence, status, and unresolved decisions.', updated: '2026-08-17', audience: 'distributed content teams working across time zones on practical staffing articles', output: 'a handoff note with current status, files, next action, open questions, and owner', checks: ['Link the current brief, draft, sources, and review notes.', 'State what is complete and what is only proposed.', 'Use timestamps and time zones for deadline-sensitive work.'], boundary: 'Do not imply approval, hide an exception, or transfer a sensitive decision without naming its owner.', owner: 'The receiving editor confirms the handoff and next action.', faq: 'A handoff should let the next person continue safely without reconstructing the whole conversation.' },
  { slug: 'virtual-assistant-blog-editorial-sop-review', title: 'Editorial SOP review a virtual assistant can organize', excerpt: 'Keep article-work instructions aligned with the actual review path so a routine supports judgment instead of replacing it.', updated: '2026-08-17', audience: 'small site teams documenting repeatable article planning and review work', output: 'an SOP review note listing step, owner, input, output, exception, and evidence of current use', checks: ['Compare each step with a recent real example.', 'Mark instructions that depend on an outdated tool or role.', 'Add a stop rule where the work crosses into approval or professional judgment.'], boundary: 'Do not rewrite policy, remove a control because it is inconvenient, or treat an SOP as proof that work was completed.', owner: 'The process owner approves changes to the editorial SOP.', faq: 'Review an SOP against real work and make exceptions explicit before adding more steps.' },
  { slug: 'philippines-virtual-assistant-blog-article-accessibility-review', title: 'Article accessibility review from a Philippines virtual assistant', excerpt: 'Check headings, link labels, lists, and readable structure so a staffing guide works for more readers before its owner approves release.', updated: '2026-08-17', audience: 'public-facing business blogs serving readers on different devices and assistive technologies', output: 'an accessibility note with observed issue, affected section, suggested fix, and reviewer status', checks: ['Check heading order and whether each section has a clear purpose.', 'Look for vague link labels, dense paragraphs, and unexplained abbreviations.', 'Separate an observed issue from a proposed correction.'], boundary: 'Do not claim compliance with a law or standard without qualified review or test beyond the approved scope.', owner: 'The content owner decides fixes and obtains specialist review when needed.', faq: 'An accessibility pass should identify concrete reader barriers without overstating what was tested.' },
  { slug: 'virtual-assistant-blog-editorial-backlog-prioritization', title: 'Editorial-backlog prioritization a virtual assistant can prepare', excerpt: 'Give an owner a defensible way to order article work by reader value, evidence readiness, risk, and effort.', updated: '2026-08-17', audience: 'site owners balancing a daily article routine with limited review and subject-expert time', output: 'a ranked backlog with reader need, evidence status, risk, dependency, and next action', checks: ['Use agreed criteria and show the reason for each rank.', 'Keep urgent corrections separate from new topic ideas.', 'Highlight dependencies that make a high-value topic not yet ready.'], boundary: 'Do not promise a delivery date, optimize for volume alone, or bury a high-risk correction under new ideas.', owner: 'The owner chooses the final sequence and commits available review time.', faq: 'Prioritize the work that is useful, supportable, and safe to review now.' },
];

const makePost = (spec: Spec, index: number): BlogPost => ({
  slug: spec.slug,
  title: spec.title,
  excerpt: spec.excerpt,
  minutes: 8 + (index % 5),
  updated: spec.updated,
  takeaways: [spec.output, 'Use a current example, a named reviewer, and a visible exception path.', 'Keep preparation separate from approval, publication, and professional judgment.'],
  sections: [
    { heading: 'Define the useful output', body: `${spec.title} is most useful when ${spec.audience} starts with a clearly bounded assignment. ${spec.excerpt} Write down the trigger, inputs, finished output, and reviewer before the work begins.`, bullets: spec.checks },
    { heading: 'Keep evidence and uncertainty visible', body: `For this work, the record should make its source and status easy to inspect. ${spec.output} is only ready when its missing information, assumptions, and unresolved questions are visible rather than hidden behind a polished summary.` },
    { heading: 'Use a deliberate handoff', body: `A reliable handoff names the next decision and gives the owner the context needed to make it. ${spec.boundary} Preparation can shorten review, but it cannot turn an unchecked item into an approved one.` },
    { heading: 'Start with controlled access', body: 'Give access only to the systems needed for the first assignment. Use individual accounts where possible, enable multi-factor authentication, and review access when the work expands or ends.' },
  ],
  faqs: [{ question: `What should the first ${spec.title.toLowerCase().replace(/^.*?with a |^.*?from a |^.*?a /, '')} assignment include?`, answer: spec.faq }, { question: 'Who keeps the final decision?', answer: spec.owner }],
  sources: [sba, nist],
});

export const aug17BlogPosts: BlogPost[] = specs.map(makePost);
