import type { BlogPost } from './data';

type AugustSpec = { slug: string; title: string; excerpt: string; published: string; focus: string; audience: string; firstSteps: string[]; watch: string };
const source = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'planning and managing a small-business team' };
const securitySource = { name: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity practices' };

const specs: AugustSpec[] = [
  { slug: 'virtual-assistant-client-portal-intake', title: 'Client-portal intake support for a virtual assistant', excerpt: 'Turn scattered client-portal submissions into a clear, reviewable starting record for the service team.', published: '2026-08-13', focus: 'client-portal intake', audience: 'consultancies receiving files, questions, and project details through an online portal', firstSteps: ['Define required fields before review.', 'Mark missing context instead of guessing.', 'Attach the source to the intake summary.'], watch: 'Do not accept scope, promise timing, or expose another client’s files.' },
  { slug: 'philippines-virtual-assistant-renewal-calendar', title: 'Renewal-calendar support from a Philippines virtual assistant', excerpt: 'Keep recurring agreement dates visible so owners can review decisions before deadlines arrive.', published: '2026-08-13', focus: 'renewal-calendar support', audience: 'small teams managing recurring agreements and client follow-up', firstSteps: ['Record the source, date, notice window, and owner.', 'Separate an approaching date from a renewal decision.', 'Send the review queue early.'], watch: 'Do not renew, cancel, negotiate, or represent an agreement as approved.' },
  { slug: 'virtual-assistant-customer-onboarding-checklist', title: 'Customer-onboarding checklists a virtual assistant can maintain', excerpt: 'Keep welcome steps, requested information, and unresolved setup questions organized for a consistent handoff.', published: '2026-08-13', focus: 'customer-onboarding checklists', audience: 'service businesses guiding customers through several early steps', firstSteps: ['Tie each item to an approved promise or source.', 'Show waiting, completed, and blocked states.', 'Return one owner-ready question list.'], watch: 'Do not promise results, change settings, or mark a customer complete without evidence.' },
  { slug: 'philippines-virtual-assistant-knowledge-base-curation', title: 'Knowledge-base curation with a Philippines virtual assistant', excerpt: 'Collect repeated customer questions and approved answers so help content stays useful and current.', published: '2026-08-13', focus: 'knowledge-base curation', audience: 'small support teams whose answers are spread across inboxes and documents', firstSteps: ['Group questions by the decision a reader needs.', 'Link answers to approved sources.', 'Flag stale instructions for the subject owner.'], watch: 'Do not invent policy, publish unverified advice, or remove required warnings.' },
  { slug: 'virtual-assistant-service-area-records', title: 'Service-area records for a virtual assistant to organize', excerpt: 'Maintain location requests and coverage notes without turning an administrative record into a service promise.', published: '2026-08-13', focus: 'service-area records', audience: 'local service businesses receiving work requests from several locations', firstSteps: ['Use the approved coverage list.', 'Separate a request from confirmed availability.', 'Route unusual addresses to the operator.'], watch: 'Do not guarantee coverage, quote travel terms, or make safety judgments.' },
  { slug: 'philippines-virtual-assistant-membership-welcome', title: 'Membership welcome administration from a Philippines virtual assistant', excerpt: 'Coordinate welcome messages, orientation details, and unanswered member questions while owners retain policy control.', published: '2026-08-13', focus: 'membership welcome administration', audience: 'membership communities welcoming new members', firstSteps: ['Record each sent welcome message.', 'Separate access from conduct and refund issues.', 'Give the owner an exception queue.'], watch: 'Do not grant special access, disclose member information, or decide disputes.' },
  { slug: 'philippines-virtual-assistant-webinar-coordination', title: 'Webinar coordination support from a Philippines virtual assistant', excerpt: 'Keep speaker details, attendee questions, reminders, and follow-up resources organized around an approved event plan.', published: '2026-08-13', focus: 'webinar coordination', audience: 'small teams hosting educational sessions', firstSteps: ['Maintain one event record with owners and deadlines.', 'Mark draft resources separately from approved materials.', 'Collect unanswered questions for the presenter.'], watch: 'Do not promise attendance, publish speaker material, or give expert advice.' },
  { slug: 'virtual-assistant-sales-asset-library', title: 'Sales-asset library upkeep for a virtual assistant', excerpt: 'Help sales teams find current approved material without creating unsupported claims.', published: '2026-08-13', focus: 'sales-asset library upkeep', audience: 'small sales teams sharing documents across conversations', firstSteps: ['Label assets by audience, owner, version, and review date.', 'Archive superseded files without deleting history.', 'Route new claims for commercial review.'], watch: 'Do not make performance promises, alter approved language, or send to unapproved recipients.' },
  { slug: 'philippines-virtual-assistant-support-queue-review', title: 'Support-queue review with a Philippines virtual assistant', excerpt: 'Surface aging tickets, missing owners, and repeat questions so qualified staff can focus on useful responses.', published: '2026-08-13', focus: 'support-queue review', audience: 'customer-service teams with busy shared inboxes', firstSteps: ['Define age, urgency, and owner fields.', 'Keep unanswered questions visible.', 'Summarize patterns without treating a count as a cause.'], watch: 'Do not close tickets, promise resolution, or classify safety issues.' },
  { slug: 'virtual-assistant-project-status-digest', title: 'Project-status digests a virtual assistant can prepare', excerpt: 'Turn approved updates into a compact view of milestones, decisions, blockers, and next owners.', published: '2026-08-13', focus: 'project-status digests', audience: 'small teams coordinating client work across contributors', firstSteps: ['Collect dated updates from named owners.', 'Distinguish risk from confirmed delay.', 'Separate decisions waiting on leadership.'], watch: 'Do not change milestones, hide risks, or present an estimate as a commitment.' },
  { slug: 'philippines-virtual-assistant-product-feedback-log', title: 'Product-feedback logs from a Philippines virtual assistant', excerpt: 'Organize customer observations into traceable themes while product owners decide what merits investigation.', published: '2026-08-13', focus: 'product-feedback logs', audience: 'small product teams collecting customer observations', firstSteps: ['Keep customer words distinct from summaries.', 'Tag source, date, area, and requested outcome.', 'Group only when context remains visible.'], watch: 'Do not promise features, infer consent, or generalize one comment.' },
  { slug: 'virtual-assistant-office-supply-reconciliation', title: 'Office-supply reconciliation a virtual assistant can organize', excerpt: 'Match approved orders, deliveries, and storage notes so teams can spot discrepancies early.', published: '2026-08-13', focus: 'office-supply reconciliation', audience: 'distributed teams coordinating physical supplies', firstSteps: ['Match deliveries to orders and recipients.', 'Separate missing confirmations from missing items.', 'Escalate substitutions with documentation.'], watch: 'Do not approve purchases, accuse suppliers, or alter records to make them balance.' },
  { slug: 'philippines-virtual-assistant-client-feedback-follow-up', title: 'Client-feedback follow-up from a Philippines virtual assistant', excerpt: 'Capture agreed next steps after feedback conversations while relationship and remedy decisions stay with the account owner.', published: '2026-08-13', focus: 'client-feedback follow-up', audience: 'agencies and consultants following up after review calls', firstSteps: ['Record what was said and what remains undecided.', 'Assign every action to an owner and date.', 'Keep dissatisfaction visible to the account lead.'], watch: 'Do not promise corrections, offer concessions, or characterize intent.' },
  { slug: 'virtual-assistant-compliance-document-chasing', title: 'Compliance-document follow-up a virtual assistant can support', excerpt: 'Track requested certificates and forms without claiming that receipt proves compliance.', published: '2026-08-13', focus: 'compliance-document follow-up', audience: 'small businesses collecting recurring records', firstSteps: ['List document, source, owner, version, and due date.', 'Mark received files ready for review, not approved.', 'Escalate missing or expired records.'], watch: 'Do not certify compliance, interpret regulations, or make risk decisions.' },
  { slug: 'philippines-virtual-assistant-digital-file-migration', title: 'Digital-file migration support from a Philippines virtual assistant', excerpt: 'Prepare a careful inventory and move plan while owners control deletion, access, and retention decisions.', published: '2026-08-13', focus: 'digital-file migration', audience: 'small teams reorganizing shared folders', firstSteps: ['Inventory paths, owners, types, and duplicates.', 'Map destinations and record exceptions.', 'Test permissions on a small sample.'], watch: 'Do not delete originals, broaden access, or discard records.' },
  { slug: 'virtual-assistant-recruiting-interview-scheduling', title: 'Interview scheduling support a virtual assistant can provide', excerpt: 'Coordinate candidate availability and interviewer calendars while hiring decisions stay with the hiring team.', published: '2026-08-13', focus: 'interview scheduling', audience: 'small employers arranging interviews across time zones', firstSteps: ['Use approved stages and preserve time zones.', 'Keep accommodation questions visible to hiring owners.', 'Send current role information.'], watch: 'Do not screen by unapproved criteria, promise employment, or overshare candidate details.' },
  { slug: 'philippines-virtual-assistant-appointment-waitlist', title: 'Appointment waitlist coordination from a Philippines virtual assistant', excerpt: 'Maintain waitlist requests and preferences without allowing reminders to become unauthorized scheduling decisions.', published: '2026-08-13', focus: 'appointment waitlist coordination', audience: 'service practices managing cancellations and limited appointment windows', firstSteps: ['Record requested service and acceptable times.', 'Separate an opening from a confirmed appointment.', 'Use current identity and cancellation rules.'], watch: 'Do not give professional advice, disclose unnecessary details, or promise an opening.' },
  { slug: 'virtual-assistant-community-directory-maintenance', title: 'Community-directory maintenance for a virtual assistant', excerpt: 'Keep directory details current through sourced updates and owner review for public changes.', published: '2026-08-13', focus: 'community-directory maintenance', audience: 'associations maintaining a shared directory', firstSteps: ['Record source and date for each change.', 'Flag conflicting names and roles.', 'Separate public fields from restricted information.'], watch: 'Do not publish profiles, expose private contacts, or infer affiliations.' },
  { slug: 'philippines-virtual-assistant-shift-handoff-notes', title: 'Shift-handoff notes from a Philippines virtual assistant', excerpt: 'Give the next support person a factual view of completed work, open questions, and promised follow-up.', published: '2026-08-13', focus: 'shift-handoff notes', audience: 'teams passing customer or administrative work across time zones', firstSteps: ['Use done, waiting, blocked, and urgent sections.', 'Link items to sources and owners.', 'State uncertainty plainly.'], watch: 'Do not invent progress, close exceptions, or transfer sensitive decisions.' },
  { slug: 'virtual-assistant-local-partner-research', title: 'Local-partner research a virtual assistant can organize', excerpt: 'Build a reviewable shortlist from public information while the owner decides fit and outreach.', published: '2026-08-13', focus: 'local-partner research', audience: 'small companies exploring referral relationships', firstSteps: ['Define geography, partner type, and evidence fields.', 'Save source links and separate facts from assumptions.', 'Return open questions with the shortlist.'], watch: 'Do not imply endorsement, collect restricted information, or contact businesses without authorization.' },
  { slug: 'philippines-virtual-assistant-customer-survey-admin', title: 'Customer-survey administration from a Philippines virtual assistant', excerpt: 'Organize survey invitations and responses while preserving consent and the limits of what feedback can show.', published: '2026-08-13', focus: 'customer-survey administration', audience: 'small businesses collecting structured service feedback', firstSteps: ['Use approved audience and invitation language.', 'Keep incomplete responses separate.', 'Show the sample when summarizing themes.'], watch: 'Do not alter responses, pressure customers, or present a small sample as universal evidence.' },
  { slug: 'virtual-assistant-service-record-archiving', title: 'Service-record archiving a virtual assistant can prepare', excerpt: 'Organize completed work records for retrieval while owners decide retention, access, and closure.', published: '2026-08-13', focus: 'service-record archiving', audience: 'small service teams whose completed work is hard to retrieve', firstSteps: ['Apply approved naming and status fields.', 'Link records to sources and closure reasons.', 'Flag missing approvals before moving files.'], watch: 'Do not delete history, change meaning, or widen access while archiving.' },
];

const makePost = (spec: AugustSpec, index: number): BlogPost => ({
  slug: spec.slug, title: spec.title, excerpt: spec.excerpt, minutes: 8 + (index % 5), updated: spec.published,
  takeaways: [`Define the finished output for ${spec.focus} before access is granted.`, 'Give the assistant examples, a source of truth, and a named person for exceptions.', 'Review early work for accuracy, tone, completeness, and safe escalation.'],
  sections: [
    { heading: 'Set the first assignment', body: `${spec.title} is easiest to delegate when ${spec.audience} starts with one visible work lane. ${spec.excerpt} Name the trigger, available information, finished output, and accepting owner.`, bullets: spec.firstSteps },
    { heading: 'Make the handoff specific', body: `For ${spec.focus}, give context without asking the assistant to infer policy. Show a completed example, identify the source of truth, and state what to do when a record is incomplete.` },
    { heading: 'Review the first real items', body: `Review early ${spec.focus} work for accuracy, completeness, tone, and escalation. When the same question appears twice, improve the handoff rather than expecting silent guesswork.` },
    { heading: 'Protect decisions and access', body: `${spec.watch} Use individual accounts where possible, enable multi-factor authentication, and give access only to the systems needed for this assignment.` },
  ],
  faqs: [
    { question: `What should the first ${spec.focus} assignment include?`, answer: 'Start with one repeatable output, a current example, the source of truth, and a named reviewer.' },
    { question: 'Who keeps the final decision?', answer: 'The business owner or authorized professional keeps sensitive commitments, exceptions, and final approvals.' },
  ],
  sources: [source, securitySource],
});

export const aug13BlogPosts: BlogPost[] = specs.map(makePost);
