import type { ResearchPost } from './data';

export const claimHandoffResearch: ResearchPost = {
  slug: 'claim-handoff-proof-for-philippines-va-research',
  title: 'Claim handoff proof for Philippines virtual assistant research',
  excerpt: 'What must an editor be able to verify before accepting a research handoff from a Philippines-based virtual assistant?',
  published: '2026-08-20',
  methodology: 'Research question: what must an editor be able to verify before accepting a research handoff from a Philippines-based virtual assistant? This study compares SBA guidance on expectations and management, NIST Cybersecurity Framework guidance on context and risk, and CISA Secure Our World guidance on clear protective action. The evidence scope is a defined sample of claim handoffs from one article lane. It tests whether a second reviewer can identify the question, exact supported wording, source location, date, unresolved gap, and owner decision. It distinguishes public-source fact from local observation and editorial analysis. It does not prove worker performance, source correctness beyond the checked sample, or a business outcome.',
  headlineStat: { value: '6', label: 'handoff fields in the proposed acceptance test', source: 'Local evidence design stated in the methodology' },
  keyStats: [{ value: '3', label: 'claim-relevant public sources' }, { value: '1', label: 'second-reviewer acceptance test' }, { value: '0', label: 'guaranteed article outcomes' }],
  takeaways: ['An accepted handoff lets another reviewer reconstruct the question and evidence without guessing.', 'A source link is not enough; the supported wording, date, limitation, and unresolved decision must travel with it.', 'The assistant prepares traceability while the owner keeps publication and sensitive interpretation.'],
  sections: [
    { heading: 'The handoff is an evidence object', body: 'A remote research handoff is often treated as a message containing links. That is too thin for a publication decision. SBA guidance connects management with clear expectations, which means a handoff should make the expected output visible. NIST’s framework uses context and risk functions, which supports preserving what information matters and what response remains open. CISA’s small-business guidance emphasizes practical protective actions and clear response thinking, which supports recording what was checked rather than relying on implied knowledge. These sources do not define a universal handoff form. The local question is what a second editor needs to verify before accepting a claim package prepared for an article about Philippines-based virtual assistant work. The unit is one claim package, not one worker or one article. A package can be accepted, corrected, held, escalated, or rejected. Its status should be visible. The handoff should also distinguish a missing input from a wrong conclusion. That distinction helps the editor fix the lane rather than assigning blame to the person who happened to receive an unclear brief.', table: [['Handoff field','Verification question'],['Question','What reader decision is this claim meant to support?'],['Exact wording','What sentence is being proposed?'],['Source location','Where does the source support it?'],['Date','What publication or access date matters?'],['Limitation','What does the evidence not establish?'],['Owner decision','What remains outside the assistant’s authority?']] },
    { heading: 'The second-reviewer test', body: 'Use a dated sample of handoffs and ask a reviewer who did not prepare the item to continue the work using only the handoff and permitted source links. The reviewer should identify the intended reader, the claim, the source passage, the evidence scope, the missing question, and the next decision. Record clarification requests rather than hiding them. A handoff that requires a short clarification may be close to ready, but the reason matters. Missing source location is an evidence problem. Missing owner availability is a coordination problem. An ambiguous reader is a brief problem. A disputed definition is a judgment problem. Include ordinary and exceptional handoffs, including those that were accepted quickly and those that were returned. Do not select only completed work. The test is not a score for writing style or speed. It is a test of whether the evidence can move between owners without reconstruction. The owner can then decide whether to add a field, narrow the claim, change the source standard, or stop the item. The sample should state its period and frame so its finding does not masquerade as a universal rate.', table: [['Test result','Next interpretation'],['Reproducible','The handoff carries enough context for this item'],['Clarification needed','Name the missing field and repair the lane'],['Source mismatch','Narrow, replace, or escalate the claim'],['Authority unclear','Stop until the owner decision is named']] },
    { heading: 'Evidence, interpretation, and uncertainty', body: 'A handoff becomes misleading when source findings and local interpretation are blended. A public framework may say that an organization should identify and manage risk. The local article analysis may infer that a team should name an owner for an access exception. That inference may be reasonable, but it is not a quotation from the framework. Label it as analysis. Similarly, a source may describe phishing protections while the local article proposes that a remote assistant pause a suspicious request. The proposal is a role boundary, not evidence that the control eliminates risk. Keep a claim ledger that shows source fact, proposed public wording, confidence or uncertainty, and the review decision. If a source is current but too broad, state the limitation. If local observation conflicts with general guidance, preserve both and route the conflict. An editor should be able to tell whether a sentence was accepted because the source supported it, because the owner accepted a bounded interpretation, or because it was removed. This history need not appear in public copy, but the public copy must still state meaningful limitations. Honest uncertainty is part of research quality.', table: [['Layer','Publicly responsible treatment'],['Source fact','Attribute and keep its scope'],['Local observation','Describe the sample and period'],['Editorial analysis','Label as interpretation or proposal'],['Uncertainty','State the unresolved boundary'],['Decision','Name the responsible owner']] },
    { heading: 'A clear boundary for the assistant and editor', body: 'A Philippines-based virtual assistant can search public sources, capture exact passages, compare claim wording, record access dates, and prepare an escalation note. The assistant should not approve a consequential claim merely because it has three URLs. Three sources can share a limitation or fail to answer the same question. The assistant should not decide that an employment, legal, financial, medical, privacy, security, or customer commitment is acceptable for publication. The editor or qualified reviewer owns those judgments. In a distributed team, the handoff should make stopping easy. It should say: here is the question, here is what I checked, here is what I can support, here is what I cannot support, and here is the decision needed. That language is useful to a reader because it produces a narrower article, not because it promises certainty. It is useful to a worker because the boundary is visible. If an editor changes the thesis, preserve the reason in the internal evidence record and do not quietly restore the earlier claim in a later draft. A routine stays reliable when decisions are observable rather than inferred from activity.', table: [['Assistant owns','Editor or qualified reviewer owns'],['Collection and source capture','Thesis and publication approval'],['Claim comparison','Consequential interpretation'],['Open-question note','Risk acceptance and exception authority'],['Handoff completeness','Final reader-facing commitment']] },
    { heading: 'Conclusion: accept traceability, not confidence', body: 'The evidence supports a second-reviewer acceptance test for remote research handoffs. The minimum useful record identifies the reader decision, exact claim, source location, date, evidence limit, and owner decision. A sample can reveal recurring missing fields and show where a lane needs repair, but it cannot prove that every future handoff is correct or that a worker will produce a particular result. For OverseasVirtualAssistant.com, the evidence-led conclusion is to accept a handoff only when another editor can continue without reconstructing the source trail and can see what remains unresolved. If the source supports less than the proposed sentence, narrow it. If the question belongs to the owner or a specialist, escalate it. If the context is missing, return the handoff for clarification. A clear acceptance boundary makes daily research more dependable while keeping authority with the person responsible for publication.', table: [['Conclusion test','Pass condition'],['Reconstructable','A second reviewer can continue from the handoff'],['Source-backed','Each material claim has relevant evidence'],['Bounded','Limitations and open questions are visible'],['Role-safe','Owner-only decisions remain with the owner']] }
  ],
  sourceNotes: 'Sources consulted: https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework; https://www.cisa.gov/secure-our-world. The acceptance test is a local editorial design, not a service or workforce claim.',
  sources: [{ name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'clear expectations and management' }, { name: 'National Institute of Standards and Technology: Cybersecurity Framework', url: 'https://www.nist.gov/cyberframework', note: 'context and risk-management functions' }, { name: 'Cybersecurity and Infrastructure Security Agency: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'practical protective and response guidance' }],
  internalLinks: ['/services/research-and-data-support','/research'],
  faqs: [{ question: 'Does a complete handoff prove the claim is true?', answer: 'No. It proves that the claim and evidence can be reviewed with its limits visible.' }, { question: 'What if the reviewer needs clarification?', answer: 'Record the missing field and repair the handoff or brief before publication.' }, { question: 'Who keeps final authority?', answer: 'The authorized editor or qualified reviewer.' }],
  relatedResearch: ['/research/handoff-reliability-in-distributed-teams','/research/research-brief-acceptance-criteria','/research'],
  image: { src: '/images/research-aug20/claim-handoff-proof-for-philippines-va-research.png', alt: 'Editorial illustration of claim handoff proof for Philippines virtual assistant research' },
  cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, and owner rules with our staffing team.'
};
