import type { ResearchPost } from './data';

const cta = 'Want this research translated into a clearly scoped staffing lane? Share the work, evidence, and approval boundaries with our staffing team.';
const sources = {
  sba: { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'clear expectations and management planning' },
  nist: { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'risk context and governance functions' },
  cisa: { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'authentication, updates, and phishing protection' },
  ilo: { name: 'International Labour Organization: Working time and work-life balance', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'working-time context for sustainable schedules' },
  ftc: { name: 'FTC: Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'data minimization and access discipline' },
  fdlp: { name: 'Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public-information provenance and access' },
};

type Spec = Omit<ResearchPost, 'internalLinks' | 'cta' | 'image'> & { imageSlug: string; imageAlt: string };
const make = (s: Spec): ResearchPost => ({ ...s, internalLinks: ['/services/research-and-data-support', '/research'], cta, image: { src: `/images/research-aug23/${s.imageSlug}.png`, alt: s.imageAlt } });

export const aug23ResearchPosts: ResearchPost[] = [
  make({
    slug: 'how-to-measure-research-handoff-completeness', published: '2026-08-23', imageSlug: 'research-handoff-completeness', imageAlt: 'Researcher checking a complete evidence handoff between a business owner and a remote assistant',
    title: 'How can a business measure research-handoff completeness before a virtual assistant drafts?',
    excerpt: 'A bounded study of the evidence fields that make a daily article research handoff usable for a Philippines-based virtual assistant and its reviewer.',
    methodology: 'Research question: which observable fields make a research handoff complete enough for a Philippines-based virtual assistant to begin a daily article draft? This study compares management guidance from the SBA, risk-context guidance from NIST, and public-information provenance guidance from the FDLP. The unit is one proposed claim handoff, not one worker, article, or business. The evidence scope covers question, audience, source, interpretation boundary, status, and escalation fields. It does not measure writing quality, search performance, or a staffing outcome. Facts from the sources are separated from the operating analysis below.',
    headlineStat: { value: '6', label: 'handoff fields examined', source: 'Defined claim-handoff model' },
    keyStats: [{ value: '3', label: 'public sources consulted' }, { value: '1', label: 'claim used as the review unit' }, { value: '0', label: 'performance outcomes inferred' }],
    takeaways: ['Completeness means a reviewer can make the next decision without reconstructing the request.', 'A source URL is necessary but does not explain how far a claim may travel.', 'The assistant prepares missing-field questions; the owner retains publication and interpretation decisions.'],
    sections: [
      { heading: 'Completeness is a decision test', body: 'A research handoff is often called complete when a document contains a topic, several links, and a suggested outline. That definition is too thin for daily article work. A Philippines-based virtual assistant may find a credible source yet still lack the audience, date boundary, claim scope, or approval owner needed to use it safely. The SBA describes management as a practice of setting expectations and managing work, which supports treating the handoff as an operational interface. Its purpose is not to make the assistant guess more confidently; it is to let the next person decide whether to research, draft, clarify, or stop. A complete record therefore answers six questions: what question is being answered, who needs the answer, which claim is supported, where the source is, what the evidence does not establish, and who resolves a material uncertainty. The fields are small, but they prevent a large amount of hidden reconstruction.', table: [['Field','Completion question'],['Question','Can the researcher state the decision the article serves?'],['Audience','Is the intended reader and use explicit?'],['Claim','Is the proposed sentence bounded?'],['Source','Can a reviewer reach the cited evidence?'],['Limit','Is the unsupported inference named?'],['Owner','Is the escalation decision assigned?']] },
      { heading: 'What the evidence supports', body: 'The FDLP provides a useful provenance lens: public information is more useful when readers can identify and access the underlying material. That does not prescribe this company’s editorial form, but it supports recording a stable URL, source name, relevant date, and a short note about what the source contributes. NIST’s framework similarly emphasizes context and risk rather than a universal control list. Applied to article research, a source note should say whether it supplies a fact, a definition, a process principle, or background context. The distinction matters because a government page about security practice may support a recommendation to examine access, but it does not prove that a particular virtual assistant team experienced a breach or achieved a result. The handoff should carry the source’s role and the writer’s proposed interpretation separately. This makes the reviewer’s task an inspectable decision instead of a hunt through a pile of URLs.', table: [['Evidence item','What it can establish'],['Stable source','Where a reviewer can inspect the material'],['Quoted concept in own words','Which idea the source contributes'],['Scope note','Which audience, date, or jurisdiction applies'],['Analysis label','What the local article recommendation adds'],['Limitation','What the source cannot establish']] },
      { heading: 'A practical review for remote article support', body: 'The assistant can complete the first pass: identify the question, classify each source, draft a claim in plain language, and flag missing context. The reviewer should then test the record in a fixed order. First, ask whether the question is narrow enough to answer. Second, check that every important public statement has a source that actually supports it. Third, separate source fact from local analysis. Fourth, confirm that the proposed reader action does not become a promise about the company, a worker, or a result. Fifth, decide whether the item is ready, needs clarification, or must be escalated. This is especially useful when the article concerns overseas staffing. Geography can make the decision concrete, but it cannot justify assumptions about an individual assistant’s skills, schedule, or legal status. The company’s staffing team can explain a role lane; the owner still approves sensitive claims and final publication.', table: [['Review outcome','Next action'],['Ready','Release the bounded handoff to drafting'],['Clarify','Return named questions before drafting'],['Escalate','Send privacy, legal, security, or commitment issues to owner'],['Reject','Record why the source or angle cannot support publication']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'This model is a proposed operating analysis, not a validated completeness score. Six fields may be enough for one daily article lane and insufficient for a regulated or technically complex topic. The sources do not establish that a complete handoff improves rankings, revenue, turnaround time, or worker performance. A local review can also miss information held in conversation, restricted systems, or an owner’s memory. Those limitations should remain visible. The evidence supports a narrower conclusion: measure handoff completeness by whether an authorized reviewer can make the next research or approval decision from the record, without guessing about audience, source scope, or boundaries. For OverseasVirtualAssistant.com, the most useful role for a Philippines-based virtual assistant is to prepare this traceable record and stop at the stated boundary. The owner decides whether the evidence is sufficient for a public article.', table: [['Conclusion test','Pass condition'],['Traceability','Each central claim points to a source and scope note'],['Usability','Reviewer can choose ready, clarify, escalate, or reject'],['Niche relevance','Examples concern daily article support and remote staffing'],['Honesty','No worker, market, or business result is inferred']] },
    ],
    sourceNotes: 'Sources consulted: https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework; https://www.fdlp.gov/. They inform expectations, context, and provenance; the six-field model is local editorial analysis.',
    sources: [sources.sba, sources.nist, sources.fdlp], faqs: [{ question: 'Is a source URL enough to complete a handoff?', answer: 'No. The record also needs the question, audience, claim boundary, limitation, and owner for escalation.' }, { question: 'Can the assistant approve the article?', answer: 'The assistant can prepare evidence and flag gaps; an authorized owner or editor retains final publication decisions.' }], relatedResearch: ['/research/sample-frame-design-for-virtual-assistant-research', '/research/reviewer-disagreement-in-virtual-assistant-research'],
  }),
  make({
    slug: 'what-source-diversity-means-for-daily-va-research', published: '2026-08-23', imageSlug: 'source-diversity-daily-research', imageAlt: 'Distinct source paths converging on a carefully bounded daily research question for remote article support',
    title: 'What does source diversity actually add to daily research by a virtual assistant?',
    excerpt: 'An evidence-scope study of independent source roles for articles about overseas virtual assistant work, without turning link counts into proof.',
    methodology: 'Research question: what can source diversity add to a daily article researched by a Philippines-based virtual assistant? The method compares CISA security guidance, NIST risk context, and FDLP provenance guidance, then models source roles at claim level. The unit is one article claim and its evidence path. The study distinguishes independent authority, repeated reporting, and contextual background. It does not calculate a universal source-quality score, estimate market conditions, or prove that more links improve an article. Facts from the sources are separated from the analysis.',
    headlineStat: { value: '3', label: 'source roles compared', source: 'Authority, context, and corroboration model' },
    keyStats: [{ value: '3', label: 'public sources consulted' }, { value: '1', label: 'claim-level unit' }, { value: '0', label: 'link-count quality scores' }],
    takeaways: ['Different sources help only when they contribute different evidence or scope.', 'Three links repeating one assertion are not three independent confirmations.', 'A virtual assistant can map source roles while the editor decides whether the claim is publishable.'],
    sections: [
      { heading: 'Diversity is about roles, not decoration', body: 'Daily article routines often reward a visible list of references. That can create a false signal: an article with eight links may still depend on one unexamined assertion. Source diversity is more useful when the researcher can explain why each source is present. One source may define a risk, another may describe a control, and a third may supply public-document context. CISA’s guidance on practical security behavior and NIST’s framework do not say the same thing, even where they address related concerns. The difference lets an article distinguish a user action from a governance question. For an OverseasVirtualAssistant.com article, this can keep a staffing recommendation from pretending to be a cybersecurity finding. The assistant should record each source’s role beside the claim rather than adding links at the end of a draft. The reviewer then sees whether the evidence is complementary, duplicative, or irrelevant.', table: [['Source role','Question it answers'],['Definition','What does the topic mean?'],['Practice','What behavior or control is recommended?'],['Context','Which audience or risk setting applies?'],['Corroboration','Does an independent authority support the same bounded fact?'],['Limit','Where does the evidence stop?']] },
      { heading: 'Independence needs a careful definition', body: 'Two pages can look different while repeating the same press release, statistic, or institutional claim. Conversely, two public authorities may address one concept from genuinely different responsibilities. The researcher should therefore trace the relationship when it matters. FDLP guidance supports the practical value of identifiable public documents, but it does not make every government page independent evidence for every editorial statement. A source map can label direct authority, secondary summary, and local analysis. If three pages merely restate one original document, they are useful for access or explanation but should not be presented as three confirmations. This is a methodological boundary, not a reason to avoid secondary sources. A Philippines-based virtual assistant can find the primary material, note the chain, and ask whether a secondary source adds reader context. The editor decides how the chain appears publicly.', table: [['Relationship','Editorial treatment'],['Independent authority','May corroborate a bounded fact'],['Secondary summary','Use for context; trace primary source when material'],['Same-origin repetition','Do not count as independent confirmation'],['Local analysis','Label as analysis, not sourced fact'],['Conflict','Narrow the claim or escalate for review']] },
      { heading: 'How to use a source map in a staffing lane', body: 'A source map should be small enough to use every day. For each central claim, record the sentence, source role, URL, access date, relevant scope, and unresolved question. The assistant can prepare this map and group claims that share an authority. They can also flag when a source concerns general security, working time, or public information while the draft makes a claim about a specific assistant or business. That jump is where many apparently well-referenced articles become unsupported. The owner can then choose among three responses: keep the general statement, add a clearly labeled operating inference, or remove the claim. This division preserves useful delegation. The assistant performs retrieval and comparison; the authorized editor controls the public meaning and any company-specific assertion. A source-diversity check should slow a draft when it reveals a boundary, not pressure the researcher to find a fourth link.', table: [['Map field','Why it matters'],['Claim text','Keeps review at sentence level'],['Source role','Shows what the URL contributes'],['Origin chain','Avoids counting repetition as independence'],['Scope','Prevents geography or audience drift'],['Decision','Makes keep, narrow, or remove explicit']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'No source map can remove judgment from research. Authorities may disagree, pages may change, and a narrow staffing question may have no source that addresses the exact operating situation. The three sources used here do not establish a best number of references, a country-specific labor conclusion, or a business outcome. Source diversity can also become performative if the article includes unrelated authorities merely to look rigorous. The evidence supports a bounded conclusion: diversity adds value when distinct sources contribute distinct roles, their origin and scope are visible, and the final claim remains no broader than the evidence. For a daily research routine, a Philippines-based virtual assistant is well placed to build the map and expose repetition or gaps. An owner or editor must decide whether the evidence supports the article’s public conclusion.', table: [['Evidence-led close','Boundary'],['Different roles','Do not confuse topical variety with proof'],['Independent paths','Trace repeated source chains'],['Claim discipline','Keep geography and certainty within evidence'],['Escalation','Refer conflict or sensitive interpretation to owner']] },
    ],
    sourceNotes: 'Sources consulted: https://www.cisa.gov/secure-our-world; https://www.nist.gov/cyberframework; https://www.fdlp.gov/. They inform control, context, and provenance distinctions; the source-map method is editorial analysis.',
    sources: [sources.cisa, sources.nist, sources.fdlp], faqs: [{ question: 'Does adding more links make research stronger?', answer: 'Only when the links add relevant, independent evidence or useful context.' }, { question: 'Who checks whether sources are independent?', answer: 'The assistant can trace and label the relationships; an authorized editor decides the final evidence treatment.' }], relatedResearch: ['/research/evidence-age-in-daily-article-research', '/research/source-independence-in-virtual-assistant-research'],
  }),
  make({
    slug: 'when-to-escalate-uncertain-claims-in-va-article-research', published: '2026-08-23', imageSlug: 'uncertain-claim-escalation', imageAlt: 'Remote research handoff pausing an uncertain article claim for owner review',
    title: 'When should a virtual assistant escalate an uncertain claim in article research?',
    excerpt: 'A risk-bounded escalation study for Philippines-based virtual assistants preparing daily research, with separate paths for missing evidence, sensitive meaning, and ordinary uncertainty.',
    methodology: 'Research question: when should a Philippines-based virtual assistant stop researching and escalate an uncertain claim? The method compares NIST risk governance, FTC data-protection guidance, and SBA management guidance with a proposed claim triage. The unit is one public sentence or recommendation. The scope covers uncertainty about source support, privacy, security, legal meaning, and company commitments; it does not give legal advice or measure assistant performance. Facts and operating analysis are separated.',
    headlineStat: { value: '5', label: 'escalation triggers separated', source: 'Claim-risk triage model' },
    keyStats: [{ value: '3', label: 'public sources consulted' }, { value: '1', label: 'sentence used as unit' }, { value: '0', label: 'legal or compliance conclusions offered' }],
    takeaways: ['Escalation is a work control, not a failure state.', 'The assistant should identify the uncertainty and its possible consequence, not silently resolve it.', 'Owners need a consistent response path so pauses do not become hidden delays.'],
    sections: [
      { heading: 'Uncertainty becomes material at the boundary', body: 'Every research task contains ordinary uncertainty: a page may be hard to read, a term may have multiple meanings, or the source may answer a neighboring question. Not every uncertainty deserves an owner interruption. The useful distinction is consequence. If choosing one interpretation could change a privacy statement, security instruction, legal implication, financial expectation, or promise about the company, the assistant should pause. NIST’s framework places risk work in organizational context, while the FTC emphasizes practical controls such as limiting access and protecting information. Neither source provides a bespoke escalation rule for this company; together they support the principle that uncertainty matters when the downside is material and the researcher lacks authority to choose. The assistant’s job is to make the uncertainty legible: show the sentence, evidence, competing readings, and suggested question.', table: [['Trigger','Pause because'],['Unsupported scope','The source does not reach the proposed claim'],['Privacy exposure','The draft may reveal or infer personal information'],['Security meaning','A wrong instruction could increase risk'],['Legal or financial meaning','A specialist or owner may need to decide'],['Company commitment','The sentence could promise a result, rate, or service level']] },
      { heading: 'A triage record keeps escalation useful', body: 'An escalation should not say only “please review.” It should contain the exact claim, source URL, what the source establishes, what the draft adds, why the difference matters, and the decision needed. The assistant can also offer bounded alternatives, such as replacing a universal statement with “this source recommends,” or removing a company-specific implication. FTC guidance makes data minimization a practical concern, which means the escalation record itself should avoid copying unnecessary personal or confidential material. The owner can then choose to approve a narrowed sentence, request more evidence, route the issue to a qualified adviser, or remove the claim. The record should not be used to make the assistant responsible for legal judgment. It is a routing instrument that protects both the writer and the publication.', table: [['Record element','Example purpose'],['Exact sentence','Prevents vague review'],['Evidence boundary','Shows the source’s actual reach'],['Consequence','Explains why a wrong choice matters'],['Safe alternative','Lets the owner narrow without starting over'],['Decision owner','Routes the question to the right authority']] },
      { heading: 'Designing the remote handoff', body: 'For daily article support, the routine can define three lanes. The assistant may resolve low-risk retrieval issues by finding a better version of the same authority and documenting the change. They should ask the editorial owner about audience, angle, or ordinary wording ambiguity. They must escalate material questions involving privacy, security, legal meaning, financial claims, or a company commitment. That boundary is especially important when the article discusses overseas virtual assistant work. The assistant can describe a role, task, or review practice based on evidence. They should not invent a worker’s credentials, guarantee availability, state an employment outcome, or make a country-wide claim from a narrow source. The owner’s response should be recorded as an instruction or approved wording so the same uncertainty does not return in the next article.', table: [['Lane','Assistant action'],['Resolve','Replace an inaccessible source with an equivalent authoritative version'],['Ask','Return a bounded question about scope or reader intent'],['Escalate','Pause material risk and name the required owner decision'],['Learn','Add the approved resolution to future examples']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'This triage model does not determine whether a statement is legally compliant, technically secure, or suitable for every business. The sources are public guidance, not advice about a particular company’s systems or worker relationship. A low-risk label can also be wrong if context is missing, and an owner may prefer a conservative pause. The evidence supports a clear conclusion: escalation is warranted when the assistant cannot support a public claim without choosing a material interpretation outside the assigned role. A strong daily routine makes that pause specific, minimal, and easy to answer. For OverseasVirtualAssistant.com, a Philippines-based virtual assistant can improve article reliability by surfacing the boundary early. The authorized owner, editor, or qualified adviser decides the sensitive question; the researcher preserves the evidence trail.', table: [['Conclusion test','Pass condition'],['Specificity','The claim and decision needed are explicit'],['Proportionality','Only material uncertainty interrupts the lane'],['Boundary','No assistant-made legal, security, or company promise'],['Follow-through','Approved resolutions become reusable guidance']] },
    ],
    sourceNotes: 'Sources consulted: https://www.nist.gov/cyberframework; https://www.ftc.gov/business-guidance/resources/start-security-guide-business; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees. They inform risk, data, and role boundaries; the escalation triage is editorial analysis.',
    sources: [sources.nist, sources.ftc, sources.sba], faqs: [{ question: 'Is asking for review a sign of poor performance?', answer: 'No. A well-defined escalation can be the correct control when a claim crosses the assistant’s authority.' }, { question: 'What belongs in an escalation?', answer: 'The exact claim, evidence boundary, possible consequence, safe alternative, and named decision owner.' }], relatedResearch: ['/research/reviewer-disagreement-in-virtual-assistant-research', '/research/privacy-boundaries-in-virtual-assistant-research-notes'],
  }),
  make({
    slug: 'how-working-time-context-changes-daily-article-research', published: '2026-08-23', imageSlug: 'working-time-context-research', imageAlt: 'Remote editorial team comparing working-time context before planning a daily article handoff',
    title: 'How should working-time context change daily article research for a remote assistant?',
    excerpt: 'A bounded study of schedule context, handoff timing, and evidence limits for teams using Philippines-based virtual assistant support.',
    methodology: 'Research question: how should working-time context affect a daily article research handoff involving a Philippines-based virtual assistant? The method compares ILO working-time research, SBA management guidance, and NIST context-based risk guidance. The unit is one handoff window and its required response, not an employee or country workforce. The scope covers overlap, asynchronous review, fatigue-sensitive planning, and exception timing. It does not provide labor-law advice, infer productivity, or recommend a universal schedule.',
    headlineStat: { value: '4', label: 'timing factors examined', source: 'Overlap, latency, fatigue, and escalation context' },
    keyStats: [{ value: '3', label: 'public sources consulted' }, { value: '1', label: 'handoff window as unit' }, { value: '0', label: 'universal schedule claims' }],
    takeaways: ['A date or time stamp does not explain whether a reviewer was available to act.', 'Asynchronous work needs explicit response windows and stop rules.', 'Schedule design should respect people and applicable requirements rather than treating time zones as a productivity shortcut.'],
    sections: [
      { heading: 'Time is part of research context', body: 'A daily article routine can appear punctual while still being operationally unclear. A brief sent at the end of one person’s shift may wait until the next overlap window; a source question may be answered after the intended publication slot; an urgent correction may arrive when the assigned researcher is offline. ILO research on working time and work-life balance provides context for considering schedule sustainability, while the SBA supports explicit expectations and management practices. These sources do not tell this company which hours to choose. They do support treating time as part of the handoff design. A useful record says when the task opens, when a response is needed, what can proceed asynchronously, and what must wait. That lets a Philippines-based virtual assistant prepare research without being pushed to guess when the owner is unavailable.', table: [['Timing factor','Question for the brief'],['Overlap','When can a live clarification happen?'],['Latency','How long may a non-urgent question wait?'],['Fatigue','Which work should not depend on extended hours?'],['Escalation','Who receives a material issue outside overlap?']] },
      { heading: 'Separate schedule fact from schedule inference', body: 'The research routine should avoid turning a published working-time principle into a claim about a particular assistant. A source may discuss rest, working hours, or balance in general. It does not establish that a person is available at a named hour, that a night shift is safe for them, or that a schedule will improve output. The article can make a narrower analysis: if a workflow depends on rapid clarification, it needs overlap or a delegated decision rule; if it can tolerate delay, it needs a clear asynchronous queue. NIST’s emphasis on context is useful here because a risk decision depends on the activity, information, and consequence. A source request about a public definition may wait. A question about an exposed account or sensitive correction may need a faster route. The assistant records the timing constraint; the owner chooses the operating response.', table: [['Statement type','Allowed treatment'],['Source fact','Attribute to the cited authority and scope'],['Local observation','Label as a record from this workflow'],['Operating analysis','Explain as a proposed design, not a measured result'],['Personal or legal claim','Escalate; do not infer from schedule data']] },
      { heading: 'A schedule-aware article handoff', body: 'A practical handoff has a due date, a preferred overlap window, an asynchronous fallback, and a stop rule. The assistant can gather sources, draft a methods note, and list open questions without waiting for every minor clarification. The editor can answer the questions in a queue and mark which decisions are safe to apply. If the item is time-sensitive, the brief should identify the actual owner rather than assume that online presence equals authority. A handoff also benefits from a “next available action” field: continue research, draft with a stated limitation, hold for approval, or escalate. This reduces the temptation to fill a quiet period with unsupported language. For a distributed staffing lane, respect for schedule boundaries is not separate from quality; it determines which evidence and approvals can realistically arrive before publication.', table: [['Handoff field','Why it prevents rework'],['Open time','Shows when work became active'],['Response window','Sets a realistic expectation'],['Fallback','Defines safe progress without live access'],['Stop rule','Prevents guessing under time pressure'],['Next action','Makes the queue usable across shifts']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'The three sources do not measure the schedule, workload, health, or output of any individual or team. Time-zone arithmetic cannot establish a fair schedule, and a delayed response may reflect an approval boundary rather than low capacity. Local law, contracts, and personal circumstances may impose requirements that this article does not address. The evidence supports a bounded conclusion: working-time context should change how a research handoff specifies overlap, latency, fallback actions, and escalation, but it should not be used to infer character, availability, or performance. For OverseasVirtualAssistant.com, a Philippines-based virtual assistant can make timing visible in the research record and prepare work asynchronously within the agreed lane. The owner remains responsible for schedule decisions, approvals, and any specialist advice required.', table: [['Evidence-led close','Boundary'],['Make timing visible','Do not treat timestamps as availability proof'],['Design fallbacks','Do not make the researcher invent authority'],['Respect limits','No legal or personal inference from general sources'],['Review reality','Adjust the lane from observed workflow evidence']] },
    ],
    sourceNotes: 'Sources consulted: https://www.ilo.org/publications/working-time-and-work-life-balance-around-world; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework. They inform working-time, expectation, and context principles; the handoff design is analysis.',
    sources: [sources.ilo, sources.sba, sources.nist], faqs: [{ question: 'Does a time-zone difference require live overlap?', answer: 'Only when the decision or risk requires rapid clarification; other work can use a documented asynchronous fallback.' }, { question: 'Can a timestamp prove an assistant was available?', answer: 'No. It records an event, not a person’s availability, workload, or performance.' }], relatedResearch: ['/research/handoff-context-loss-in-daily-virtual-assistant-research', '/research/evidence-age-in-daily-article-research'],
  }),
  make({
    slug: 'what-a-research-revision-log-can-and-cannot-prove', published: '2026-08-23', imageSlug: 'research-revision-log-evidence', imageAlt: 'Editor and remote assistant examining a revision log that separates source changes from editorial decisions',
    title: 'What can a research revision log prove about a virtual assistant article?',
    excerpt: 'A claim-level study of revision records for daily articles, distinguishing traceable change history from unsupported conclusions about people or outcomes.',
    methodology: 'Research question: what can a revision log establish when a Philippines-based virtual assistant helps prepare a daily research article? The method compares SBA expectations, NIST governance context, and FTC security guidance with a proposed claim-level log. The unit is one changed claim or evidence field. The scope covers reason, source, reviewer decision, and final wording. It does not measure worker quality, causation, legal compliance, or business results. Facts from the sources are distinguished from local analysis.',
    headlineStat: { value: '4', label: 'revision facts separated', source: 'Before, change, reason, and approval model' },
    keyStats: [{ value: '3', label: 'public sources consulted' }, { value: '1', label: 'claim-level revision unit' }, { value: '0', label: 'causal outcomes inferred' }],
    takeaways: ['A log can show what changed and who approved it; it cannot explain every cause.', 'Revision reasons should distinguish evidence correction from preference or scope change.', 'A clean history protects the article’s meaning without turning editing into surveillance of a worker.'],
    sections: [
      { heading: 'A log is evidence of sequence', body: 'A revision log is valuable because a daily article changes while it is being researched, drafted, reviewed, and approved. Without a record, a team may remember that a sentence was “fixed” but not whether the source changed, the claim narrowed, or an editor preferred different wording. The SBA’s emphasis on clear expectations supports naming the work and decision being managed. NIST’s governance perspective supports keeping context around a control rather than treating an isolated event as the whole story. A useful log records the original claim, changed claim, reason, supporting source, reviewer, and approval state. That establishes a sequence of editorial events. It does not establish why a person made an error, whether the first wording was careless, or whether the final article caused a business result. Those are different questions requiring different evidence.', table: [['Log field','What it can show'],['Before text','The wording under review'],['After text','The approved or proposed change'],['Reason','The stated basis for the change'],['Source state','Whether evidence was added, removed, or updated'],['Approval','Who accepted the public wording']] },
      { heading: 'Revision reasons need separate lanes', body: 'A single label such as “quality improvement” hides useful distinctions. One change may correct a factual mismatch between a claim and its source. Another may narrow an overbroad statement. A third may adjust tone for the intended reader without changing the evidence. A fourth may respond to a new source date or changed public guidance. The assistant can propose the label and attach the relevant source note; the editor decides the final classification. FTC guidance on security encourages attention to practical controls and information handling. Applied to an editorial log, that means minimizing sensitive material and keeping access appropriate to the task. The log should not become a place to copy private correspondence or personal assessments. It should preserve the smallest evidence needed to understand the public change. This makes the record useful for future research while respecting role boundaries.', table: [['Reason lane','Review question'],['Evidence correction','Does the source support the revised claim?'],['Scope narrowing','What inference was removed?'],['Reader clarity','Did public meaning change?'],['Source update','What changed in the authority?'],['Owner preference','Is the choice clearly distinguished from fact correction?']] },
      { heading: 'Using the log to improve a daily routine', body: 'A virtual assistant can maintain the first record: link the claim to the source, note the reviewer’s question, and enter the proposed change. The owner or editor approves sensitive wording and decides whether an instruction should change. At the end of a batch, the team can sample logs for recurring categories. If many edits narrow claims, briefs may be too broad. If many edits replace inaccessible sources, the source plan needs improvement. If many edits concern formatting, the template may be unclear. These are workflow hypotheses, not proof of a person’s performance. A revision log can support a coaching conversation when it is paired with examples and a clear expectation, but it should not be used to rank workers from a small or selective sample. The same record should also preserve approved examples so the next article starts with better context.', table: [['Pattern','Possible process question'],['Repeated scope narrowing','Should the brief define the reader decision earlier?'],['Repeated source mismatch','Is the claim-to-source check clear?'],['Repeated format edit','Does the template show an approved example?'],['Repeated owner preference','Should style guidance be documented?'],['Sensitive material','Is access and retention still appropriate?']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'A revision log reflects what the team chose to record. It can omit informal conversations, unlogged source changes, or reasons that were never written down. A high edit count may mean a careful review, a weak brief, a complex topic, or a changing source; it does not identify a cause on its own. The sources used here do not validate a scoring system or prove that logging improves article performance. The evidence supports a narrower conclusion: a claim-level revision log can establish the sequence, stated reason, evidence state, and approval boundary of an editorial change. It cannot prove a worker’s character, a causal business outcome, or legal compliance. For OverseasVirtualAssistant.com, a Philippines-based virtual assistant can maintain the traceable record while an authorized editor decides meaning, privacy, and publication. The log is strongest when it improves the next handoff rather than merely documenting the last correction.', table: [['Conclusion test','Pass condition'],['Minimality','Only needed editorial evidence is retained'],['Traceability','Changed claims connect to source and reason'],['Role clarity','Preparation and approval remain separate'],['Honest inference','No performance or outcome claim from edits alone']] },
    ],
    sourceNotes: 'Sources consulted: https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework; https://www.ftc.gov/business-guidance/resources/start-security-guide-business. They inform expectations, governance, and minimization; the revision-log model is editorial analysis.',
    sources: [sources.sba, sources.nist, sources.ftc], faqs: [{ question: 'Can revision count measure article quality?', answer: 'No. It is context-dependent evidence about changes, not a standalone quality or worker-performance measure.' }, { question: 'What should a revision log retain?', answer: 'The smallest useful record: before and after claim, reason, source state, reviewer, and approval.' }], relatedResearch: ['/research/reviewer-disagreement-in-virtual-assistant-research', '/research/claim-evidence-matrices-for-research-articles'],
  }),
];
