import type { ResearchPost } from './data';

export const articleIdentityResearch: ResearchPost = {
  slug: 'article-identity-decisions-for-virtual-assistant-research',
  title: 'Article identity decisions for virtual assistant research libraries',
  excerpt: 'How should an editor decide whether a new virtual assistant research question deserves a new article identity?',
  published: '2026-08-20',
  methodology: 'Research question: how should an editor decide whether a new virtual assistant research question deserves a new article identity? This study compares Google Search Central guidance on consolidating duplicate URLs, the FDLP route to authoritative information, and NIST Cybersecurity Framework concepts for understanding context and risk. The evidence scope is a proposed review of a new brief against existing Research and Blog records: title, reader decision, thesis, evidence scope, examples, date, and internal-link role. It distinguishes a genuinely new question from a changed fact within an existing question. The sources inform identity and evidence discipline; they do not measure search performance, reader preference, or business results.',
  headlineStat: { value: '1', label: 'article-identity decision examined in this research', source: 'Explicit route-scope question' },
  keyStats: [{ value: '3', label: 'claim-relevant public sources' }, { value: '6', label: 'identity fields to compare' }, { value: '0', label: 'search-performance claims' }],
  takeaways: ['A new route is justified by a distinct reader decision and evidence scope, not by changing nouns in an old title.', 'An update belongs to the existing identity when the reader question remains the same and the evidence change is traceable.', 'The editor should preserve publication history and keep route choice separate from search or conversion promises.'],
  sections: [
    { heading: 'Why identity is a research question', body: 'A research library serves readers through the questions it separates and connects. A new title alone does not prove a new article is needed. Google Search Central discusses consolidating duplicate URLs, which supports avoiding multiple locations that represent the same content decision; it does not determine the editorial thesis for this site. The FDLP supports access to authoritative public information, which helps an editor compare evidence provenance; it does not say whether two article questions are the same. NIST frameworks emphasize context and risk, which supports comparing the actual decision and conditions rather than keywords alone. For a site about Philippines-based virtual assistant staffing, identity should follow the reader’s operating question: role boundaries, research handoffs, access, schedules, quality evidence, or another distinct choice. The unit is one proposed brief compared with the existing library. The result can be new article, update, redirect or merge review, return for clarification, or reject. The owner should not use a new route to conceal a changed thesis, and should not overwrite an existing article merely because a new brief is easier to write.', table: [['Identity field','Comparison question'],['Reader decision','Is the choice the reader must make different?'],['Thesis','Does the article answer a different why or how?'],['Evidence scope','Would different sources or methods be required?'],['Treatment','Are examples and reasoning materially distinct?'],['Family','Is this Research rather than a practical Blog guide?'],['History','Can the old record remain truthful and findable?']] },
    { heading: 'A route-review method', body: 'Start with a dated brief and build a comparison set from existing Research and Blog records. Search for conceptual overlap, not just identical words. Read the title, excerpt, methodology, section headings, examples, conclusion, and sources of the nearest records. State the proposed reader decision in one sentence. Then state the closest existing decision in one sentence. If the two decisions differ, identify the evidence and examples needed for the new one. If they are the same, identify what has changed: a date-sensitive fact, source version, product condition, or limitation. That change may justify an update, but it should not erase the earlier publication context. Record the route decision and reason before drafting. A small comparison table is more useful than a vague similarity score because it shows where the overlap lives. The editor should also check internal-link purpose. Two articles may mention the same service while serving different decisions; two articles with different titles may compete for the same question. The result must be an editorial decision, not a claim that a route will rank or convert.', table: [['Review step','Evidence to record'],['Nearest records','Routes and family of each comparison'],['Decision sentence','Reader choice in the proposed brief'],['Thesis comparison','What is materially different or unchanged'],['Source comparison','Why the evidence set changes or remains'],['Route reason','New, update, clarify, or reject'],['Link role','How the article helps the library without duplication']] },
    { heading: 'New question versus changed evidence', body: 'A new article and an update solve different problems. A new article addresses a reader question that the existing record does not answer without changing its thesis. It may require a new method, a different evidence scope, new examples, and a separate conclusion. An update keeps the reader question but corrects or refreshes the evidence, clarifies a limitation, or adds a material condition. The distinction matters for a daily routine because repeated drafts can blur the library’s history. If an old article says how to evaluate access and a new brief asks how to test a continuity handoff, both may mention permissions but their decisions and evidence units differ. If the old article asks about a current rule and the rule changes, update the same question with a dated change note rather than creating a duplicate identity. The source review should state what changed and why the existing route remains the honest home. If the evidence reveals that the old thesis was too broad, an owner may narrow it, but the correction should be deliberate and traceable. Do not treat a route change as a substitute for editorial judgment.', table: [['Finding','Likely identity decision'],['Different reader choice','Create a new Research route'],['Same choice, changed fact','Update the existing route'],['Unclear question','Return the brief for clarification'],['Same treatment, new noun','Reject as duplicate framing'],['Sensitive or disputed scope','Escalate before route assignment']] },
    { heading: 'Keeping Research separate from Blog', body: 'A Research article should answer a genuine question with a stated methodology, evidence analysis, limitations, and conclusion. A Blog guide can explain a practical routine or checklist. The two families may link to each other, but a Research route should not be created by adding citations to an existing Blog body. Compare the proposed structure, not just the topic. A Blog article may tell a business how to prepare a handoff; Research may examine what evidence shows a handoff is accepted and what the sample cannot prove. The reader decisions differ. The sources, method, and conclusion should differ too. A Philippines-based virtual assistant can prepare the comparison record, source review, and overlap note. The editorial owner decides the family, route, and public treatment. Public copy should not mention internal route audits, generation, manifests, deployment, or other production mechanics. It should simply explain the research question and its evidence boundary. This separation keeps the library useful and protects the buyer from mistaking an operating suggestion for a measured finding.', table: [['Family check','Research treatment'],['Question','Specific evidence-led decision'],['Method','Named source set and local evidence scope'],['Analysis','Facts separated from interpretation'],['Limitations','What the evidence cannot establish'],['Conclusion','Evidence-led owner decision'],['Blog boundary','Do not present a checklist as research']] },
    { heading: 'Conclusion: preserve identity when the question is the same', body: 'The evidence supports an identity decision based on reader question, thesis, evidence scope, treatment, family, and history. Create a new route when the reader must make a genuinely different virtual assistant operating decision and the article needs distinct reasoning and evidence. Update the existing route when the question remains the same but a fact, source, or limitation changes. Return a brief when the question is not precise. Do not create a duplicate by swapping nouns, and do not use a new identity to hide a changed article. For OverseasVirtualAssistant.com, this protects a research library about Philippines-based virtual assistant work from becoming a stack of near-identical pages. The editor should keep route choice reversible until the comparison is complete, then preserve the reason for the decision. The sources do not prove rankings, reader preference, or business impact. They support a disciplined identity review that keeps each article honest about the question it answers.', table: [['Conclusion test','Pass condition'],['Distinctness','New route answers a different reader decision'],['Evidence fit','Method and sources match the new question'],['Family separation','Research is not Blog copy with citations'],['History','Existing routes remain unchanged and truthful'],['Boundedness','No search or business outcome is claimed']] }
  ],
  sourceNotes: 'Sources consulted: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls; https://www.fdlp.gov/; https://www.nist.gov/cyberframework. These sources inform identity, provenance, and context; route choice remains editorial analysis.',
  sources: [{ name: 'Google Search Central: Consolidate duplicate URLs', url: 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls', note: 'duplicate URL and canonicalization concepts' }, { name: 'U.S. Government Publishing Office: Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public information provenance' }, { name: 'National Institute of Standards and Technology: Cybersecurity Framework', url: 'https://www.nist.gov/cyberframework', note: 'context and risk framing' }],
  internalLinks: ['/services/research-and-data-support','/research'],
  faqs: [{ question: 'Does a new route guarantee search performance?', answer: 'No. It records an editorial identity decision and makes no ranking or conversion claim.' }, { question: 'When should an article be updated?', answer: 'When the reader question is unchanged but its evidence, conditions, or limitations materially change.' }, { question: 'Can Research reuse a Blog treatment?', answer: 'No. Research requires its own question, method, evidence analysis, limitations, and conclusion.' }],
  relatedResearch: ['/research/article-cluster-mapping-for-virtual-assistant-teams','/research/internal-link-audits-for-research-libraries','/research'],
  image: { src: '/images/research-aug20/article-identity-decisions-for-virtual-assistant-research.png', alt: 'Editorial illustration of article identity decisions for virtual assistant research' },
  cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, and owner rules with our staffing team.'
};
