import type { ResearchPost } from './data';

const sources = [
  { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'role definition, supervision, and management planning' },
  { name: 'NIST: Small Business Cybersecurity Corner', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business security controls and risk management' },
  { name: 'CISA: Cyber Guidance for Small Businesses', url: 'https://www.cisa.gov/stopransomware', note: 'ransomware prevention and response practices' },
  { name: 'FTC: Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'data minimization, access, and incident response guidance' },
  { name: 'NIST: Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy risk identification and governance' },
  { name: 'NIST: Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'identify, protect, detect, respond, and recover functions' },
  { name: 'U.S. Department of Labor: Hours Worked', url: 'https://www.dol.gov/general/topic/workhours', note: 'working-time planning reference' },
  { name: 'ILO: Working Time and Work-Life Balance Around the World', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'sustainable scheduling and working-time research' },
  { name: 'NIST: Digital Identity Guidelines', url: 'https://pages.nist.gov/800-63-3/', note: 'identity proofing and authentication concepts' },
  { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'strong passwords, MFA, updates, and phishing awareness' },
];

const topicSpecs = [
  ['role-design-for-philippines-remote-staffing', 'Role design for Philippines-based remote staffing', 'Role design', 'A bounded role makes output, ownership, access, and escalation inspectable before volume increases.'],
  ['quality-controls-for-remote-assistant-work', 'Quality controls for remote assistant work', 'Quality control', 'A small evidence-based review loop catches repeat errors before they become process debt.'],
  ['access-governance-for-delegated-operations', 'Access governance for delegated operations', 'Access governance', 'Least-privilege access and scheduled reviews reduce avoidable exposure in delegated workflows.'],
  ['shift-planning-for-philippines-based-assistants', 'Shift planning for Philippines-based assistants', 'Shift planning', 'A documented overlap and handoff window is more useful than treating time zones as a staffing strategy.'],
  ['handoff-reliability-in-distributed-teams', 'Handoff reliability in distributed teams', 'Handoff reliability', 'A handoff is reliable when the next owner can act without reconstructing context.'],
  ['evidence-based-assistant-onboarding', 'Evidence-based assistant onboarding', 'Onboarding evidence', 'Observed examples and supervised work provide stronger launch evidence than attendance alone.'],
  ['remote-operations-for-small-businesses', 'Remote operations for small businesses', 'Remote operations', 'Small teams can scale repeatable operations by pairing clear routines with explicit decision boundaries.'],
  ['manager-scorecards-for-assistant-teams', 'Manager scorecards for assistant teams', 'Manager scorecards', 'A balanced scorecard makes output, quality, blocked work, and escalation quality visible together.'],
  ['source-quality-in-assistant-prepared-briefs', 'Source quality in assistant-prepared briefs', 'Source quality', 'A brief is decision-ready when claims, dates, methods, and source links can be checked quickly.'],
  ['risk-review-before-expanding-delegated-work', 'Risk review before expanding delegated work', 'Delegation risk', 'Expansion should follow evidence from a pilot and a documented review of impact, access, and reversibility.'],
  ['customer-support-queue-controls-for-remote-teams', 'Customer-support queue controls for remote teams', 'Support queues', 'Approved response patterns and owner-only exceptions keep support helpful without creating unauthorized commitments.'],
  ['secure-file-sharing-for-virtual-assistant-work', 'Secure file sharing for virtual assistant work', 'File sharing', 'A file-sharing routine needs ownership, permissions, retention, and offboarding, rather than just a shared folder.'],
  ['research-workflow-design-for-virtual-assistants', 'Research workflow design for virtual assistants', 'Research workflows', 'Research work improves when the question, source standard, citation format, and stop rule are explicit.'],
  ['calendar-delegation-controls-for-remote-assistants', 'Calendar delegation controls for remote assistants', 'Calendar controls', 'Calendar delegation is safer when preferences, buffers, approvals, and exceptions are written down.'],
  ['sop-maturity-for-distributed-assistant-teams', 'SOP maturity for distributed assistant teams', 'SOP maturity', 'An SOP earns expansion when another trained person can follow it and produce a reviewable result.'],
  ['inbox-triage-controls-for-remote-assistants', 'Inbox triage controls for remote assistants', 'Inbox triage', 'An inbox lane is safer when categories, response authority, and unresolved-item ownership are explicit.'],
  ['meeting-notes-to-action-tracking-for-remote-teams', 'Meeting notes to action tracking for remote teams', 'Action tracking', 'Meeting notes create value when decisions, owners, due dates, and follow-up evidence are separated.'],
  ['lead-research-quality-controls-for-virtual-assistants', 'Lead research quality controls for virtual assistants', 'Lead research', 'Lead research is more useful when inclusion rules, evidence fields, and review outcomes are defined before collection.'],
  ['content-calendar-governance-for-small-teams', 'Content calendar governance for small teams', 'Content governance', 'A content calendar needs an accountable editor, source trail, status vocabulary, and approval boundary.'],
  ['documented-escalation-paths-for-delegated-work', 'Documented escalation paths for delegated work', 'Escalation design', 'Escalation paths reduce delay when triggers, owners, response expectations, and stop rules are visible.'],
  ['appointment-setting-quality-controls-for-remote-staff', 'Appointment-setting quality controls for remote staff', 'Appointment setting', 'Appointment setting should separate qualification, scheduling authority, confirmation, and exception review.'],
  ['crm-data-hygiene-routines-for-virtual-assistants', 'CRM data hygiene routines for virtual assistants', 'CRM hygiene', 'CRM maintenance is dependable when field definitions, evidence standards, and duplicate handling are documented.'],
  ['recurring-task-control-for-distributed-assistant-teams', 'Recurring task control for distributed assistant teams', 'Recurring tasks', 'Recurring work stays reliable when triggers, completion evidence, failure handling, and owner review are explicit.'],
  ['client-intake-workflow-design-for-remote-support', 'Client intake workflow design for remote support', 'Client intake', 'An intake workflow should capture the minimum useful context while keeping decisions and sensitive exceptions with the owner.'],
  ['knowledge-base-maintenance-for-remote-assistant-teams', 'Knowledge-base maintenance for remote assistant teams', 'Knowledge maintenance', 'A knowledge base remains useful when article ownership, review dates, change evidence, and retirement rules are assigned.'],
  ['quality-sampling-for-outsourced-administrative-work', 'Quality sampling for outsourced administrative work', 'Quality sampling', 'Sampling can reveal process drift when the sample frame, acceptance rule, reviewer, and correction loop are fixed.'],
  ['vendor-research-workflows-for-small-businesses', 'Vendor research workflows for small businesses', 'Vendor research', 'Vendor research becomes decision-ready when criteria, comparison evidence, conflicts, and approval ownership are recorded.'],
  ['social-media-scheduling-controls-for-remote-teams', 'Social media scheduling controls for remote teams', 'Social scheduling', 'Scheduling content is safer when approved assets, publication authority, exception handling, and audit evidence are clear.'],
  ['file-naming-and-records-routines-for-virtual-assistants', 'File naming and records routines for virtual assistants', 'Records routines', 'Consistent naming and records routines reduce reconstruction work when ownership, version, retention, and retrieval rules are explicit.'],
  ['daily-article-creation-routines-for-remote-research-teams', 'Daily article creation routines for remote research teams', 'Article creation', 'Daily article production improves when research, evidence review, drafting, visual checks, and publication ownership are staged.'],
  ['brief-quality-gates-for-remote-assistant-work', 'Brief quality gates for remote assistant work', 'Brief quality', 'A short brief is more useful when its outcome, evidence standard, owner, and stop rule are explicit.'],
  ['async-status-reporting-for-distributed-assistant-teams', 'Async status reporting for distributed assistant teams', 'Status reporting', 'A concise status report reduces coordination cost when progress, risk, next action, and owner are separated.'],
  ['approval-matrix-for-delegated-operations', 'Approval matrices for delegated operations', 'Approval design', 'An approval matrix makes authority visible before a delegated task reaches a sensitive decision.'],
  ['content-review-routines-for-small-businesses', 'Content review routines for small businesses', 'Content review', 'A content review lane is dependable when factual, editorial, accessibility, and publication checks have named owners.'],
  ['source-triage-for-assistant-research', 'Source triage for assistant research', 'Source triage', 'Source triage improves research quality when authority, relevance, date, method, and claim fit are checked separately.'],
  ['backup-coverage-for-remote-assistant-teams', 'Backup coverage for remote assistant teams', 'Backup coverage', 'Backup coverage is resilient when the substitute can find current instructions, access only what is needed, and escalate exceptions.'],
  ['offboarding-controls-for-delegated-access', 'Offboarding controls for delegated access', 'Offboarding', 'Delegated access should end through a documented checklist tied to ownership, system inventory, and evidence of removal.'],
  ['research-brief-acceptance-criteria', 'Research brief acceptance criteria', 'Research acceptance', 'A research brief is ready for drafting when the question, source list, claim boundaries, and review path are complete.'],
  ['task-aging-controls-for-remote-support', 'Task aging controls for remote support', 'Task aging', 'Aging controls surface stalled work before an overdue item becomes an invisible handoff failure.'],
  ['incident-logging-for-virtual-assistant-work', 'Incident logging for virtual assistant work', 'Incident logging', 'A useful incident log records what happened, impact, containment, owner, and prevention evidence without assigning blame.'],
  ['owner-review-routines-for-delegated-work', 'Owner review routines for delegated work', 'Owner review', 'Owner review works best as a scheduled decision loop with representative evidence and explicit follow-up.'],
  ['work-in-progress-limits-for-small-remote-teams', 'Work-in-progress limits for small remote teams', 'Work in progress', 'A modest work-in-progress limit protects quality by making queue pressure and tradeoffs visible.'],
  ['acceptance-criteria-for-assistant-task-lanes', 'Acceptance criteria for assistant task lanes', 'Acceptance criteria', 'Task lanes become easier to manage when “done” is expressed as observable evidence rather than activity.'],
  ['citation-routines-for-remote-research-teams', 'Citation routines for remote research teams', 'Citation routines', 'Citation routines make research auditable when each claim has a source, location, date, and context note.'],
  ['capacity-planning-for-remote-assistant-work', 'Capacity planning for remote assistant work', 'Capacity planning', 'Capacity planning is more useful when demand, available ownership, queue limits, and exception work are recorded together.'],
  ['editorial-source-registers-for-daily-articles', 'Editorial source registers for daily articles', 'Source registers', 'A source register keeps daily article claims traceable when URLs, access dates, claim scope, and review notes are recorded together.', '2026-08-10'],
  ['article-cluster-mapping-for-virtual-assistant-teams', 'Article cluster mapping for virtual assistant teams', 'Cluster mapping', 'A topic cluster is easier to expand safely when each article has a distinct reader question, service relationship, and internal-link role.', '2026-08-10'],
  ['research-queue-aging-for-content-operations', 'Research queue aging for content operations', 'Queue aging', 'Aging research requests need explicit next actions so stale briefs do not quietly consume review capacity or produce weak drafts.', '2026-08-10'],
  ['headline-statistic-verification-for-research-articles', 'Headline statistic verification for research articles', 'Statistic verification', 'A headline statistic is publication-ready only when its definition, denominator, date, source location, and contextual limits are recorded.', '2026-08-10'],
  ['article-methodology-notes-for-remote-researchers', 'Article methodology notes for remote researchers', 'Methodology notes', 'A concise methodology note lets an editor distinguish sourced findings from proposed operating criteria and editorial interpretation.', '2026-08-10'],
  ['research-article-fact-check-handoffs', 'Research article fact-check handoffs', 'Fact-check handoffs', 'Fact-checking is dependable when each claim arrives with its source, evidence location, status, and required editorial decision.', '2026-08-10'],
  ['internal-link-audits-for-research-libraries', 'Internal-link audits for research libraries', 'Link audits', 'Internal links are useful when they connect distinct reader needs and are checked for valid destinations, relevance, and family boundaries.', '2026-08-10'],
  ['related-research-card-governance', 'Related Research card governance', 'Related content', 'Related-content recommendations should be limited, relevant, and checked against the current article family to avoid navigational noise.', '2026-08-10'],
  ['article-revision-ledgers-for-content-teams', 'Article revision ledgers for content teams', 'Revision ledgers', 'A revision ledger preserves the reason, evidence, owner, and verification status for each material article change.', '2026-08-10'],
  ['daily-research-publishing-capacity-controls', 'Daily research publishing capacity controls', 'Publishing capacity', 'A daily publishing target should be matched to research depth, review ownership, source quality, and the team’s ability to validate every article.', '2026-08-10'],
  ['research-article-acceptance-gates-for-small-teams', 'Research article acceptance gates for small teams', 'Acceptance gates', 'Clear acceptance gates turn a draft into a publication decision by requiring evidence, structure, links, metadata, and owner review.', '2026-08-10'],
  ['claim-evidence-matrices-for-research-articles', 'Claim-evidence matrices for research articles', 'Evidence matrices', 'A claim-evidence matrix gives editors a compact way to check that important statements have the right source, scope, and review status.', '2026-08-10'],
] as const;

const related = (index: number) => [
  `/research/${topicSpecs[(index + 1) % topicSpecs.length][0]}`,
  `/research/${topicSpecs[(index + 2) % topicSpecs.length][0]}`,
  `/research/${topicSpecs[(index + 3) % topicSpecs.length][0]}`,
];

const august11ResearchSpecs = [
  {
    slug: 'role-scope-evidence-for-virtual-assistant-hiring',
    published: '2026-08-12',
    title: 'Role-scope evidence for virtual assistant hiring',
    question: 'What evidence shows that a virtual assistant role is defined well enough to recruit and manage?',
    finding: 'The Small Business Administration treats hiring and management as connected planning decisions: a business needs a clear job, expectations, and management approach before it can evaluate fit.',
    implication: 'For a Philippines-based assistant, the useful research artifact is a bounded role brief that separates recurring responsibilities from owner-only decisions and identifies the examples a candidate should discuss.',
    source: { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'employment planning, expectations, and management responsibilities' },
    image: '/images/thumbnails/generated/role-design-for-philippines-remote-staffing.webp',
  },
  {
    slug: 'data-minimization-for-delegated-assistant-work',
    published: '2026-08-12',
    title: 'Data minimization for delegated assistant work',
    question: 'How much customer or business information should a remote assistant receive to complete a task?',
    finding: 'The FTC recommends starting with the information a business actually needs, protecting it through its lifecycle, and disposing of data that no longer has a business purpose.',
    implication: 'A staffing scope should name the minimum records needed for the first task lane, the fields that must stay masked, and the owner who approves any request for broader access.',
    source: { name: 'Federal Trade Commission: Protecting personal information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', note: 'data inventory, minimization, protection, and disposal guidance' },
    image: '/images/thumbnails/generated/secure-file-sharing-for-virtual-assistant-work.webp',
  },
  {
    slug: 'working-time-evidence-for-philippines-assistant-shifts',
    published: '2026-08-12',
    title: 'Working-time evidence for Philippines assistant shifts',
    question: 'What should a business examine before choosing a shift for a Philippines-based assistant?',
    finding: 'The International Labour Organization links working-time arrangements with health, work-life balance, and productivity; a shift is therefore a service-coverage decision as well as a calendar choice.',
    implication: 'Compare the required response window, handoff opportunity, breaks, and sustainable availability instead of choosing a shift from time-zone arithmetic alone.',
    source: { name: 'International Labour Organization: Working time and work-life balance around the world', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'working-time evidence and sustainable scheduling context' },
    image: '/images/thumbnails/generated/shift-planning-for-philippines-based-assistants.webp',
  },
  {
    slug: 'identity-and-accountability-in-remote-assistant-access',
    published: '2026-08-12',
    title: 'Identity and accountability in remote assistant access',
    question: 'Which access evidence helps a business know who is using an account and what they are allowed to do?',
    finding: 'NIST Digital Identity Guidelines distinguish identity proofing, authentication, and authorization; those are separate questions and should not be collapsed into a shared password.',
    implication: 'A delegated role should use an identifiable account where possible, an authentication method appropriate to risk, and permissions tied to the specific work rather than to a person’s general trustworthiness.',
    source: { name: 'NIST: Digital Identity Guidelines', url: 'https://pages.nist.gov/800-63-3/', note: 'identity proofing, authentication, and authorization concepts' },
    image: '/images/thumbnails/generated/access-governance-for-delegated-operations.webp',
  },
  {
    slug: 'phishing-resilience-for-virtual-assistant-teams',
    published: '2026-08-12',
    title: 'Phishing resilience for virtual assistant teams',
    question: 'What makes a remote assistant team more resilient to suspicious messages and account takeover attempts?',
    finding: 'CISA’s small-business guidance emphasizes practical protections such as multifactor authentication, software updates, strong passwords, and recognizing phishing attempts.',
    implication: 'The staffing conversation should identify which messages require a pause, how suspicious requests reach the owner, and which account protections are in place before the assistant handles real customer or business records.',
    source: { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'multifactor authentication, updates, passwords, and phishing awareness' },
    image: '/images/thumbnails/generated/secure-file-sharing-for-virtual-assistant-work.webp',
  },
  {
    slug: 'privacy-risk-questions-for-remote-assistant-roles',
    published: '2026-08-12',
    title: 'Privacy-risk questions for remote assistant roles',
    question: 'How can a small business identify privacy risk before delegating a new assistant role?',
    finding: 'The NIST Privacy Framework organizes privacy risk around identifying, governing, controlling, communicating, and protecting data-processing activities.',
    implication: 'Before recruiting for a sensitive lane, map whose information is involved, why it is used, where it moves, who can change it, and how a person can raise a privacy concern.',
    source: { name: 'NIST: Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy-risk identification and governance concepts' },
    image: '/images/thumbnails/generated/client-intake-workflow-design-for-remote-support.webp',
  },
  {
    slug: 'cybersecurity-risk-evidence-for-delegated-operations',
    published: '2026-08-12',
    title: 'Cybersecurity-risk evidence for delegated operations',
    question: 'What should a manager review before expanding a virtual assistant’s access to business systems?',
    finding: 'NIST Cybersecurity Framework 2.0 gives organizations a common language for understanding, managing, and communicating cybersecurity risk across governance, identification, protection, detection, response, and recovery.',
    implication: 'Expansion evidence should cover the system and information involved, the safeguards already active, the response owner for an incident, and the recovery path if access or records are compromised.',
    source: { name: 'NIST: Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'cybersecurity risk governance and response functions' },
    image: '/images/thumbnails/generated/risk-review-before-expanding-delegated-work.webp',
  },
  {
    slug: 'source-quality-for-assistant-prepared-research',
    published: '2026-08-12',
    title: 'Source quality for assistant-prepared research',
    question: 'What makes research prepared by a virtual assistant useful to a business decision-maker?',
    finding: 'A defensible research note distinguishes the authority of a source from the relevance of a claim and preserves enough context for another reader to check the conclusion.',
    implication: 'Evaluate a research sample by its question, source provenance, publication date, quoted scope, and unresolved limitations—not by the number of links collected.',
    source: { name: 'U.S. Government Publishing Office: Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public access to authoritative government information and source provenance' },
    image: '/images/thumbnails/generated/source-quality-in-assistant-prepared-briefs.webp',
  },
  {
    slug: 'continuity-evidence-for-remote-assistant-coverage',
    published: '2026-08-12',
    title: 'Continuity evidence for remote assistant coverage',
    question: 'How can a small team tell whether assistant coverage will survive an absence or handoff?',
    finding: 'CISA’s ransomware guidance stresses preparation, backups, and recovery planning because continuity depends on what can be restored and who knows how to respond.',
    implication: 'Assess coverage by asking whether a substitute can locate current records, understand the next decision, work with limited access, and escalate when the normal owner is unavailable.',
    source: { name: 'CISA: StopRansomware guide', url: 'https://www.cisa.gov/stopransomware', note: 'preparation, backup, response, and recovery guidance' },
    image: '/images/thumbnails/generated/backup-coverage-for-remote-assistant-teams.webp',
  },
  {
    slug: 'handoff-latency-in-distributed-assistant-support',
    published: '2026-08-12',
    title: 'Handoff latency in distributed assistant support',
    question: 'How should a business study delays between a Philippines-based assistant and the next decision-maker?',
    finding: 'Handoff delay is not simply a time-zone problem: it combines the moment work becomes blocked, the quality of the context sent forward, and the availability of the next owner.',
    implication: 'A useful sample records blocked time, missing context, escalation destination, and resolution—not just whether a task was eventually completed.',
    source: { name: 'U.S. Department of Labor: Hours worked', url: 'https://www.dol.gov/general/topic/workhours', note: 'working-time planning reference for evaluating scheduled coverage' },
    image: '/images/thumbnails/generated/handoff-reliability-in-distributed-teams.webp',
  },
] as const;

const makeAugust11ResearchPost = (spec: typeof august11ResearchSpecs[number], index: number): ResearchPost => ({
  slug: spec.slug,
  title: `Research note: ${spec.title}`,
  excerpt: `${spec.question} Evidence-led findings for businesses planning Philippines-based virtual assistant support.`,
  published: spec.published,
  methodology: `This article examines one decision question through the cited authoritative source and separates sourced guidance from the editorial interpretation. It does not claim a workforce statistic; the review criteria are proposed for a bounded staffing study.`,
  headlineStat: { value: '1', label: 'decision question kept in scope for this research note', source: 'Editorial scope statement for this article' },
  keyStats: [{ value: '1', label: 'authoritative source examined' }, { value: '4', label: 'evidence fields to review' }, { value: '0', label: 'unsupported workforce claims' }],
  takeaways: [spec.finding, spec.implication, 'Treat the conclusion as a research input for a role decision and revisit it when the work, information, or service expectation changes.'],
  sections: [
    { heading: 'What the source supports', body: spec.finding, table: [['Evidence field', 'Question to answer'], ['Authority', 'Who published the guidance and for what audience?'], ['Scope', 'Which claim or risk does it actually address?'], ['Limit', 'What does the source leave for the business to decide?']] },
    { heading: 'What the staffing decision still needs', body: spec.implication, table: [['Decision input', 'Record'], ['Work', 'The task and observable outcome'], ['Information', 'The minimum records or systems needed'], ['Ownership', 'The person who approves exceptions'], ['Review', 'The evidence that would change the decision']] },
    { heading: 'How to read a sample', body: `Use representative examples from the ${index % 2 === 0 ? 'first role discussion' : 'first task lane'} and compare them with the source-backed question above. Note what is known, what is inferred, and what requires owner or professional judgment. A sample is evidence for a decision, not proof that every future case will behave the same way.`, table: [['Result', 'Interpretation'], ['Supported', 'Keep the finding in the role brief'], ['Unclear', 'Collect a narrower example or ask the owner'], ['Outside scope', 'Pause and route the decision to the right authority']] },
  ],
  sourceNotes: `Source note: ${spec.source.name} is cited for the evidence boundary. The staffing implications are editorial analysis for OverseasVirtualAssistant.com and are not presented as measurements from the cited source.`,
  sources: [spec.source],
  internalLinks: ['/services/research-and-data-support', '/research'],
  faqs: [
    { question: 'Does this article measure assistant performance?', answer: 'No. It defines a way to examine one staffing decision and clearly separates the source’s guidance from proposed review criteria.' },
    { question: 'What should a business do with an ambiguous result?', answer: 'Keep the decision narrow, record the unresolved question, and ask the authorized owner or qualified professional before expanding the role.' },
    { question: 'Why is the Philippines context included?', answer: 'The service audience hires Philippines-based virtual assistants, so coverage, access, and handoff questions should be considered in that real service context without turning it into a workforce claim.' },
  ],
  relatedResearch: related(15 + index),
  image: { src: spec.image, alt: `Research illustration for ${spec.title}` },
  cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, and owner rules with our staffing team.',
});

const august13ResearchSpecs = [
  ['delegation-boundaries-for-client-intake','Delegation boundaries for client intake','Client intake is useful when support staff can organize facts without turning an incomplete record into a promise or eligibility decision.','The SBA connects clear job expectations with management, while the FTC advises businesses to understand and protect the personal information they collect.','Separate collection, completeness checks, owner review, and acceptance decisions. Measure missing fields and escalation reasons by a stated period, not by impressions.','Public guidance does not determine a firm’s intake policy or professional obligations. Sensitive or regulated intake requires the responsible owner’s review.',['https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees','https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business','https://www.nist.gov/privacy-framework'],'client-intake-workflow-design-for-remote-support'],
  ['appointment-buffer-evidence-for-executive-assistance','Appointment buffer evidence for executive assistance','Calendar buffers should be based on travel, preparation, time-zone, and recovery demands rather than a universal interval copied from another schedule.','The ILO examines working-time arrangements and work-life balance, while NIST risk guidance emphasizes identifying context before selecting safeguards.','Review a defined sample of appointments for preparation time, overruns, changes, and owner-approved exceptions. Distinguish a missed buffer from a deliberately accepted tradeoff.','A local calendar sample cannot prove productivity or a legally appropriate schedule. It can reveal whether the current planning assumption fits the work.',['https://www.ilo.org/publications/working-time-and-work-life-balance-around-world','https://www.nist.gov/privacy-framework','https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'],'calendar-delegation-controls-for-remote-assistants'],
  ['record-retention-decisions-for-remote-support','Record-retention decisions for remote support','Delegated record work needs a retention decision because keeping every document forever increases retrieval burden and exposure.','The FTC recommends knowing what information a business holds, protecting it through its lifecycle, and disposing of information that no longer has a business purpose. NIST frames privacy as a risk-management concern.','For each record class, name its purpose, owner, approved location, review trigger, and deletion authority. Test retrieval and removal using representative records.','Retention periods can depend on contracts, jurisdictions, and regulated obligations. This research does not set a legal retention schedule.',['https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business','https://www.nist.gov/privacy-framework','https://www.ftc.gov/business-guidance/resources/start-security-guide-business'],'file-naming-and-records-routines-for-virtual-assistants'],
  ['exception-routing-in-property-management-admin','Exception routing in property-management administration','Property-management support is safer when routine updates are separated from safety, habitability, legal, and commitment decisions.','The SBA emphasizes defined expectations and management responsibility. NIST’s cybersecurity framework gives organizations a way to identify, respond to, and recover from risk rather than treating every request as ordinary.','Classify a dated sample of requests by routine, urgent, specialist, and owner decision. Record the evidence available, the responsible escalation owner, and whether the response made a commitment.','A routing study cannot provide legal, housing, or safety advice. Local rules and qualified property professionals determine the correct response.',['https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees','https://www.nist.gov/cyberframework','https://www.ftc.gov/business-guidance/resources/start-security-guide-business'],'documented-escalation-paths-for-delegated-work'],
  ['source-provenance-for-vendor-research','Source provenance for vendor research','Vendor research becomes decision-ready when a reader can trace each comparison field to a dated source and see what remains unverified.','The Government Publishing Office supports access to authoritative government information, while NIST risk guidance calls for understanding context and purpose before selecting controls.','Keep the source URL, access date, definition, quoted scope, and unresolved question beside each material field. Separate a vendor statement from an independently verified fact.','A source register does not establish vendor quality or guarantee an outcome. Commercial, legal, and security decisions still belong to the authorized owner.',['https://www.fdlp.gov/','https://www.nist.gov/cyberframework','https://www.nist.gov/privacy-framework'],'vendor-research-workflows-for-small-businesses'],
  ['follow-up-reliability-for-service-businesses','Follow-up reliability for service businesses','Follow-up is reliable when a customer request has a visible owner, due period, source context, and confirmation of what was actually promised.','The SBA treats expectations and management as connected, and the FTC emphasizes protecting information throughout its lifecycle.','Sample follow-ups by request type and record whether the next action, owner, due period, and customer-facing commitment were explicit. Count unresolved items separately from completed contacts.','A follow-up record measures traceability, not customer satisfaction or business growth. Promises and regulated advice remain outside delegated authority.',['https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees','https://www.ftc.gov/business-guidance/resources/start-security-guide-business','https://www.cisa.gov/secure-our-world'],'task-aging-controls-for-remote-support'],
  ['approval-boundaries-for-invoice-preparation','Approval boundaries for invoice preparation','Invoice preparation can be delegated as record assembly when calculation, contractual interpretation, and payment approval remain visibly separate decisions.','The SBA links role expectations to management, while FTC guidance supports limiting access to information and protecting it through its lifecycle.','Review a period of draft invoices for source records, missing evidence, calculation changes, approval owner, and release status. Never treat a prepared draft as an approved financial commitment.','The sources do not determine accounting treatment, tax rules, or payment authority. A qualified finance professional must resolve those questions.',['https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees','https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business','https://www.nist.gov/privacy-framework'],'approval-matrix-for-delegated-operations'],
  ['record-reconciliation-for-ecommerce-support','Record reconciliation for ecommerce support','Ecommerce support needs reconciliation because an order status, inventory note, and customer message can describe different moments in the same transaction.','The FTC advises businesses to understand the information they hold and protect it, while NIST risk guidance favors identifying and responding to discrepancies.','Compare a stated period of orders across the approved records, mark the source of each status, and route substitutions, refunds, damaged goods, and delivery disputes to the authorized owner.','Reconciliation can expose inconsistency but cannot establish carrier liability, consumer-law compliance, or an inventory forecast.',['https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business','https://www.nist.gov/cyberframework','https://www.cisa.gov/secure-our-world'],'crm-data-hygiene-routines-for-virtual-assistants'],
  ['backup-access-testing-for-remote-assistant-coverage','Backup access testing for remote assistant coverage','Continuity depends on a substitute having current instructions and the minimum access needed to complete safe work without inheriting unrestricted authority.','CISA connects preparation, backups, and recovery, and NIST includes response and recovery in its framework functions.','Test one bounded lane with a substitute scenario: locate the current record, perform low-risk work, identify an exception, and document where access stopped. Record every unavailable dependency.','A tabletop or controlled exercise cannot predict every outage and should not grant broad production access. Security and employment owners must approve the test.',['https://www.cisa.gov/stopransomware','https://www.nist.gov/cyberframework','https://www.ftc.gov/business-guidance/resources/start-security-guide-business'],'backup-coverage-for-remote-assistant-teams'],
] as const;

const august13Source = (url: string) => ({ name: url.includes('ilo.org') ? 'International Labour Organization' : url.includes('nist.gov') ? 'National Institute of Standards and Technology' : url.includes('ftc.gov') ? 'Federal Trade Commission' : url.includes('sba.gov') ? 'U.S. Small Business Administration' : url.includes('cisa.gov') ? 'Cybersecurity and Infrastructure Security Agency' : url.includes('dol.gov') ? 'U.S. Department of Labor' : 'U.S. Government Publishing Office', url, note: 'claim-relevant authoritative source for this research note' });

const makeAugust13ResearchPost = (spec: typeof august13ResearchSpecs[number], index: number): ResearchPost => {
  const [slug, title, thesis, evidence, decision, limit, sourceUrls, imageSlug] = spec;
  const body = (extra: string) => extra + ' The source claim needs to stay at its proper level. It describes a principle, a risk category, or a research result. It does not select a worker, set a contract, or decide what a particular customer should receive. Use it to make the question precise, then gather local evidence from the actual service lane. Keep the date, population, definition, and source location with every material finding. If a sentence cannot be traced to a source or local record, label it as interpretation or remove it. A careful note is allowed to conclude that the evidence is mixed. That is more useful than a confident answer that changes the denominator or hides the exception. The business should also ask what the source leaves out. A security framework may describe controls but not the customer’s expectations. A working-time study may compare schedules but not settle an employment question. A hiring guide may explain management duties but not prove that one role is well designed. Those gaps are where local judgment belongs. State them plainly. Then describe the smallest additional record that would reduce the uncertainty. This could be a dated sample of requests, a permissions review, a handoff record, or an owner decision. The record should be proportionate to the risk. There is no reason to collect sensitive details that the question does not require. There is also no reason to treat a convenient count as evidence if the items were selected after the result was known. A manager should be able to read the study and reconstruct why the items were included, what was observed, and what was not observed. That makes the conclusion auditable without turning the article into a promise. It also protects the worker from being judged on an unclear standard. When a finding is uncertain, the honest action is to narrow the work or ask for a decision, not to fill the gap with a guess. This matters especially across time zones, where a short message can conceal a missing record or an owner who was unavailable. A useful escalation states the question, the evidence already checked, the decision needed, and the consequence of waiting. The person preparing the information can then stop at the boundary of their authority. The owner can decide whether the case belongs in the current lane or needs a different adviser. That separation keeps the study relevant to a real service decision while preventing a general source from being stretched into a specific claim. The conclusion should therefore name both the supported finding and the unresolved part. A reader should know what to keep, what to test next, and what not to infer.';
  const sample = decision + ' Define the sample before reading the result. Choose a period, list eligible items, and say which items were excluded. Capture the original request, information available, action taken, result, and reviewer disposition. If work was delayed, record when it became blocked and who could unblock it. If it was corrected, record the reason rather than treating correction as a personal score. For sensitive work, record an access category without copying unnecessary personal information. A short described sample is more useful than a large count with no denominator or decision rule.';
  return {
    slug, title: 'Research note: ' + title, excerpt: thesis + ' Evidence-led analysis for businesses planning Philippines-based virtual assistant support.', published: '2026-08-13',
    methodology: 'This article keeps one decision question in scope and compares it with three named public sources. Source claims, local interpretation, and limitations are separated. It does not claim a workforce average or promise a result for every business. It gives a bounded way to inspect a real service decision using dated records, representative examples, and an owner who can pause the work when evidence is incomplete.',
    headlineStat: { value: '1', label: 'decision question examined in this research note', source: 'Explicit editorial scope for this article' },
    keyStats: [{ value: '3', label: 'claim-relevant authoritative sources' }, { value: '4', label: 'evidence fields to inspect' }, { value: '0', label: 'unsupported workforce averages' }],
    takeaways: [thesis, decision, limit],
    sections: [
      { heading: 'What the evidence says', body: body(evidence), table: [['Evidence field','Question'],['Source and date','Who published the claim, and when?'],['Scope','Which people, records, period, or risk does it describe?'],['Local observation','What happened in this business lane?'],['Limit','What remains outside the evidence?']] },
      { heading: 'What a business should measure locally', body: sample, table: [['Local field','Why it matters'],['Eligible item','Defines the denominator'],['Input available','Shows what the worker could reasonably know'],['Disposition','Separates accepted, corrected, pending, and escalated work'],['Owner decision','Shows whether the lane should continue or change']] },
      { heading: 'Where interpretation can go wrong', body: body('A business can misread this question by counting activity instead of accepted output, using one unusual request as if it represented the lane, or comparing shifts with different request mixes and owner availability. It can also turn general guidance into a local promise. Preserve exceptions in the result. A result marked "unclear" tells the owner that the question needs a narrower sample, better access, or professional review. A result outside the worker’s authority should stop at escalation.'), table: [['Result','Responsible interpretation'],['Supported','Keep the finding within its stated scope'],['Mixed','Separate ordinary items from exceptions'],['Unclear','Collect a narrower example or ask the owner'],['Outside authority','Pause and escalate']] },
      { heading: 'A bounded decision for the owner', body: body('The final decision should be small enough to reverse. The owner might keep one task lane, change the information available, alter the review point, or pause expansion. Each choice should name the evidence that supports it and the observation that would reopen it. This keeps the staffing conversation grounded in a clearly scoped Philippines-based virtual assistant role with defined tools, hours, handoffs, and owner-only decisions. Growth is possible when evidence supports the next step, but growth is not the default conclusion.'), table: [['Decision','Evidence required'],['Continue','Representative work is reviewable and within scope'],['Revise','A repeat issue has a specific correction'],['Pause','Risk, authority, or evidence remains unresolved'],['Expand','The next task has a named owner and acceptance rule']] },
      { heading: 'Conclusion', body: thesis + ' The sources support a disciplined question, not a slogan. Start with the work and the people affected, define evidence before reading the result, and keep interpretation narrower than the source. Make one owner-approved change that can be checked in the next review period. ' + limit + ' That boundary is part of the finding.', table: [['Conclusion test','Pass condition'],['Relevant','Answers the stated service decision'],['Traceable','Points to a named source or local record'],['Bounded','Units, period, cohort, and limitations are visible'],['Actionable','The owner can choose a reversible next step']] },
    ],
    sourceNotes: 'Source notes: ' + sourceUrls.join('; ') + ' are cited for the evidence boundary. The local decision criteria are editorial analysis for OverseasVirtualAssistant.com, not measurements of a workforce or guarantees of service performance.',
    sources: sourceUrls.map(august13Source), internalLinks: ['/services/research-and-data-support','/research'], faqs: [
      { question: 'Does this article measure virtual assistant performance?', answer: 'No. It defines a bounded question and a local evidence record. It does not produce a general performance rate.' },
      { question: 'What if the evidence is mixed?', answer: 'Separate ordinary items from exceptions, record the limitation, and let the authorized owner decide whether to revise or pause the scope.' },
      { question: 'Why is the Philippines context included?', answer: 'The company serves businesses planning Philippines-based virtual assistant support. The context makes the service decision concrete without becoming a claim about a country or workforce.' },
    ], relatedResearch: related(20 + index), image: { src: '/images/thumbnails/generated/' + imageSlug + '.webp', alt: 'Research illustration for ' + title }, cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, and owner rules with our staffing team.',
  };
};

export const researchPosts: ResearchPost[] = [...topicSpecs.map(([slug, title, cluster, thesis, publishedDate], index) => ({
  slug,
  title: `Research note: ${title}`,
  excerpt: `Evidence-led planning note on ${title.toLowerCase()} for teams building dependable Philippines-based support routines.`,
  published: publishedDate || (index < 15 ? '2026-08-08' : '2026-08-09'),
  methodology: `This note uses a structured review of ${sources.length} public primary and government sources, then translates the evidence into an operational pilot. The headline measure is a proposed acceptance criterion, not a claim about the workforce. Recheck source dates and applicable local requirements before implementation.`,
  headlineStat: { value: '100%', label: 'of pilot work items should have an owner disposition before the lane expands', source: 'Operational acceptance criterion defined for this research note' },
  keyStats: [
    { value: '10', label: 'authoritative sources reviewed' },
    { value: '3', label: 'review checkpoints in the pilot' },
    { value: '1', label: 'named owner for exceptions' },
  ],
  takeaways: [
    `Define ${cluster.toLowerCase()} as a visible routine with a trigger, inputs, output, and review owner.`,
    'Start with a reversible pilot and record completed, correct, blocked, and escalated work separately.',
    'Keep approvals, sensitive access, legal or financial commitments, and unusual exceptions with the authorized owner.',
  ],
  sections: [
    { heading: 'What the evidence supports', body: `${thesis} Across the source set, the common control is not a particular tool or geography; it is a clear owner, a bounded task, and a way to detect and correct exceptions.`, table: [['Evidence question', 'Practical answer'], ['Who decides?', 'Name the owner before work starts.'], ['What proves completion?', 'Define a reviewable output and acceptance rule.'], ['When should work stop?', 'Document the exception and escalation path.']] },
    { heading: 'A defensible pilot design', body: 'Use representative examples, minimum required access, a fixed review window, and a short batch size. Capture the input, action, result, reviewer decision, and any correction needed. Do not infer quality from hours online or activity counts alone.', table: [['Pilot field', 'Record'], ['Scope', 'One task lane and explicit exclusions'], ['Quality', 'Accepted, corrected, rejected, or pending'], ['Risk', 'Access used and exceptions escalated'], ['Decision', 'Continue, revise, or pause with rationale']] },
    { heading: 'How to operationalize the result', body: 'At the end of each review checkpoint, update the SOP only when the evidence shows a repeatable improvement. Preserve the previous instruction until the new version is tested. If the work touches personal data, payments, regulated advice, or customer commitments, obtain the appropriate owner or professional review before expanding the scope.', table: [['Checkpoint', 'Decision'], ['Launch', 'Can the worker explain the finish line?'], ['Review', 'Can the manager inspect representative output?'], ['Expand', 'Are exceptions understood and controlled?']] },
  ],
  sourceNotes: 'Source notes: government and standards-body guidance is used for control concepts; the operational thresholds above are proposed acceptance criteria for a local pilot and should not be presented as externally measured workforce statistics.',
  sources,
  internalLinks: ['/blog', '/services', '/contact'],
  faqs: [
    { question: 'Is this a staffing performance claim?', answer: 'No. The percentage and counts are proposed pilot controls unless a source is explicitly identified; they are not claims about an individual or a workforce.' },
    { question: 'What should happen when a source or requirement conflicts?', answer: 'Pause the affected item, record the conflict, and escalate it to the named owner or qualified adviser.' },
    { question: 'When is the routine ready to expand?', answer: 'Only after representative work is reviewable, exceptions have an owner, and the updated SOP has been tested.' },
  ],
  relatedResearch: related(index),
  image: { src: `/images/thumbnails/generated/${slug}.webp`, alt: `Research illustration for ${title}` },
  cta: 'Want this research translated into a scoped staffing routine? Share the task lane, tools, schedule, and owner rules with our staffing team.',
})), ...august11ResearchSpecs.map(makeAugust11ResearchPost), ...august13ResearchSpecs.map(makeAugust13ResearchPost)].sort((a, b) => b.published.localeCompare(a.published) || a.slug.localeCompare(b.slug));
