import type { ResearchPost } from './data';

const sources = [
  { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'role definition, supervision, and management planning' },
  { name: 'NIST: Small Business Cybersecurity Corner', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business security controls and risk management' },
  { name: 'CISA: Cyber Guidance for Small Businesses', url: 'https://www.cisa.gov/stopransomware', note: 'ransomware prevention and response practices' },
  { name: 'FTC: Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'data minimization, access, and incident response guidance' },
  { name: 'NIST: Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy risk identification and governance' },
  { name: 'NIST: Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'identify, protect, detect, respond, and recover functions' },
  { name: 'U.S. Department of Labor: Hours Worked', url: 'https://www.dol.gov/general/topic/workhours', note: 'working-time planning reference' },
  { name: 'ILO: Working Time and Work-Life Balance Around the World', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'sustainable scheduling and working-time research' },
  { name: 'NIST: Digital Identity Guidelines', url: 'https://pages.nist.gov/800-63-3/', note: 'identity proofing and authentication concepts' },
  { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'strong passwords, MFA, updates, and phishing awareness' },
];

const topicSpecs = [
  ['role-design-for-philippines-remote-staffing', 'Role design for Philippines-based remote staffing', 'Role design', 'A bounded role makes output, ownership, access, and escalation inspectable before volume increases.'],
  ['quality-controls-for-remote-assistant-work', 'Quality controls for remote assistant work', 'Quality control', 'A small evidence-based review loop catches repeat errors before they become process debt.'],
  ['access-governance-for-delegated-operations', 'Access governance for delegated operations', 'Access governance', 'Least-privilege access and scheduled reviews reduce avoidable exposure in delegated workflows.'],
  ['shift-planning-for-philippines-based-assistants', 'Shift planning for Philippines-based assistants', 'Shift planning', 'A documented overlap and handoff window is more useful than treating time zones as a staffing strategy.'],
  ['handoff-reliability-in-distributed-teams', 'Handoff reliability in distributed teams', 'Handoff reliability', 'A handoff is reliable when the next owner can act without reconstructing context.'],
  ['evidence-based-assistant-onboarding', 'Evidence-based assistant onboarding', 'Onboarding evidence', 'Observed examples and supervised work provide stronger launch evidence than attendance alone.'],
  ['remote-operations-for-small-businesses', 'Remote operations for small businesses', 'Remote operations', 'Small teams can scale repeatable operations by pairing clear routines with explicit decision boundaries.'],
  ['manager-scorecards-for-assistant-teams', 'Manager scorecards for assistant teams', 'Manager scorecards', 'A balanced scorecard makes output, quality, blocked work, and escalation quality visible together.'],
  ['source-quality-in-assistant-prepared-briefs', 'Source quality in assistant-prepared briefs', 'Source quality', 'A brief is decision-ready when claims, dates, methods, and source links can be checked quickly.'],
  ['risk-review-before-expanding-delegated-work', 'Risk review before expanding delegated work', 'Delegation risk', 'Expansion should follow evidence from a pilot and a documented review of impact, access, and reversibility.'],
  ['customer-support-queue-controls-for-remote-teams', 'Customer-support queue controls for remote teams', 'Support queues', 'Approved response patterns and owner-only exceptions keep support helpful without creating unauthorized commitments.'],
  ['secure-file-sharing-for-virtual-assistant-work', 'Secure file sharing for virtual assistant work', 'File sharing', 'A file-sharing routine needs ownership, permissions, retention, and offboarding, rather than just a shared folder.'],
  ['research-workflow-design-for-virtual-assistants', 'Research workflow design for virtual assistants', 'Research workflows', 'Research work improves when the question, source standard, citation format, and stop rule are explicit.'],
  ['calendar-delegation-controls-for-remote-assistants', 'Calendar delegation controls for remote assistants', 'Calendar controls', 'Calendar delegation is safer when preferences, buffers, approvals, and exceptions are written down.'],
  ['sop-maturity-for-distributed-assistant-teams', 'SOP maturity for distributed assistant teams', 'SOP maturity', 'An SOP earns expansion when another trained person can follow it and produce a reviewable result.'],
  ['inbox-triage-controls-for-remote-assistants', 'Inbox triage controls for remote assistants', 'Inbox triage', 'An inbox lane is safer when categories, response authority, and unresolved-item ownership are explicit.'],
  ['meeting-notes-to-action-tracking-for-remote-teams', 'Meeting notes to action tracking for remote teams', 'Action tracking', 'Meeting notes create value when decisions, owners, due dates, and follow-up evidence are separated.'],
  ['lead-research-quality-controls-for-virtual-assistants', 'Lead research quality controls for virtual assistants', 'Lead research', 'Lead research is more useful when inclusion rules, evidence fields, and review outcomes are defined before collection.'],
  ['content-calendar-governance-for-small-teams', 'Content calendar governance for small teams', 'Content governance', 'A content calendar needs an accountable editor, source trail, status vocabulary, and approval boundary.'],
  ['documented-escalation-paths-for-delegated-work', 'Documented escalation paths for delegated work', 'Escalation design', 'Escalation paths reduce delay when triggers, owners, response expectations, and stop rules are visible.'],
  ['appointment-setting-quality-controls-for-remote-staff', 'Appointment-setting quality controls for remote staff', 'Appointment setting', 'Appointment setting should separate qualification, scheduling authority, confirmation, and exception review.'],
  ['crm-data-hygiene-routines-for-virtual-assistants', 'CRM data hygiene routines for virtual assistants', 'CRM hygiene', 'CRM maintenance is dependable when field definitions, evidence standards, and duplicate handling are documented.'],
  ['recurring-task-control-for-distributed-assistant-teams', 'Recurring task control for distributed assistant teams', 'Recurring tasks', 'Recurring work stays reliable when triggers, completion evidence, failure handling, and owner review are explicit.'],
  ['client-intake-workflow-design-for-remote-support', 'Client intake workflow design for remote support', 'Client intake', 'An intake workflow should capture the minimum useful context while keeping decisions and sensitive exceptions with the owner.'],
  ['knowledge-base-maintenance-for-remote-assistant-teams', 'Knowledge-base maintenance for remote assistant teams', 'Knowledge maintenance', 'A knowledge base remains useful when article ownership, review dates, change evidence, and retirement rules are assigned.'],
  ['quality-sampling-for-outsourced-administrative-work', 'Quality sampling for outsourced administrative work', 'Quality sampling', 'Sampling can reveal process drift when the sample frame, acceptance rule, reviewer, and correction loop are fixed.'],
  ['vendor-research-workflows-for-small-businesses', 'Vendor research workflows for small businesses', 'Vendor research', 'Vendor research becomes decision-ready when criteria, comparison evidence, conflicts, and approval ownership are recorded.'],
  ['social-media-scheduling-controls-for-remote-teams', 'Social media scheduling controls for remote teams', 'Social scheduling', 'Scheduling content is safer when approved assets, publication authority, exception handling, and audit evidence are clear.'],
  ['file-naming-and-records-routines-for-virtual-assistants', 'File naming and records routines for virtual assistants', 'Records routines', 'Consistent naming and records routines reduce reconstruction work when ownership, version, retention, and retrieval rules are explicit.'],
  ['daily-article-creation-routines-for-remote-research-teams', 'Daily article creation routines for remote research teams', 'Article creation', 'Daily article production improves when research, evidence review, drafting, visual checks, and publication ownership are staged.'],
  ['brief-quality-gates-for-remote-assistant-work', 'Brief quality gates for remote assistant work', 'Brief quality', 'A short brief is more useful when its outcome, evidence standard, owner, and stop rule are explicit.'],
  ['async-status-reporting-for-distributed-assistant-teams', 'Async status reporting for distributed assistant teams', 'Status reporting', 'A concise status report reduces coordination cost when progress, risk, next action, and owner are separated.'],
  ['approval-matrix-for-delegated-operations', 'Approval matrices for delegated operations', 'Approval design', 'An approval matrix makes authority visible before a delegated task reaches a sensitive decision.'],
  ['content-review-routines-for-small-businesses', 'Content review routines for small businesses', 'Content review', 'A content review lane is dependable when factual, editorial, accessibility, and publication checks have named owners.'],
  ['source-triage-for-assistant-research', 'Source triage for assistant research', 'Source triage', 'Source triage improves research quality when authority, relevance, date, method, and claim fit are checked separately.'],
  ['backup-coverage-for-remote-assistant-teams', 'Backup coverage for remote assistant teams', 'Backup coverage', 'Backup coverage is resilient when the substitute can find current instructions, access only what is needed, and escalate exceptions.'],
  ['offboarding-controls-for-delegated-access', 'Offboarding controls for delegated access', 'Offboarding', 'Delegated access should end through a documented checklist tied to ownership, system inventory, and evidence of removal.'],
  ['research-brief-acceptance-criteria', 'Research brief acceptance criteria', 'Research acceptance', 'A research brief is ready for drafting when the question, source list, claim boundaries, and review path are complete.'],
  ['task-aging-controls-for-remote-support', 'Task aging controls for remote support', 'Task aging', 'Aging controls surface stalled work before an overdue item becomes an invisible handoff failure.'],
  ['incident-logging-for-virtual-assistant-work', 'Incident logging for virtual assistant work', 'Incident logging', 'A useful incident log records what happened, impact, containment, owner, and prevention evidence without assigning blame.'],
  ['owner-review-routines-for-delegated-work', 'Owner review routines for delegated work', 'Owner review', 'Owner review works best as a scheduled decision loop with representative evidence and explicit follow-up.'],
  ['work-in-progress-limits-for-small-remote-teams', 'Work-in-progress limits for small remote teams', 'Work in progress', 'A modest work-in-progress limit protects quality by making queue pressure and tradeoffs visible.'],
  ['acceptance-criteria-for-assistant-task-lanes', 'Acceptance criteria for assistant task lanes', 'Acceptance criteria', 'Task lanes become easier to manage when “done” is expressed as observable evidence rather than activity.'],
  ['citation-routines-for-remote-research-teams', 'Citation routines for remote research teams', 'Citation routines', 'Citation routines make research auditable when each claim has a source, location, date, and context note.'],
  ['capacity-planning-for-remote-assistant-work', 'Capacity planning for remote assistant work', 'Capacity planning', 'Capacity planning is more useful when demand, available ownership, queue limits, and exception work are recorded together.'],
  ['editorial-source-registers-for-daily-articles', 'Editorial source registers for daily articles', 'Source registers', 'A source register keeps daily article claims traceable when URLs, access dates, claim scope, and review notes are recorded together.', '2026-08-10'],
  ['article-cluster-mapping-for-virtual-assistant-teams', 'Article cluster mapping for virtual assistant teams', 'Cluster mapping', 'A topic cluster is easier to expand safely when each article has a distinct reader question, service relationship, and internal-link role.', '2026-08-10'],
  ['research-queue-aging-for-content-operations', 'Research queue aging for content operations', 'Queue aging', 'Aging research requests need explicit next actions so stale briefs do not quietly consume review capacity or produce weak drafts.', '2026-08-10'],
  ['headline-statistic-verification-for-research-articles', 'Headline statistic verification for research articles', 'Statistic verification', 'A headline statistic is publication-ready only when its definition, denominator, date, source location, and contextual limits are recorded.', '2026-08-10'],
  ['article-methodology-notes-for-remote-researchers', 'Article methodology notes for remote researchers', 'Methodology notes', 'A concise methodology note lets an editor distinguish sourced findings from proposed operating criteria and editorial interpretation.', '2026-08-10'],
  ['research-article-fact-check-handoffs', 'Research article fact-check handoffs', 'Fact-check handoffs', 'Fact-checking is dependable when each claim arrives with its source, evidence location, status, and required editorial decision.', '2026-08-10'],
  ['internal-link-audits-for-research-libraries', 'Internal-link audits for research libraries', 'Link audits', 'Internal links are useful when they connect distinct reader needs and are checked for valid destinations, relevance, and family boundaries.', '2026-08-10'],
  ['related-research-card-governance', 'Related Research card governance', 'Related content', 'Related-content recommendations should be limited, relevant, and checked against the current article family to avoid navigational noise.', '2026-08-10'],
  ['article-revision-ledgers-for-content-teams', 'Article revision ledgers for content teams', 'Revision ledgers', 'A revision ledger preserves the reason, evidence, owner, and verification status for each material article change.', '2026-08-10'],
  ['daily-research-publishing-capacity-controls', 'Daily research publishing capacity controls', 'Publishing capacity', 'A daily publishing target should be matched to research depth, review ownership, source quality, and the team’s ability to validate every article.', '2026-08-10'],
  ['research-article-acceptance-gates-for-small-teams', 'Research article acceptance gates for small teams', 'Acceptance gates', 'Clear acceptance gates turn a draft into a publication decision by requiring evidence, structure, links, metadata, and owner review.', '2026-08-10'],
  ['claim-evidence-matrices-for-research-articles', 'Claim-evidence matrices for research articles', 'Evidence matrices', 'A claim-evidence matrix gives editors a compact way to check that important statements have the right source, scope, and review status.', '2026-08-10'],
] as const;

const related = (index: number) => [
  `/research/${topicSpecs[(index + 1) % topicSpecs.length][0]}`,
  `/research/${topicSpecs[(index + 2) % topicSpecs.length][0]}`,
  `/research/${topicSpecs[(index + 3) % topicSpecs.length][0]}`,
];

const august11ResearchSpecs = [
  {
    slug: 'role-scope-evidence-for-virtual-assistant-hiring',
    published: '2026-08-12',
    title: 'Role-scope evidence for virtual assistant hiring',
    question: 'What evidence shows that a virtual assistant role is defined well enough to recruit and manage?',
    finding: 'The Small Business Administration treats hiring and management as connected planning decisions: a business needs a clear job, expectations, and management approach before it can evaluate fit.',
    implication: 'For a Philippines-based assistant, the useful research artifact is a bounded role brief that separates recurring responsibilities from owner-only decisions and identifies the examples a candidate should discuss.',
    source: { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'employment planning, expectations, and management responsibilities' },
    image: '/images/thumbnails/generated/role-design-for-philippines-remote-staffing.webp',
  },
  {
    slug: 'data-minimization-for-delegated-assistant-work',
    published: '2026-08-12',
    title: 'Data minimization for delegated assistant work',
    question: 'How much customer or business information should a remote assistant receive to complete a task?',
    finding: 'The FTC recommends starting with the information a business actually needs, protecting it through its lifecycle, and disposing of data that no longer has a business purpose.',
    implication: 'A staffing scope should name the minimum records needed for the first task lane, the fields that must stay masked, and the owner who approves any request for broader access.',
    source: { name: 'Federal Trade Commission: Protecting personal information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', note: 'data inventory, minimization, protection, and disposal guidance' },
    image: '/images/thumbnails/generated/secure-file-sharing-for-virtual-assistant-work.webp',
  },
  {
    slug: 'working-time-evidence-for-philippines-assistant-shifts',
    published: '2026-08-12',
    title: 'Working-time evidence for Philippines assistant shifts',
    question: 'What should a business examine before choosing a shift for a Philippines-based assistant?',
    finding: 'The International Labour Organization links working-time arrangements with health, work-life balance, and productivity; a shift is therefore a service-coverage decision as well as a calendar choice.',
    implication: 'Compare the required response window, handoff opportunity, breaks, and sustainable availability instead of choosing a shift from time-zone arithmetic alone.',
    source: { name: 'International Labour Organization: Working time and work-life balance around the world', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'working-time evidence and sustainable scheduling context' },
    image: '/images/thumbnails/generated/shift-planning-for-philippines-based-assistants.webp',
  },
  {
    slug: 'identity-and-accountability-in-remote-assistant-access',
    published: '2026-08-12',
    title: 'Identity and accountability in remote assistant access',
    question: 'Which access evidence helps a business know who is using an account and what they are allowed to do?',
    finding: 'NIST Digital Identity Guidelines distinguish identity proofing, authentication, and authorization; those are separate questions and should not be collapsed into a shared password.',
    implication: 'A delegated role should use an identifiable account where possible, an authentication method appropriate to risk, and permissions tied to the specific work rather than to a person’s general trustworthiness.',
    source: { name: 'NIST: Digital Identity Guidelines', url: 'https://pages.nist.gov/800-63-3/', note: 'identity proofing, authentication, and authorization concepts' },
    image: '/images/thumbnails/generated/access-governance-for-delegated-operations.webp',
  },
  {
    slug: 'phishing-resilience-for-virtual-assistant-teams',
    published: '2026-08-12',
    title: 'Phishing resilience for virtual assistant teams',
    question: 'What makes a remote assistant team more resilient to suspicious messages and account takeover attempts?',
    finding: 'CISA’s small-business guidance emphasizes practical protections such as multifactor authentication, software updates, strong passwords, and recognizing phishing attempts.',
    implication: 'The staffing conversation should identify which messages require a pause, how suspicious requests reach the owner, and which account protections are in place before the assistant handles real customer or business records.',
    source: { name: 'CISA: Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'multifactor authentication, updates, passwords, and phishing awareness' },
    image: '/images/thumbnails/generated/secure-file-sharing-for-virtual-assistant-work.webp',
  },
  {
    slug: 'privacy-risk-questions-for-remote-assistant-roles',
    published: '2026-08-12',
    title: 'Privacy-risk questions for remote assistant roles',
    question: 'How can a small business identify privacy risk before delegating a new assistant role?',
    finding: 'The NIST Privacy Framework organizes privacy risk around identifying, governing, controlling, communicating, and protecting data-processing activities.',
    implication: 'Before recruiting for a sensitive lane, map whose information is involved, why it is used, where it moves, who can change it, and how a person can raise a privacy concern.',
    source: { name: 'NIST: Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy-risk identification and governance concepts' },
    image: '/images/thumbnails/generated/client-intake-workflow-design-for-remote-support.webp',
  },
  {
    slug: 'cybersecurity-risk-evidence-for-delegated-operations',
    published: '2026-08-12',
    title: 'Cybersecurity-risk evidence for delegated operations',
    question: 'What should a manager review before expanding a virtual assistant’s access to business systems?',
    finding: 'NIST Cybersecurity Framework 2.0 gives organizations a common language for understanding, managing, and communicating cybersecurity risk across governance, identification, protection, detection, response, and recovery.',
    implication: 'Expansion evidence should cover the system and information involved, the safeguards already active, the response owner for an incident, and the recovery path if access or records are compromised.',
    source: { name: 'NIST: Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'cybersecurity risk governance and response functions' },
    image: '/images/thumbnails/generated/risk-review-before-expanding-delegated-work.webp',
  },
  {
    slug: 'source-quality-for-assistant-prepared-research',
    published: '2026-08-12',
    title: 'Source quality for assistant-prepared research',
    question: 'What makes research prepared by a virtual assistant useful to a business decision-maker?',
    finding: 'A defensible research note distinguishes the authority of a source from the relevance of a claim and preserves enough context for another reader to check the conclusion.',
    implication: 'Evaluate a research sample by its question, source provenance, publication date, quoted scope, and unresolved limitations—not by the number of links collected.',
    source: { name: 'U.S. Government Publishing Office: Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public access to authoritative government information and source provenance' },
    image: '/images/thumbnails/generated/source-quality-in-assistant-prepared-briefs.webp',
  },
  {
    slug: 'continuity-evidence-for-remote-assistant-coverage',
    published: '2026-08-12',
    title: 'Continuity evidence for remote assistant coverage',
    question: 'How can a small team tell whether assistant coverage will survive an absence or handoff?',
    finding: 'CISA’s ransomware guidance stresses preparation, backups, and recovery planning because continuity depends on what can be restored and who knows how to respond.',
    implication: 'Assess coverage by asking whether a substitute can locate current records, understand the next decision, work with limited access, and escalate when the normal owner is unavailable.',
    source: { name: 'CISA: StopRansomware guide', url: 'https://www.cisa.gov/stopransomware', note: 'preparation, backup, response, and recovery guidance' },
    image: '/images/thumbnails/generated/backup-coverage-for-remote-assistant-teams.webp',
  },
  {
    slug: 'handoff-latency-in-distributed-assistant-support',
    published: '2026-08-12',
    title: 'Handoff latency in distributed assistant support',
    question: 'How should a business study delays between a Philippines-based assistant and the next decision-maker?',
    finding: 'Handoff delay is not simply a time-zone problem: it combines the moment work becomes blocked, the quality of the context sent forward, and the availability of the next owner.',
    implication: 'A useful sample records blocked time, missing context, escalation destination, and resolution—not just whether a task was eventually completed.',
    source: { name: 'U.S. Department of Labor: Hours worked', url: 'https://www.dol.gov/general/topic/workhours', note: 'working-time planning reference for evaluating scheduled coverage' },
    image: '/images/thumbnails/generated/handoff-reliability-in-distributed-teams.webp',
  },
] as const;

const makeAugust11ResearchPost = (spec: typeof august11ResearchSpecs[number], index: number): ResearchPost => ({
  slug: spec.slug,
  title: `Research note: ${spec.title}`,
  excerpt: `${spec.question} Evidence-led findings for businesses planning Philippines-based virtual assistant support.`,
  published: spec.published,
  methodology: `This article examines one decision question through the cited authoritative source and separates sourced guidance from the editorial interpretation. It does not claim a workforce statistic; the review criteria are proposed for a bounded staffing study.`,
  headlineStat: { value: '1', label: 'decision question kept in scope for this research note', source: 'Editorial scope statement for this article' },
  keyStats: [{ value: '1', label: 'authoritative source examined' }, { value: '4', label: 'evidence fields to review' }, { value: '0', label: 'unsupported workforce claims' }],
  takeaways: [spec.finding, spec.implication, 'Treat the conclusion as a research input for a role decision and revisit it when the work, information, or service expectation changes.'],
  sections: [
    { heading: 'What the source supports', body: spec.finding, table: [['Evidence field', 'Question to answer'], ['Authority', 'Who published the guidance and for what audience?'], ['Scope', 'Which claim or risk does it actually address?'], ['Limit', 'What does the source leave for the business to decide?']] },
    { heading: 'What the staffing decision still needs', body: spec.implication, table: [['Decision input', 'Record'], ['Work', 'The task and observable outcome'], ['Information', 'The minimum records or systems needed'], ['Ownership', 'The person who approves exceptions'], ['Review', 'The evidence that would change the decision']] },
    { heading: 'How to read a sample', body: `Use representative examples from the ${index % 2 === 0 ? 'first role discussion' : 'first task lane'} and compare them with the source-backed question above. Note what is known, what is inferred, and what requires owner or professional judgment. A sample is evidence for a decision, not proof that every future case will behave the same way.`, table: [['Result', 'Interpretation'], ['Supported', 'Keep the finding in the role brief'], ['Unclear', 'Collect a narrower example or ask the owner'], ['Outside scope', 'Pause and route the decision to the right authority']] },
  ],
  sourceNotes: `Source note: ${spec.source.name} is cited for the evidence boundary. The staffing implications are editorial analysis for OverseasVirtualAssistant.com and are not presented as measurements from the cited source.`,
  sources: [spec.source],
  internalLinks: ['/services/research-and-data-support', '/research'],
  faqs: [
    { question: 'Does this article measure assistant performance?', answer: 'No. It defines a way to examine one staffing decision and clearly separates the source’s guidance from proposed review criteria.' },
    { question: 'What should a business do with an ambiguous result?', answer: 'Keep the decision narrow, record the unresolved question, and ask the authorized owner or qualified professional before expanding the role.' },
    { question: 'Why is the Philippines context included?', answer: 'The service audience hires Philippines-based virtual assistants, so coverage, access, and handoff questions should be considered in that real service context without turning it into a workforce claim.' },
  ],
  relatedResearch: related(15 + index),
  image: { src: spec.image, alt: `Research illustration for ${spec.title}` },
  cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, and owner rules with our staffing team.',
});

export const researchPosts: ResearchPost[] = [...topicSpecs.map(([slug, title, cluster, thesis, publishedDate], index) => ({
  slug,
  title: `Research note: ${title}`,
  excerpt: `Evidence-led planning note on ${title.toLowerCase()} for teams building dependable Philippines-based support routines.`,
  published: publishedDate || (index < 15 ? '2026-08-08' : '2026-08-09'),
  methodology: `This note uses a structured review of ${sources.length} public primary and government sources, then translates the evidence into an operational pilot. The headline measure is a proposed acceptance criterion, not a claim about the workforce. Recheck source dates and applicable local requirements before implementation.`,
  headlineStat: { value: '100%', label: 'of pilot work items should have an owner disposition before the lane expands', source: 'Operational acceptance criterion defined for this research note' },
  keyStats: [
    { value: '10', label: 'authoritative sources reviewed' },
    { value: '3', label: 'review checkpoints in the pilot' },
    { value: '1', label: 'named owner for exceptions' },
  ],
  takeaways: [
    `Define ${cluster.toLowerCase()} as a visible routine with a trigger, inputs, output, and review owner.`,
    'Start with a reversible pilot and record completed, correct, blocked, and escalated work separately.',
    'Keep approvals, sensitive access, legal or financial commitments, and unusual exceptions with the authorized owner.',
  ],
  sections: [
    { heading: 'What the evidence supports', body: `${thesis} Across the source set, the common control is not a particular tool or geography; it is a clear owner, a bounded task, and a way to detect and correct exceptions.`, table: [['Evidence question', 'Practical answer'], ['Who decides?', 'Name the owner before work starts.'], ['What proves completion?', 'Define a reviewable output and acceptance rule.'], ['When should work stop?', 'Document the exception and escalation path.']] },
    { heading: 'A defensible pilot design', body: 'Use representative examples, minimum required access, a fixed review window, and a short batch size. Capture the input, action, result, reviewer decision, and any correction needed. Do not infer quality from hours online or activity counts alone.', table: [['Pilot field', 'Record'], ['Scope', 'One task lane and explicit exclusions'], ['Quality', 'Accepted, corrected, rejected, or pending'], ['Risk', 'Access used and exceptions escalated'], ['Decision', 'Continue, revise, or pause with rationale']] },
    { heading: 'How to operationalize the result', body: 'At the end of each review checkpoint, update the SOP only when the evidence shows a repeatable improvement. Preserve the previous instruction until the new version is tested. If the work touches personal data, payments, regulated advice, or customer commitments, obtain the appropriate owner or professional review before expanding the scope.', table: [['Checkpoint', 'Decision'], ['Launch', 'Can the worker explain the finish line?'], ['Review', 'Can the manager inspect representative output?'], ['Expand', 'Are exceptions understood and controlled?']] },
  ],
  sourceNotes: 'Source notes: government and standards-body guidance is used for control concepts; the operational thresholds above are proposed acceptance criteria for a local pilot and should not be presented as externally measured workforce statistics.',
  sources,
  internalLinks: ['/blog', '/services', '/contact'],
  faqs: [
    { question: 'Is this a staffing performance claim?', answer: 'No. The percentage and counts are proposed pilot controls unless a source is explicitly identified; they are not claims about an individual or a workforce.' },
    { question: 'What should happen when a source or requirement conflicts?', answer: 'Pause the affected item, record the conflict, and escalate it to the named owner or qualified adviser.' },
    { question: 'When is the routine ready to expand?', answer: 'Only after representative work is reviewable, exceptions have an owner, and the updated SOP has been tested.' },
  ],
  relatedResearch: related(index),
  image: { src: `/images/thumbnails/generated/${slug}.webp`, alt: `Research illustration for ${title}` },
  cta: 'Want this research translated into a scoped staffing routine? Share the task lane, tools, schedule, and owner rules with our staffing team.',
})), ...august11ResearchSpecs.map(makeAugust11ResearchPost)].sort((a, b) => b.published.localeCompare(a.published) || a.slug.localeCompare(b.slug));
