import type { ResearchPost } from './data';

const published = '2026-09-03';
const nist = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'risk context and governance' };
const cisa = { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'practical account-security guidance' };
const fdlp = { name: 'Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public-document provenance and access' };
const gao = { name: 'U.S. GAO Yellow Book', url: 'https://www.gao.gov/yellowbook', note: 'evidence sufficiency and appropriateness principles' };
const sba = { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'expectations and management responsibilities' };

export const september3ResearchPart1: ResearchPost[] = [
  {
    slug: 'source-change-sensitivity-in-daily-va-research', published,
    title: 'How should source-change sensitivity set recheck timing in daily VA research?',
    excerpt: 'A claim-level study of which evidence needs release-day verification and which can use a slower review cycle.',
    methodology: 'Research question: how should a Philippines-based virtual assistant set recheck timing for a source-backed article claim? This study compares NIST risk context, CISA security guidance, FDLP provenance practice, and a proposed change-sensitivity model. The unit is one claim-source pair. Evidence is classified by authority, expected change mechanism, reader consequence, and reversibility. Public-source principles are reported as facts; the timing matrix is analysis. The study does not estimate how often pages change, and it does not treat a recent access date as proof that a claim remains true.',
    headlineStat: { value: '4', label: 'change-sensitivity dimensions', source: 'Claim-source timing model' },
    keyStats: [{ value: '3', label: 'public authorities consulted' }, { value: '1', label: 'claim-source pair per unit' }, { value: '0', label: 'universal refresh intervals asserted' }],
    takeaways: ['Recheck timing should follow the mechanism and consequence of change, not draft age alone.', 'A working URL proves access, not continued support for a sentence.', 'The assistant records change signals; the editor makes the publication decision.'],
    sections: [
      { heading: 'The date on a source is only one signal', body: 'A daily article can combine stable definitions with details that change without warning. Treating every citation as equally fresh wastes review time and can still miss the risky claim. A definitions page may remain useful for years, while an eligibility rule, named office holder, security recommendation, or product instruction can become wrong between drafting and release. NIST frames risk decisions around context rather than one universal control. Applied to article research, context includes what could change, how a reader might act on the statement, and how difficult an error would be to reverse. A Philippines-based virtual assistant can record those properties while collecting evidence. The assistant should not invent a refresh interval because a template demands one. The useful output is a reasoned recheck class and the observable event that would move it. This keeps OverseasVirtualAssistant.com focused on defensible staffing and workflow guidance rather than unsupported claims of permanent accuracy.', table: [['Dimension', 'Question'], ['Authority', 'Is this the primary body for the statement?'], ['Mechanism', 'What event could make it stale?'], ['Consequence', 'What could a reader do if it is wrong?'], ['Reversibility', 'Can the error be corrected without lasting harm?'], ['Signal', 'What notice or change triggers review?']] },
      { heading: 'Name the mechanism instead of calling content evergreen', body: 'The researcher should name how a claim might change. A rule changes through an official process. Product documentation changes when the provider releases or removes a feature. A company description changes when the company alters its public offer. Security guidance may evolve after new threats or controls emerge. CISA publishes practical security material, but the presence of that guidance cannot prove that a business implemented a control. FDLP practice supports keeping public-document provenance visible, yet provenance does not guarantee permanence. These distinctions matter for an article about delegating research because a general authority may support a principle while the site adds its own operating analysis. The authority can remain stable even when the recommended handoff changes. Those layers need separate notes. Otherwise a reviewer may waste time repeatedly checking a stable principle while overlooking a local service description that has actually changed.', table: [['Mechanism', 'Useful trigger'], ['Scheduled publication', 'New edition or effective date'], ['Provider page', 'Revision notice or material page change'], ['Organizational fact', 'Primary-site confirmation near release'], ['General principle', 'Periodic scope review'], ['Local analysis', 'Workflow or service change']] },
      { heading: 'A release-day check needs a reproducible record', body: 'For a high-sensitivity claim, the assistant opens the primary source near release, reads the passage in context, records the access time, and compares the proposed sentence with the current wording. A screenshot alone is weak evidence when it hides qualifications or cannot be traced to a stable page. The record should state whether the result was unchanged, narrowed, replaced, unavailable, or escalated. If a source disappears, the safe response depends on the claim. A harmless background sentence may be removed. A central claim needs replacement evidence or a held release. The editor owns that choice. This division lets a remote research specialist perform careful retrieval without silently deciding the business’s public position. The record should also distinguish a page redesign from a substantive change. A moved paragraph can preserve the same meaning, while one altered condition can invalidate an otherwise familiar citation.', table: [['Result', 'Next action'], ['Unchanged', 'Retain with access record'], ['Narrower scope', 'Narrow claim and seek approval'], ['Conflicting update', 'Hold and compare authorities'], ['Unavailable', 'Replace, remove, or escalate'], ['Unclear meaning', 'Do not publish a confident paraphrase']] },
      { heading: 'Test the timing model on varied claims', body: 'A team can test the model on a bounded sample of recent work. Select claim-source pairs from different change mechanisms and ask a reviewer who did not prepare them to choose a recheck class using only the saved record. Compare disagreements, missed change signals, and unnecessary checks. Do not convert a small sample into a worker score or a claim that one interval is best for every topic. The useful finding is whether another person can understand why timing was chosen. If reviewers disagree because consequence is unclear, improve the brief. If they disagree because the source is secondary, improve provenance notes. The assistant can maintain the sample and report the observable disagreement. The owner approves any change to the release rule. A later review should ask whether the revised field solved the original ambiguity, not whether the team merely completed more checks.', table: [['Observation', 'Possible response'], ['Authority confusion', 'Require source-role classification'], ['Missed effective dates', 'Add an effective-date field'], ['Excess same-day checks', 'Separate low-consequence background'], ['Choice cannot be reproduced', 'Record mechanism and consequence'], ['Sensitive uncertainty', 'Escalate rather than average']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'No timing matrix predicts every source change. Pages can update without notices, archived material can remain accessible after it stops governing, and a primary source can still be ambiguous. The consulted authorities do not prescribe editorial refresh intervals for virtual-assistant articles. This analysis cannot prove improved rankings, faster production, fewer corrections, or better worker performance. It supports a bounded conclusion: recheck timing should be justified by the source’s change mechanism, the claim’s consequence, and the reversibility of error. For OverseasVirtualAssistant.com, a Philippines-based virtual assistant can prepare that evidence and carry out the approved check. An authorized editor still decides whether the statement is fit for publication. The model is successful only when it makes that decision easier to inspect and challenge without pretending to remove judgment.', table: [['Conclusion test', 'Pass condition'], ['Timing', 'Mechanism and consequence are named'], ['Traceability', 'Primary URL and scope are recorded'], ['Wording', 'Claim does not exceed current evidence'], ['Authority', 'Assistant prepares; editor approves']] },
    ],
    sourceNotes: 'Sources consulted: https://www.nist.gov/cyberframework; https://www.cisa.gov/secure-our-world; https://www.fdlp.gov/. The recheck matrix is editorial analysis, not a published standard.', sources: [nist, cisa, fdlp],
    faqs: [{ question: 'Does a recent access date prove a claim is current?', answer: 'No. It proves that someone reached a page. The reviewer must still confirm that the current passage supports the sentence.' }, { question: 'Who sets the final recheck rule?', answer: 'The assistant can classify change sensitivity. The editor or business owner approves the release rule.' }],
    relatedResearch: ['/research/evidence-age-in-daily-article-research', '/research/what-source-diversity-means-for-daily-va-research'], internalLinks: ['/services/research-and-data-support', '/research'], image: { src: '/images/research-sep3/source-change-sensitivity-in-daily-va-research.png', alt: 'Research assistant comparing source change signals before release' }, cta: 'Use this research to define a bounded source-verification lane for Philippines-based support.'
  },
  {
    slug: 'sampling-bias-in-virtual-assistant-research-review', published,
    title: 'When does sampling bias distort review of virtual-assistant research packets?',
    excerpt: 'A study of how packet selection can make a research workflow look stronger or weaker than the underlying queue.',
    methodology: 'Research question: when does selection distort a manager’s view of a Philippines-based assistant research workflow? This study draws on GAO evidence principles, NIST governance context, and SBA management guidance. The unit is a packet selected from a defined article queue. The analysis compares convenience, exception-only, time-window, risk-stratified, and random selection. It evaluates what each design can reveal, not the performance of a worker. The authorities inform evidence quality and management context; the sampling recommendations are local editorial analysis.',
    headlineStat: { value: '5', label: 'selection designs compared', source: 'Packet-sampling model' },
    keyStats: [{ value: '3', label: 'public authorities consulted' }, { value: '5', label: 'selection designs examined' }, { value: '0', label: 'worker rankings produced' }],
    takeaways: ['A clean sample can hide hard cases, while an exception-only sample can exaggerate failure.', 'The frame must name what was eligible before results are reviewed.', 'Managers should change workflow rules from inspectable evidence, not a memorable packet.'],
    sections: [
      { heading: 'The missing denominator changes the story', body: 'Review often begins with whatever is easiest to open: the latest polished draft, a packet that caused a complaint, or examples selected by the person presenting the work. Each can teach something, but none represents the queue unless the selection rule and eligible population are known. GAO guidance emphasizes evidence sufficiency and appropriateness in its audit context. That does not turn editorial review into an audit, but it supports asking whether evidence fits the conclusion. Three successful packets chosen from an unknown number cannot estimate routine consistency. Failures alone cannot estimate ordinary quality. A Philippines-based assistant can maintain the frame without deciding what result a manager should infer. For OverseasVirtualAssistant.com, the frame should stay connected to the daily article lane and should not grow into unnecessary monitoring of a person.', table: [['Selection', 'What it may reveal'], ['Convenience', 'Fast examples with high selection risk'], ['Exception-only', 'Failure mechanisms, not prevalence'], ['Time window', 'Work present during a stated period'], ['Stratified', 'Differences across defined claim classes'], ['Random', 'A less selective view of eligible packets']] },
      { heading: 'Define the packet before selecting it', body: 'A packet needs a stable unit. It might contain a reader question, source map, claim notes, limitations, and one requested editorial decision. Counting loose URLs as one packet and a complete brief as another creates comparisons that mean little. The frame should record route, family, completion state, risk class, reviewer, and date range only when those fields serve the research question. It should exclude personal detail that is not needed. SBA management guidance supports clear expectations, while NIST governance emphasizes context and responsibility. The manager defines the review question and the assistant compiles eligible records. Changing eligibility after seeing results should be recorded as a new analysis, not hidden in the first one. Missing records are a finding about the evidence system, not permission to swap in cleaner examples.', table: [['Frame field', 'Reason'], ['Unit definition', 'Keeps unlike artifacts separate'], ['Eligibility window', 'Shows which packets could be selected'], ['Completion state', 'Separates drafts from accepted work'], ['Risk class', 'Supports proportionate review'], ['Exclusion reason', 'Makes missing records visible']] },
      { heading: 'Different decisions require different designs', body: 'A random sample can support a broad process check when the frame is complete, but it may miss rare high-risk claims. A stratified sample deliberately includes categories such as privacy, security, company commitments, and stable background. It can compare how controls operate across categories, though it does not estimate the overall queue unless selection and weighting are handled carefully. An exception sample is useful for learning why work stopped. A time-window sample examines handoffs under the conditions present during that period. The manager should choose the design before reading packets and state the conclusion it can support. The assistant can apply the rule, preserve selected identifiers, and report missing material. They should not replace an inconvenient selected packet. A case review of one serious event may be valuable while supporting no claim about how often that event occurs.', table: [['Decision', 'Suitable design'], ['Find failure mechanisms', 'Exception sample'], ['Inspect current routine', 'Defined recent window'], ['Compare risk classes', 'Stratified sample'], ['Reduce chooser discretion', 'Random sample from complete frame'], ['Investigate one event', 'Case review without prevalence claim']] },
      { heading: 'Reviewer disagreement tests the instrument', body: 'Two reviewers can read the same packet differently because acceptance criteria are vague, evidence is genuinely ambiguous, or one reviewer knows context the packet omits. Record the reason before averaging scores. A disagreement about whether a source supports a claim is not equivalent to a preference about sentence rhythm. Use a small calibration set with visible rationales and inspect where decisions diverge. This tests the review instrument, not personal worth. The central question is whether the record supports a safe next editorial decision about Philippines-based research assistance. The owner may revise the rubric, request evidence, or narrow the lane. The assistant can document examples but should not resolve sensitive policy by majority vote. Consistent reviewer agreement can still be wrong if every reviewer relies on the same unsupported assumption.', table: [['Disagreement', 'Response'], ['Missing context', 'Improve required fields'], ['Evidence-scope dispute', 'Escalate to editor'], ['Style preference', 'Document house guidance'], ['Risk-class dispute', 'Clarify trigger definitions'], ['Selection breach', 'Replace sample transparently']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'Small samples remain uncertain, and even a sound design cannot reveal work that never entered the recorded queue. Reviewers may change behavior when they know work is sampled. The public authorities cited here do not validate a particular editorial score or universal sample size. The evidence supports a narrower conclusion: sampling bias becomes material when selection is related to the result while the review is presented as representative. A defensible review names the frame, unit, selection rule, exclusions, and permissible inference. A Philippines-based virtual assistant can assemble and trace the sample. The accountable manager decides what process change, if any, the evidence warrants. The review should end with that bounded decision, not with a claim that the sample proves overall worker quality or business performance.', table: [['Evidence-led test', 'Pass condition'], ['Frame', 'Eligible packets are known'], ['Selection', 'Rule is fixed and reproducible'], ['Inference', 'Conclusion matches design'], ['Privacy', 'Only necessary fields are retained'], ['Ownership', 'Manager approves process changes']] },
    ],
    sourceNotes: 'Sources consulted: https://www.gao.gov/yellowbook; https://www.nist.gov/cyberframework; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees. The sampling designs are editorial analysis.', sources: [gao, nist, sba],
    faqs: [{ question: 'Is an exception sample useless?', answer: 'No. It can reveal failure mechanisms, but it cannot show how common those failures are in the full queue.' }, { question: 'Can the sample become a worker score?', answer: 'This model evaluates workflow evidence and does not support ranking a person from a small or selective set.' }],
    relatedResearch: ['/research/sample-frame-design-for-virtual-assistant-research', '/research/content-quality-sampling-for-remote-va-teams'], internalLinks: ['/services/research-and-data-support', '/research'], image: { src: '/images/research-sep3/sampling-bias-in-virtual-assistant-research-review.png', alt: 'Reviewer selecting research packets from a defined article queue' }, cta: 'Use this research to scope an evidence-review routine with clear management ownership.'
  },
];
