import type { ResearchPost } from './data';
const published='2026-09-08';
const image={src:'/images/remote-onboarding.jpg',alt:'Remote research team reviewing article evidence and handoff notes'};
const gao={name:'U.S. GAO Yellow Book',url:'https://www.gao.gov/yellowbook',note:'principles for sufficient, appropriate evidence and documented judgment'};
const nist={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'governance, roles, risk context, and review principles'};
const cisa={name:'CISA Secure Our World',url:'https://www.cisa.gov/secure-our-world',note:'practical account and access security guidance'};
const ftc={name:'FTC Start with Security',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'data minimization and access-control guidance for businesses'};
const wcag={name:'Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/',note:'testable web accessibility criteria and conformance limits'};
type Spec={slug:string;title:string;excerpt:string;question:string;observation:string;method:string;limits:string;sources:typeof gao[]};
const specs:Spec[]=[
{slug:'brief-rejection-reasons-in-daily-va-writing-queues',title:'Which brief gaps cause returns in daily VA writing queues?',excerpt:'A bounded way to classify returned briefs without turning one queue into a workforce score.',question:'Which recorded brief fields are missing when an editor returns a daily article assignment before drafting?',observation:'Count the first stated reason for each return, then preserve secondary reasons separately. A category count describes the sampled queue, not the writer or every future assignment.',method:'Define eligible briefs and the observation window first. Code reader question, audience, evidence boundary, owner, deadline, and route identity as present, missing, or unclear. A second reviewer checks disputed codes.',limits:'The method cannot establish why a field was omitted, whether the editor was correct, or whether another team would return the same brief.',sources:[gao,nist]},
{slug:'review-window-fit-for-overnight-article-handoffs',title:'Do review windows fit overnight article handoffs?',excerpt:'A queue study that separates writing completion from reviewer availability and decision delay.',question:'How often does a completed overnight draft reach a named reviewer within its planned review window?',observation:'Measure draft-ready time, planned window, first reviewer action, and disposition as separate events. Waiting time alone does not reveal whether the draft was ready or the reviewer was available.',method:'Sample one dated queue. Use system timestamps where available and label manual timestamps. Report scheduled waits, missed windows, and unresolved records without combining them.',limits:'This is a process-timing study. It does not measure article quality, individual productivity, fatigue, or the cause of a missed window.',sources:[gao,nist]},
{slug:'alt-text-context-errors-in-reused-editorial-images',title:'What context errors appear in alt text for reused article images?',excerpt:'A page-level inspection of approved assets whose descriptions may not fit their new editorial context.',question:'When an approved image is reused, does its rendered alt text describe the visible subject and its purpose on the current page?',observation:'Asset approval and contextual description answer different questions. Inspect the rendered page, because an inventory label may be accurate for the file but unhelpful beside a particular article.',method:'List the dated pages that reuse inventory images. Two reviewers compare visible content, nearby copy, alt text, and repeated descriptions. Record agreement and retain disputed cases.',limits:'The inspection is not a full accessibility audit, legal opinion, or user study. Results apply only to the pages, viewport, and assistive checks observed.',sources:[wcag,gao]},
{slug:'source-access-failures-before-va-article-drafting',title:'How should source-access failures be measured before VA drafting?',excerpt:'A reproducible distinction between broken transport, restricted access, and evidence that no longer supports the assignment.',question:'Which assigned sources can a remote researcher open, read in context, and connect to the intended claim before drafting begins?',observation:'A 200 response is only one state. The record should distinguish redirects, blocked access, missing passages, changed scope, and a page that remains usable.',method:'Test each assigned URL from the defined work environment, record the response and access result, then compare the relevant passage with the intended claim. The editor decides whether a substitute is acceptable.',limits:'A single check is time-bound. It does not prove source truth, permanence, global availability, or suitability for claims outside the stated assignment.',sources:[gao,cisa,ftc]},
{slug:'live-route-evidence-decay-after-daily-publication',title:'How quickly can live-route evidence become stale after publication?',excerpt:'A repeat-check design for article routes, metadata, discovery surfaces, and images after a successful release.',question:'Do the same article-release gates still pass at a defined follow-up time after the initial production audit?',observation:'A launch audit is a timestamped observation, not permanent proof. Repeat checks can locate later changes in routing, caching, indexes, structured metadata, or asset delivery.',method:'Freeze the route list and expected values at release. Repeat direct HTTP, visible date, datePublished, self-canonical, family index, sitemap, hero image, and OG image checks at a stated interval. Compare gate by gate.',limits:'The study detects observed state changes but may not identify their cause. Passing checks cannot prove availability between observations or on every network and device.',sources:[gao,nist,cisa]},
];
export const september8ResearchPosts:ResearchPost[]=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published,methodology:`Research question: ${s.question} Scope: one explicitly dated article queue, source set, or production route set. ${s.method} The cited guidance informs evidence, governance, security, or accessibility criteria. The workflow and interpretation are ours.`,headlineStat:{value:'1',label:'bounded unit of analysis',source:'Article methodology'},keyStats:[{value:String(s.sources.length),label:'public standards or guidance sources consulted'},{value:'1',label:'defined research question'},{value:'0',label:'worker-performance conclusions'}],takeaways:[s.observation,s.method,s.limits],sections:[{heading:'Question and scope',body:`${s.question} The unit of analysis is limited to the stated dated set.`,table:[['Field','Recorded boundary'],['Family','Research'],['Publication date',published],['Generalization','None beyond the observed set']]},{heading:'Method',body:s.method,table:[['Record','Keep'],['Input','Original request or expected state'],['Observation','What the check returned'],['Decision','Named reviewer disposition']]},{heading:'Interpretation',body:s.observation,table:[['Evidence layer','Reading rule'],['Observed','Report directly'],['Inferred','Label and bound'],['Unknown','Leave unresolved']]},{heading:'Limitations',body:s.limits,table:[['Constraint','Effect'],['Time','Results describe the observation window'],['Sample','No population estimate'],['Authority','Editors retain publication decisions']]},{heading:'Operational use',body:'A Philippines-based assistant can assemble records and reproduce checks. The editor reviews disputed evidence and owns public wording. Sensitive exceptions go to the authorized specialist.',table:[['Role','Responsibility'],['Assistant','Prepare and flag'],['Editor','Interpret and accept'],['Specialist','Decide within protected domains']]}],sourceNotes:`Sources consulted: ${s.sources.map(x=>x.url).join('; ')}. These sources do not endorse OverseasVirtualAssistant.com, and none supplies results for the proposed local study.`,sources:s.sources,internalLinks:['/research','/blog','/services/research-and-data-support'],faqs:[{question:'Does this study score virtual assistants?',answer:'No. It examines a bounded record, source set, or production condition.'},{question:'Can these findings be generalized?',answer:'No. Report them within the stated sample, date, method, and limitations.'}],relatedResearch:['/research/production-proof-completeness-for-daily-article-campaigns'],image,cta:'Apply the method to one dated set and keep contrary or unresolved results in the record.'}));
