import type { ResearchPost } from './data';

const published = '2026-09-03';
const nist = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'risk context and governance' };
const privacy = { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'privacy-risk and data-processing context' };
const ftc = { name: 'FTC Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'data minimization and access discipline' };
const cisa = { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'practical account-security guidance' };
const fdlp = { name: 'Federal Depository Library Program', url: 'https://www.fdlp.gov/', note: 'public-document provenance and access' };
const sba = { name: 'U.S. Small Business Administration: Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'expectations and management responsibilities' };
const ilo = { name: 'ILO: Working time and work-life balance around the world', url: 'https://www.ilo.org/publications/working-time-and-work-life-balance-around-world', note: 'working-time context and schedule limits' };
const links = ['/services/research-and-data-support', '/research'];

export const september3ResearchPart2: ResearchPost[] = [
  {
    slug: 'resolving-conflicting-sources-in-va-article-research', published,
    title: 'How should a virtual assistant handle conflicting sources in article research?',
    excerpt: 'A conflict-resolution study that separates different scopes, dates, and definitions before an editor chooses public wording.',
    methodology: 'Research question: how should a Philippines-based virtual assistant prepare a conflict between reputable sources for editorial decision? The method compares FDLP provenance practice, NIST context-based risk guidance, FTC business guidance, and a claim-conflict record. The unit is one proposed sentence supported by two or more apparently inconsistent passages. Conflicts are classified by authority, jurisdiction, date, population, definition, and recommendation strength. The study does not decide legal meaning or declare one institution universally superior. Source statements are separated from the resolution method, which is local analysis.',
    headlineStat: { value: '6', label: 'conflict dimensions checked', source: 'Claim-conflict record' },
    keyStats: [{ value: '3', label: 'public authorities consulted' }, { value: '1', label: 'proposed sentence per unit' }, { value: '0', label: 'conflicts resolved by link count' }],
    takeaways: ['Many apparent contradictions disappear when scope, date, and definitions are aligned.', 'Authority depends on the claim, not the prestige of a domain alone.', 'The assistant prepares the comparison; the editor owns interpretation and publication.'],
    sections: [
      { heading: 'Do not smooth over disagreement in the draft', body: 'A researcher under deadline may combine two sources into a vague sentence that neither supports. That hides the useful finding: the evidence does not yet point in one direction. The assistant should preserve the proposed claim, relevant passages in paraphrase, URLs, effective dates, and the reason they appear inconsistent. FDLP’s public-information mission supports traceable provenance. NIST adds a context lens. Neither says that more citations settle a dispute. For an article about overseas virtual-assistant operations, one source may address cybersecurity while another addresses privacy or employment management. Recommendations can differ because the underlying questions differ. The first task is comparison, not compromise. A clean-looking paragraph is not an acceptable substitute for a clear record of unresolved evidence.', table: [['Field', 'Question'], ['Authority', 'Which body speaks directly to this claim?'], ['Jurisdiction', 'Where does it apply?'], ['Date', 'Did one source replace an older position?'], ['Population', 'Who or what is covered?'], ['Definition', 'Are terms used the same way?'], ['Strength', 'Requirement, recommendation, or example?']] },
      { heading: 'Separate apparent conflict from genuine disagreement', body: 'An apparent conflict occurs when sources answer different questions or use different boundaries. A security page may recommend an account safeguard, while privacy guidance asks whether the business should collect the information at all. Both can be true. A date conflict may show that one page is obsolete. A definition conflict can arise when employee, contractor, user, or administrator has a specific meaning. Genuine disagreement remains after those dimensions are aligned. The record should name the type and retain enough context for an authorized reviewer to inspect the source. The assistant should avoid legal interpretation, country-level assumptions, or claims about a particular worker. If the article does not need the disputed sentence, removal may be more honest than forced resolution. If it does need the point, the draft should wait for an accountable decision.', table: [['Type', 'Treatment'], ['Different question', 'Split the claims'], ['Different scope', 'State each boundary'], ['Superseded source', 'Use current authority'], ['Different definition', 'Define or avoid the term'], ['Genuine disagreement', 'Attribute, narrow, or hold']] },
      { heading: 'Authority is specific to the claim', body: 'A primary source is not automatically primary for every statement on its page. An agency may be authoritative about its own program but not about a business’s staffing result. A vendor can describe a feature but cannot independently establish that the feature improves security in every setting. FTC guidance supports minimizing unnecessary information, yet it cannot establish that OverseasVirtualAssistant.com or a client has implemented a particular control. The conflict record should include an authority sentence: this source can establish one fact within a stated scope, but it cannot establish the proposed extension. Writing that sentence exposes weak leaps before publication. A Philippines-based research assistant can prepare it and flag uncertainty. An editor or qualified specialist makes the final interpretation when the stakes involve legal, security, financial, or employment meaning.', table: [['Role', 'Safe use'], ['Rule owner', 'Current rule in stated jurisdiction'], ['Product owner', 'Feature behavior'], ['Independent authority', 'Principle within its mandate'], ['Secondary explanation', 'Context with traceable origin'], ['Local analysis', 'Clearly labeled recommendation']] },
      { heading: 'Give the editor bounded options', body: 'An escalation that says only that sources disagree creates more work than it transfers. A useful packet offers bounded options. The editor might attribute both positions, narrow the sentence to shared ground, select the source with direct authority, remove the claim, or request specialist review. Each option should state what the article gains and what remains unresolved. The assistant should not recommend the most dramatic option merely to appear cautious. A low-consequence background detail may be omitted. A conflict affecting access, a company commitment, or regulated advice may require a held release. The packet records the decision and final wording so the same issue is not rediscovered without context in the next daily article. That history is decision evidence, not proof that one source was permanently right.', table: [['Option', 'Consequence'], ['Attribute both', 'Preserves disagreement'], ['Use shared ground', 'Reduces specificity'], ['Prefer authority', 'Needs a rationale'], ['Remove claim', 'Avoids unsupported meaning'], ['Specialist review', 'Adds time and preserves ownership']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'This method cannot eliminate judgment. Authorities may remain ambiguous, primary pages can conflict internally, and the public web may not contain evidence for a company-specific question. The cited sources do not validate a universal hierarchy for editorial disputes. The evidence supports a practical conclusion: a virtual assistant should not resolve conflict by counting links or blending incompatible passages. They should align scope, date, definition, and authority, record what remains, and return clear options to the authorized editor. That keeps the research lane useful while preserving accountability for public claims about Philippines-based staffing and daily article work. A successful resolution is one whose reasoning can be inspected later, not one that hides uncertainty behind confident prose.', table: [['Test', 'Pass condition'], ['Visibility', 'No blended unsupported sentence'], ['Reproducibility', 'Passages, dates, and scopes are traceable'], ['Options', 'Consequences and unknowns are stated'], ['Ownership', 'Editor approves final meaning']] },
    ],
    sourceNotes: 'Sources consulted: https://www.fdlp.gov/; https://www.nist.gov/cyberframework; https://www.ftc.gov/business-guidance/resources/start-security-guide-business. The conflict record is editorial analysis.', sources: [fdlp, nist, ftc], internalLinks: links,
    faqs: [{ question: 'Should the newest source always win?', answer: 'No. Recency matters after authority, scope, definitions, and whether newer material supersedes the older source are checked.' }, { question: 'Can an assistant choose the company’s public position?', answer: 'The assistant prepares evidence and options. An authorized editor or specialist retains that decision.' }], relatedResearch: ['/research/what-source-diversity-means-for-daily-va-research', '/research/when-to-escalate-uncertain-claims-in-va-article-research'], image: { src: '/images/research-sep3/resolving-conflicting-sources-in-va-article-research.png', alt: 'Remote researcher comparing conflicting source scopes for an article claim' }, cta: 'Use this study to define a conflict-escalation lane for remote research support.'
  },
  {
    slug: 'context-loss-in-asynchronous-va-research-questions', published,
    title: 'What evidence shows context loss in asynchronous VA research questions?',
    excerpt: 'A study of observable handoff defects that distinguishes missing task context from ordinary response delay across time zones.',
    methodology: 'Research question: what evidence can show that an asynchronous research question lost necessary context between a manager and a Philippines-based virtual assistant? The study compares ILO working-time context, SBA expectation-setting guidance, NIST governance principles, and a handoff-event model. The unit is one question sent for an editorial decision. Records include the initiating claim, requested decision, attachments, owner, timestamp, response, and reopen reason. The study does not infer attention, effort, or availability from elapsed time. Public guidance informs boundaries; the defect taxonomy is operational analysis.',
    headlineStat: { value: '7', label: 'handoff fields observed', source: 'Asynchronous question event model' },
    keyStats: [{ value: '3', label: 'public authorities consulted' }, { value: '1', label: 'question event per unit' }, { value: '0', label: 'personal causes inferred' }],
    takeaways: ['Delay and context loss are different conditions and need different evidence.', 'A question is usable when the next owner can decide without reconstructing hidden conversation.', 'Time-zone data should shape fallback design, not judgments about a person.'],
    sections: [
      { heading: 'A timestamp cannot explain a failed handoff', body: 'A question sent at the end of one person’s day may wait until another person starts work. That is schedule latency, not evidence that context was lost. Context loss appears when the receiver cannot identify the article, claim, source, requested decision, or consequence from the available packet. ILO research provides broad working-time context but does not establish a fair or productive schedule for a particular person. SBA guidance supports setting expectations, and NIST governance supports clear responsibility. Together they justify examining the work interface without inventing a personal cause. OverseasVirtualAssistant.com can use these principles to design research handoffs while avoiding claims that a Philippines-based assistant was inattentive, unavailable, or slow based on timestamps alone. The missing information, rather than an assumed motive, is the proper unit of analysis.', table: [['Event', 'What it can show'], ['Sent time', 'When the question entered the channel'], ['Planned shift', 'Expected review opportunity'], ['Clarification', 'Which field was missing'], ['Reopen', 'The first response did not settle the decision'], ['Elapsed time', 'Duration, not cause']] },
      { heading: 'The requested decision is the center of the packet', body: 'Many handoffs contain background but never state what the receiver may decide. Please review could mean check citations, approve an angle, rewrite a claim, or publish a page. The packet should identify the exact version and route, reproduce the disputed sentence, link the evidence, state the options, name the owner, and explain what can continue while waiting. A remote assistant can assemble this material when escalating uncertainty. The manager must define authority before the issue crosses time zones. If the answer depends on a private thread or memory held by one person, the workflow record is incomplete. The fix is to move necessary work context into an approved system, not expand access to every conversation. The packet should be small enough to read but complete enough to support the named choice.', table: [['Field', 'Value'], ['Article identity', 'Prevents wrong-version review'], ['Exact claim', 'Keeps the question bounded'], ['Evidence', 'Allows inspection'], ['Decision', 'Defines the response'], ['Fallback', 'Keeps safe work moving'], ['Owner', 'Shows who can close it']] },
      { heading: 'Classify the reopen reason before changing the process', body: 'A reopened question may reflect missing evidence, an undefined term, changed requirements, an answer that exceeded authority, or a preference that was never documented. These causes need different responses. Missing evidence calls for a stronger source packet. Changed requirements call for a new version and scope record. An authority breach calls for a clearer stop condition. A recurring preference may belong in editorial guidance. The assistant can tag the observable reason and attach examples, but the owner should confirm the classification. Avoid a catch-all communication problem label. It hides whether the sender, receiver, tool, brief, or decision rule needs attention and invites unsupported conclusions about people. A reopen can also be appropriate when new evidence arrives, so it should not automatically be counted as a defect.', table: [['Reason', 'Response'], ['Missing source context', 'Add claim-level evidence'], ['Undefined decision', 'Name options and authority'], ['Requirement changed', 'Create a new version'], ['Exceeded scope', 'Clarify stop condition'], ['Undocumented preference', 'Decide whether to add guidance']] },
      { heading: 'Test the handoff with a bounded event study', body: 'Select a defined window of asynchronous questions and retain only fields needed for the workflow question. Ask whether an authorized receiver could choose the next action from the initial packet. Count clarification categories, not alleged personal causes. Compare cases that closed in one exchange with cases that reopened, while noting differences in risk and complexity. A legal or security question should not be compared casually with a headline preference. The result may support one experiment: adding an exact-claim field, requiring a fallback action, or naming the owner earlier. It cannot prove that the change improved worker performance. Review the experiment after another bounded period and preserve the old rule long enough to explain what changed. A useful result makes a handoff more interpretable, not merely longer.', table: [['Element', 'Boundary'], ['Window', 'Defined dates, not anecdotes'], ['Unit', 'One question and decision trail'], ['Outcome', 'Closed, clarified, escalated, or reopened'], ['Context', 'Risk and complexity recorded'], ['Inference', 'Workflow usability, not personal quality']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'Written records omit tone, informal calls, and context that people remember but never save. A complete packet can wait because the authorized owner is unavailable, and a fast answer can still be wrong. The sources do not establish a universal response-time target or prove asynchronous work is superior. The evidence supports a limited conclusion: context loss is shown by missing decision-relevant information and repeated reconstruction, not elapsed time alone. A Philippines-based virtual assistant can prepare the question record, classify observable reopen reasons, and follow an approved fallback. The manager owns schedule design, authority, and any conclusion about changing the routine. The evidence should improve the interface between roles without becoming surveillance or a disguised judgment about personal commitment.', table: [['Close', 'Pass condition'], ['Delay', 'No cause inferred from timestamps'], ['Context', 'Decision fields are present'], ['Reopens', 'Observable reason is recorded'], ['Boundary', 'Manager approves schedule and process changes']] },
    ],
    sourceNotes: 'Sources consulted: https://www.ilo.org/publications/working-time-and-work-life-balance-around-world; https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees; https://www.nist.gov/cyberframework. The event model is operational analysis.', sources: [ilo, sba, nist], internalLinks: links,
    faqs: [{ question: 'Does a slow response prove context loss?', answer: 'No. Context loss concerns missing decision information. Delay can have causes that a timestamp does not establish.' }, { question: 'What can the assistant own?', answer: 'The assistant prepares the packet, records events, and follows the fallback. The manager owns authority and schedule decisions.' }], relatedResearch: ['/research/handoff-context-loss-in-daily-virtual-assistant-research', '/research/how-working-time-context-changes-daily-article-research'], image: { src: '/images/research-sep3/context-loss-in-asynchronous-va-research-questions.png', alt: 'Research question packet crossing an asynchronous time-zone handoff' }, cta: 'Use this evidence model to define a clearer asynchronous research handoff.'
  },
  {
    slug: 'least-privilege-evidence-collection-for-va-research', published,
    title: 'How much access does a virtual assistant need to collect article evidence?',
    excerpt: 'A least-privilege study that starts with claim requirements and separates public research from restricted business records.',
    methodology: 'Research question: how much access does a Philippines-based virtual assistant need to collect evidence for a daily article? The study compares FTC data-minimization guidance, the NIST Privacy Framework, CISA account-security guidance, and a task-to-evidence map. The unit is one evidence requirement for one approved claim. The analysis records source location, sensitivity, minimum action, duration, output, and revocation owner. It does not certify security or privacy compliance and does not authorize customer, employee, financial, medical, or credential data. Source principles are distinguished from the proposed workflow.',
    headlineStat: { value: '6', label: 'access-map fields', source: 'Task-to-evidence model' },
    keyStats: [{ value: '3', label: 'public authorities consulted' }, { value: '1', label: 'claim requirement per unit' }, { value: '0', label: 'blanket grants recommended' }],
    takeaways: ['Start with the approved claim before choosing a system permission.', 'Read, export, edit, approve, and publish are different capabilities.', 'Restricted evidence should be excluded or escalated unless an owner creates a controlled lane.'],
    sections: [
      { heading: 'Research access begins with the public claim', body: 'A broad request to research operations does not define a safe permission. The manager should state the public question and the evidence allowed to answer it. Many articles about hiring or managing virtual assistants can rely on public authorities, approved service descriptions, and sanitized process examples. They do not require inboxes, customer records, billing systems, or analytics exports. FTC guidance advises businesses to know what information they hold and keep only what they need. The NIST Privacy Framework treats data processing as a risk-management question. Applied here, the assistant should receive the smallest source set and action needed for the claim. This is an operating principle, not a compliance conclusion. The article brief should record excluded evidence so the researcher does not mistake missing access for an invitation to request everything.', table: [['Claim need', 'Evidence lane'], ['Public definition', 'Primary public authority'], ['Service description', 'Approved public site material'], ['Process example', 'Sanitized owner-approved record'], ['Customer outcome', 'Exclude unless separately authorized'], ['Regulated advice', 'Route to qualified owner']] },
      { heading: 'Capability matters as much as the system name', body: 'Access to one platform can include very different actions. A researcher may need to view an approved document but not search every folder, download a workspace, edit the source, invite users, or publish externally. CISA guidance supports strong authentication and safe account handling, but it does not define a company role. The map should state the exact object, permitted action, duration, and output. Shared credentials should not appear in research notes. When an account is required, the business should provision and revoke it under its policy. A Philippines-based assistant can report missing or excessive access. They should not work around controls with personal accounts or copied data. A permission that is technically read-only can still expose more information than the task needs, so object scope remains part of the decision.', table: [['Capability', 'Decision'], ['Discover', 'Can the assistant locate the object?'], ['Read', 'Can they view only approved content?'], ['Export', 'May data leave the system?'], ['Edit', 'Can the source change?'], ['Approve', 'Can a decision be accepted?'], ['Publish', 'Can content become public?']] },
      { heading: 'Restricted evidence should change the question', body: 'Sometimes a proposed claim appears to require private evidence. Before granting access, ask whether the public article needs the claim. A general guide can explain a control without publishing internal configurations. A staffing article can describe role boundaries without exposing candidate or employee records. A process study can use a sanitized example rather than a customer conversation. If a claim depends on confidential facts, the owner may remove it, rewrite it as a hypothetical, prepare an approved aggregate, or establish a separately reviewed lane. The assistant should not anonymize sensitive records alone and assume the result is safe. De-identification, privilege, contractual duties, and regulated data can require specialist judgment. For OverseasVirtualAssistant.com, useful specificity must not come at the cost of inventing or exposing company facts.', table: [['Situation', 'Owner decision'], ['Claim unnecessary', 'Remove it'], ['Principle sufficient', 'Use public authority'], ['Sanitized example possible', 'Approve the artifact'], ['Aggregate proposed', 'Review disclosure risk'], ['Specialist meaning required', 'Escalate before collection']] },
      { heading: 'Access needs a verifiable close', body: 'A time-limited research lane needs an end condition. At handoff, the assistant returns evidence to the approved workspace, links the current record, identifies any exported copy, and reports unexpected permissions. The owner confirms retention and revocation under business policy. Deleting evidence prematurely can break traceability, while retaining every intermediate copy increases exposure. The correct balance depends on the source, claim, and obligations. The research record should avoid passwords, recovery codes, unnecessary personal information, and internal security details. Review access again when the topic changes. Yesterday’s permission for public source review does not automatically fit a new article involving private operational data. Closure is part of the work definition, not cleanup that can be left to an unnamed person.', table: [['Close field', 'Question'], ['Output', 'Is evidence in the approved workspace?'], ['Copies', 'Were temporary files handled under policy?'], ['Excess access', 'Was it reported?'], ['Retention', 'Who decides what remains?'], ['Revocation', 'Who closes time-limited access?']] },
      { heading: 'Limitations and evidence-led conclusion', body: 'This article is not a security architecture, privacy assessment, or legal opinion. The cited authorities provide general principles, not a permission set for a particular client or tool. Least privilege can fail if the task is poorly defined or if a narrow account exposes sensitive information through search, previews, or exports. The evidence supports a bounded conclusion: access for article research should be derived from one approved claim and evidence requirement, separated by capability, limited in time, and closed through an accountable owner. A Philippines-based virtual assistant can collect public and explicitly approved evidence within that map. Sensitive access and publication authority remain with the business and qualified decision makers. The goal is an inspectable relationship between the claim and permission, not a claim that limited access removes every risk.', table: [['Condition', 'Pass test'], ['Necessity', 'Access maps to an approved claim'], ['Capability', 'Actions are separated'], ['Sensitivity', 'Restricted evidence is excluded or authorized'], ['Closure', 'Retention and revocation are owned'], ['Honesty', 'No compliance result is claimed']] },
    ],
    sourceNotes: 'Sources consulted: https://www.ftc.gov/business-guidance/resources/start-security-guide-business; https://www.nist.gov/privacy-framework; https://www.cisa.gov/secure-our-world. The access map is operational analysis, not a compliance determination.', sources: [ftc, privacy, cisa], internalLinks: links,
    faqs: [{ question: 'Does research access include publishing access?', answer: 'No. Reading evidence, editing a draft, approving claims, and publishing require separate authorization.' }, { question: 'Should an assistant anonymize private records?', answer: 'Not without an approved method and owner. The safer choice may be removing the claim or using public evidence.' }], relatedResearch: ['/research/privacy-boundaries-in-virtual-assistant-research-notes', '/research/overseas-virtual-assistant-access-governance-research'], image: { src: '/images/research-sep3/least-privilege-evidence-collection-for-va-research.png', alt: 'Access map limiting a virtual assistant research task to approved evidence' }, cta: 'Use this study to scope a research role around necessary evidence and explicit permissions.'
  },
];
