import type { ResearchPost } from './data';

const published = '2026-09-28';
const checked = 'September 28, 2026';
const image = { src: '/images/remote-onboarding.jpg', alt: 'A Philippines-based virtual assistant and business owner reviewing a bounded administrative workflow' };
type Source = { name: string; url: string; note: string };
type Spec = {
  slug: string; title: string; excerpt: string; service: string; serviceName: string;
  question: string; unit: string; assistant: string; owner: string; sample: string;
  facts: string; analysis: string; exceptions: string; measures: string; conclusion: string;
  sources: Source[]; related: string[];
};
const source = (name: string, url: string, note: string): Source => ({ name, url, note: `${note}; checked ${checked}` });
const nist = source('NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework', 'primary risk-governance framework');
const ftcData = source('FTC — Protecting Personal Information: A Guide for Business', 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', 'official data minimization and security guidance');

const specs: Spec[] = [
  {
    slug: 'payroll-time-record-preparation-boundary-study',
    title: 'Can a bookkeeping virtual assistant prepare payroll time records without making pay decisions?',
    excerpt: 'A pay-period study separating record reconciliation from worker classification, wage calculations, tax judgment, and payment authority.',
    service: '/services/travel-and-expense-support', serviceName: 'Travel and Expense Support',
    question: 'Can a Philippines-based assistant reconcile owner-approved time and leave records into a review packet while payroll, classification, wage, tax, and payment decisions remain with authorized owners?',
    unit: 'one pay-period packet linked to named workers, approved time sources, recorded edits, exceptions, reviewer disposition, payroll output, and retained evidence',
    assistant: 'collect records from approved systems, compare totals and identifiers against a written checklist, identify missing or conflicting entries, prepare a clearly marked draft, and preserve every reviewer correction',
    owner: 'The employer, payroll administrator, and qualified accounting, tax, legal, or human-resources owners retain worker classification, compensable-time rules, overtime decisions, deductions, leave eligibility, wage rates, tax treatment, payment release, and employee communications.',
    sample: 'Test consecutive synthetic or properly authorized pay periods containing an ordinary hourly record, salaried worker, approved leave, overnight shift crossing midnight, corrected punch, travel time, bonus, expense reimbursement, contractor invoice, terminated worker, duplicate identifier, and missing approval. Freeze the source-system exports, pay-period boundary, time zone, roster, and checklist before preparation. The sample must retain incomplete and disputed units; removing them after review would hide the cases most likely to transfer judgment to the preparer.',
    facts: 'The U.S. Department of Labor explains that covered employers must keep specified wage-and-hour records, including identifying information and data about hours and wages, while not prescribing one required record form. DOL Fact Sheet 21 lists records required under the Fair Labor Standards Act and explains that payroll records generally must be preserved for at least three years, with certain supporting wage-computation records preserved for two years. IRS Publication 15 describes federal employment-tax responsibilities, deposit rules, and employer records, and the IRS recordkeeping page states that businesses may choose a record system that clearly shows income and expenses. These sources establish employer duties and record categories. They do not decide a worker’s status, whether particular time is compensable, a wage rate, a deduction, or a tax result for a specific business.',
    analysis: 'A reliable preparation lane begins with provenance, not a spreadsheet total. Each row should identify the worker record, pay period, source system, source timestamp, owner-approved rate reference, submitted hours, approved leave, and unresolved exception. A correction should never overwrite the submitted state without an audit trail. Overnight work requires an explicit business time zone and pay-period cutoff; otherwise the same shift can appear in different periods. Expense reimbursements and contractor invoices need separate categories because their presence in an intake queue does not make them wages. The assistant may compare arithmetic produced by approved rules, but a mismatch should return to the payroll owner rather than be “fixed” through an inferred rate or classification. Final payroll reports must be reconciled to the reviewed packet without exposing bank, tax, or personal data beyond the approved need. A clean total only proves internal arithmetic, not legal compliance, employee consent, tax accuracy, or successful payment.',
    exceptions: 'Off-the-clock allegations, disputed breaks, overtime, travel or waiting time, retroactive rate changes, garnishments, benefit deductions, protected leave, final pay, terminated staff, minors, multiple jurisdictions, union terms, contractor classification, tax notices, identity mismatches, bank changes, and requests to alter source time require an authorized payroll, HR, legal, tax, or security owner. The assistant should not tell a worker what they are owed, classify a person, invent an approval, change a time record to reach a budget, upload bank instructions, release payroll, or treat silence as acceptance. A suspected account takeover or diverted direct deposit is a security incident, not a routine data correction.',
    measures: 'Report packets eligible for preparation, source records present, unresolved time exceptions, duplicate identifiers stopped, arithmetic differences, owner corrections by field, late approvals, excess-data exposures, final-output mismatches, and packets released only after named approval. Use the pay-period packet as the denominator and show pending cases separately. Track corrections to hours, rates, classifications, deductions, and identity as different categories because their risks are not interchangeable. Preparation time may help capacity planning, but speed cannot show that wages were lawful, taxes accurate, classifications correct, or payments received.',
    conclusion: 'Payroll support is delegable as traceable record collection, arithmetic comparison, exception logging, and draft-packet preparation. Employment, wage, tax, deduction, identity, and money-movement decisions must remain with authorized owners.',
    sources: [source('U.S. Department of Labor — Recordkeeping and Reporting', 'https://www.dol.gov/agencies/whd/flsa/recordkeeping', 'official FLSA recordkeeping overview'), source('U.S. Department of Labor — Fact Sheet #21', 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping', 'official wage-and-hour record summary'), source('IRS Publication 15', 'https://www.irs.gov/publications/p15', 'official employer tax guide'), source('IRS — What kind of records should I keep?', 'https://www.irs.gov/businesses/small-businesses-self-employed/what-kind-of-records-should-i-keep', 'official business recordkeeping guidance'), nist, ftcData],
    related: ['/research/business-travel-receipt-expense-preparation-study', '/research/invoice-draft-review-boundaries', '/research/identity-and-accountability-in-remote-assistant-access']
  },
  {
    slug: 'crm-marketing-consent-suppression-study',
    title: 'Can a CRM virtual assistant maintain marketing consent and suppression records without authorizing outreach?',
    excerpt: 'A contact-event study of provenance, unsubscribe handling, channel boundaries, and campaign approval.',
    service: '/services/research-and-data-support', serviceName: 'Research and Data Support',
    question: 'Can each proposed marketing contact be traced to a lawful owner-approved source and current channel status while campaign purpose, legal basis, audience, claims, and send authority stay with accountable owners?',
    unit: 'one contact-channel-purpose record linked to its acquisition source, notice or request, timestamp, jurisdiction flag, suppression state, proposed campaign, reviewer decision, and send evidence',
    assistant: 'normalize owner-approved CRM fields, attach source evidence, record opt-out requests without delay, apply approved suppression rules, identify conflicts across systems, and prepare an audience for review without launching a campaign',
    owner: 'The business and its authorized legal, privacy, marketing, and sales owners retain the decision whether outreach is permitted, which rules apply, what claims and sender identity are used, whether consent is adequate, which audience is selected, and whether any message is sent.',
    sample: 'Use synthetic contacts or a minimized authorized sample spanning a website inquiry, customer transaction, event list, referral, purchased-list proposal, role address, duplicate email, changed phone number, email unsubscribe, channel-specific request, bounced address, prior customer, international marker, missing timestamp, and deletion request. Freeze the field dictionary, source hierarchy, campaign purpose, jurisdiction assumptions, and suppression rules before the assistant prepares the comparison. Include records from every connected sending system so a local CRM status is not mistaken for a global state.',
    facts: 'The FTC’s CAN-SPAM compliance guide explains requirements for commercial email, including accurate header information, nondeceptive subjects, identification, a postal address, a clear opt-out method, and honoring opt-out requests within the stated period. The FTC also explains that businesses remain responsible when another company handles email marketing. Federal Communications Commission consumer guidance distinguishes unwanted calls and texts and points to consent and revocation considerations under communications law and agency rules. FTC data-security guidance recommends knowing what personal information a business holds, keeping only what is needed, protecting it, disposing of it properly, and planning for incidents. These authorities establish important duties but do not decide the lawfulness of one contact, one jurisdiction, one purpose, or one campaign.',
    analysis: 'A single “subscribed” checkbox collapses several different questions. Permission may be tied to a channel, sender, purpose, notice, number or address, and time. The evidence record should preserve the exact source and event rather than a staff member’s conclusion that a person “probably opted in.” Suppression must win over audience import, enrichment, segmentation, and sync operations unless an authorized owner resolves a documented exception. A contact can be commercially relevant and still be ineligible for a particular message. The assistant may surface duplicates and system conflicts, but should not merge people merely because names resemble each other or revive a suppressed address after a new list upload. Before a send, the owner should receive counts by provenance class, missing-evidence state, suppression reason, and jurisdiction flag. After a send, the sent audience and unsubscribe events should reconcile back to the reviewed version. Open rates, replies, or platform acceptance do not prove permission.',
    exceptions: 'Purchased, scraped, appended, or partner-provided lists; unclear notices; inherited databases; children; sensitive traits; political or health messages; international contacts; role accounts; reassigned phone numbers; conflicting opt-out events; legal holds; deletion requests; complaints; regulator contact; and requests to bypass a suppression require privacy, legal, security, or marketing ownership. The assistant should not fabricate consent, treat a sale as universal permission, rewrite an event date, delete complaint evidence, decide that business-to-business outreach is automatically exempt, or send a test to a real suppressed contact.',
    measures: 'Count contact-channel-purpose units reviewed, units with source evidence, missing timestamps, suppression conflicts, duplicate identities held, cross-system mismatches, owner eligibility decisions, audience removals by reason, opt-out propagation time, unauthorized reactivation attempts, and sent-version reconciliation differences. Report email and phone separately and preserve jurisdiction uncertainty rather than folding it into an “approved” percentage. Delivery, opens, conversions, low complaints, or a vendor compliance badge cannot establish lawful permission or accurate identity.',
    conclusion: 'CRM consent operations can be delegated as provenance capture, suppression maintenance, conflict detection, and audience preparation. Eligibility, legal basis, claims, audience approval, and campaign launch remain owner decisions.',
    sources: [source('FTC — CAN-SPAM Act: A Compliance Guide for Business', 'https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business', 'official commercial email compliance guide'), source('FCC — Stop Unwanted Robocalls and Texts', 'https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts', 'official consumer communications guidance'), source('FCC — Telephone Consumer Protection Act 1991', 'https://www.fcc.gov/document/telephone-consumer-protection-act-1991', 'official statute and rulemaking hub'), ftcData, nist],
    related: ['/research/service-follow-up-audit-evidence', '/research/data-minimization-for-delegated-assistant-work', '/research/access-governance-for-delegated-operations']
  },
  {
    slug: 'property-maintenance-intake-fair-housing-boundary-study',
    title: 'Can a real estate virtual assistant triage maintenance requests without making housing decisions?',
    excerpt: 'A request-level study separating accurate intake and routing from accommodation, tenancy, vendor, safety, and legal judgment.',
    service: '/services/real-estate-virtual-assistance', serviceName: 'Real Estate Virtual Assistance',
    question: 'Can maintenance requests be recorded and routed under an owner-approved urgency matrix without asking an assistant to judge tenant rights, disability needs, habitability, vendor authorization, or legal responsibility?',
    unit: 'one maintenance contact linked to property and unit identifiers, resident words, received channel and time, disclosed conditions, approved category, routing event, owner decision, vendor status, and closure evidence',
    assistant: 'capture the resident’s words, confirm only necessary administrative details, apply an approved non-discretionary routing code, send approved safety language, preserve timestamps, and escalate any condition outside the script',
    owner: 'The property owner, manager, qualified maintenance lead, fair-housing owner, insurer, emergency service, and legal adviser retain decisions about emergency response, habitability, disability accommodation or modification, access, tenancy enforcement, vendor selection, spending, liability, and resident remedies.',
    sample: 'Use synthetic requests or an authorized minimized set covering a dripping fixture, no heat, water intrusion, electrical smell, locked-out resident, pest report, appliance failure, elevator outage, alleged mold, service animal reference, mobility barrier, language-access need, child safety concern, after-hours contact, duplicate ticket, wrong property, hostile message, vendor no-show, and request to withhold rent. Freeze the property roster, approved questions, urgency matrix, emergency wording, vendor directory, and escalation owners before triage. Test messages arriving through phone, email, portal, and text because channel loss can remove attachments or timestamps.',
    facts: 'HUD explains that the Fair Housing Act prohibits housing discrimination because of protected characteristics, including disability, and HUD guidance describes reasonable accommodations as changes to rules, policies, practices, or services that may be necessary for equal opportunity to use and enjoy housing. The joint HUD and Department of Justice statement on reasonable accommodations explains that providers should respond promptly and that undue delay can have legal significance. EPA guidance on mold emphasizes moisture control and notes that larger or contaminated situations may require professional handling. Ready.gov identifies basic emergency planning principles. These sources show why neutral intake, prompt routing, accessibility, and competent ownership matter. They do not classify a specific condition, decide whether an accommodation is reasonable, establish liability, or replace local housing, building, emergency, and landlord-tenant rules.',
    analysis: 'The intake record should distinguish what the resident reported from what staff observed and what an owner later concluded. Rephrasing “electrical smell” as a routine appliance issue can suppress an important signal; labeling a condition hazardous without authority can also mislead. The approved matrix should use observable triggers and a conservative escalation route, not diagnoses. Disability-related information must be limited to the decision need and should not circulate to every vendor or staff member. An accommodation request does not require special words, so a reference to difficulty accessing a unit should reach the trained owner without the assistant debating disability or requesting medical details. Vendor scheduling is not closure: the record needs arrival, permitted access, work state, unresolved condition, resident communication, and owner acceptance. Metrics should not reward closing tickets that were merged, deferred, or relabeled.',
    exceptions: 'Fire, gas, electrical danger, flooding, no essential utilities, possible structural failure, injury, threats, child or vulnerable-person risk, disability-related requests, service animals, suspected retaliation or discrimination, disputed access, security incidents, mold or hazardous material, insurance events, government notices, rent withholding, lease disputes, unauthorized occupants, and unavailable emergency owners require the approved specialist path. The assistant should not promise habitability, deny an accommodation, request a diagnosis, select an unapproved vendor, authorize spending, advise a resident about legal remedies, or mark work complete solely because a vendor ticket closed.',
    measures: 'Report requests received by channel, records with complete property identity, verbatim issue capture, approved routing-code agreement, urgent escalations acknowledged, disability-related references restricted and routed, duplicate tickets reconciled, vendor-state mismatches, resident updates sent from approved language, reopened conditions, owner corrections, and closure evidence. Measure time to named-owner acknowledgement separately from time to repair. A rapid response, vendor visit, low reopen rate, or resident silence does not prove fair-housing compliance, safety, habitability, or satisfaction.',
    conclusion: 'Maintenance intake can be delegated as neutral capture, approved-code routing, status reconciliation, and exception escalation. Housing rights, safety, accommodation, access, liability, spending, and closure decisions stay with authorized owners.',
    sources: [source('HUD — Housing Discrimination Under the Fair Housing Act', 'https://www.hud.gov/helping-americans/fair-housing-act-overview', 'official fair-housing overview'), source('HUD and DOJ — Reasonable Accommodations Under the Fair Housing Act', 'https://www.hud.gov/sites/documents/huddojstatement.pdf', 'official joint agency statement'), source('EPA — Mold Cleanup in Your Home', 'https://www.epa.gov/mold/mold-cleanup-your-home', 'official moisture and mold cleanup guidance'), source('Ready.gov — Plan Ahead for Disasters', 'https://www.ready.gov/plan', 'official emergency-planning guidance'), nist, ftcData],
    related: ['/research/property-admin-escalation-evidence', '/research/real-estate-listing-change-control-assistant-study', '/research/documented-escalation-paths-for-delegated-work']
  },
  {
    slug: 'customer-refund-eligibility-preparation-study',
    title: 'Can a customer support virtual assistant prepare refund cases without deciding customer rights?',
    excerpt: 'An order-level study separating evidence assembly and scripted updates from refund authority, legal conclusions, and money movement.',
    service: '/services/ecommerce-virtual-assistance', serviceName: 'Ecommerce Virtual Assistance',
    question: 'Can an assistant assemble an order and policy record, apply an owner-approved routing matrix, and draft a response while eligibility, exceptions, promises, and payment remain with authorized owners?',
    unit: 'one refund or cancellation request linked to the order, offer and policy shown at purchase, fulfillment events, customer words, payment state, proposed route, owner decision, communication, and money-movement evidence',
    assistant: 'retrieve authentic records from approved systems, preserve the customer’s request, compare objective fields with a versioned matrix, flag conflicts, prepare an owner-review packet, and send only approved status language',
    owner: 'The merchant and its authorized customer-experience, payment, legal, fraud, and finance owners retain interpretation of law and policy, eligibility, exceptions, fault, return conditions, settlement language, account restrictions, refund amount, payment release, and final communication.',
    sample: 'Test synthetic cases or a minimized authorized sample spanning pre-shipment cancellation, delayed shipment, partial shipment, damaged item, wrong item, digital product, subscription renewal, promotional bundle, gift, marketplace order, disputed delivery, duplicate charge, prior partial refund, expired stated window, vulnerable customer, suspected fraud, chargeback already filed, and an order whose purchase-time policy cannot be reconstructed. Freeze the offer, policy version, fulfillment source, payment state, routing matrix, and response templates before preparation. Include cases with no favorable business record instead of measuring only clean approvals.',
    facts: 'The FTC Mail, Internet, or Telephone Order Merchandise Rule describes seller obligations for shipment representations, delay options, cancellation, and prompt refunds for covered orders. FTC consumer guidance explains cooling-off rights for certain sales made away from a seller’s permanent place of business and also identifies important exclusions, showing why one cancellation rule cannot be applied to every transaction. The Consumer Financial Protection Bureau explains how consumers may dispute certain credit-card charges, while merchant processor or card-network procedures may impose separate operational steps. FTC data-security guidance recommends minimizing and protecting customer information. These sources establish consumer-protection context but do not determine the outcome of one order, contract, jurisdiction, product, payment method, or dispute.',
    analysis: 'The first control is reconstruction of what was actually offered and accepted. A current website policy may differ from the version presented at purchase, and a support note is not a substitute for the order, shipment, return, and payment records. The assistant can map objective states, but “late,” “used,” “delivered,” or “fraudulent” may contain contested judgments. A routing matrix should therefore identify what can be automatically prepared, what needs discretionary owner review, and what must stop. A drafted response should distinguish known status from a promise: “sent for review” is not “refund approved.” If money is authorized, the refund identifier, amount, method, owner, timestamp, and processor state should reconcile to the customer message. A platform’s refund button does not confer authority, and a processor’s “submitted” state does not prove receipt by the customer.',
    exceptions: 'Threats, safety concerns, regulated or perishable goods, medical claims, minors, suspected account takeover, identity theft, high-value orders, serial numbers, partial returns, gifts, marketplaces, international sales, subscriptions, inaccessible purchase-time terms, threatened legal or regulator action, an active chargeback, bankruptcy, sanctions, tax questions, and any request to bypass the payment system require the named owner. The assistant should not accuse a customer, rewrite an order record, promise timing, negotiate a settlement, condition a lawful right on review removal, issue store credit as an assumed substitute, or move money without explicit authority.',
    measures: 'Count requests in scope, packets with reconstructable purchase terms, objective-field agreement, missing or conflicting records, cases escalated by reason, owner changes to proposed routes, unauthorized promises prevented, refund amount mismatches, processor states reconciled, duplicate refunds stopped, customer-message corrections, and reopened contacts. Report preparation completeness separately from approval, payment, delivery, customer satisfaction, and legal compliance. Resolution time, ticket closure, retained revenue, low chargebacks, or a positive review cannot independently prove a fair or lawful outcome.',
    conclusion: 'Refund support can be delegated as evidence assembly, versioned-rule comparison, exception routing, and approved status communication. Rights, eligibility, fault, promises, settlement, account action, and money movement remain owner decisions.',
    sources: [source('FTC — Mail, Internet, or Telephone Order Merchandise Rule', 'https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule', 'official shipment and refund rule hub'), source('FTC — Cooling-Off Rule', 'https://consumer.ftc.gov/consumer-alerts/2021/12/what-ftcs-cooling-rule-means-consumers', 'official consumer guidance on covered and excluded sales'), source('CFPB — Disputing a credit card charge', 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-a-charge-on-my-credit-card-bill-en-61/', 'official consumer billing-dispute overview'), ftcData, nist],
    related: ['/research/ecommerce-return-exception-routing-study', '/research/ecommerce-chargeback-evidence-preparation-study', '/research/ecommerce-status-reconciliation-study']
  },
  {
    slug: 'form-i9-administrative-preparation-boundary-study',
    title: 'What Form I-9 work can a recruiting virtual assistant prepare without making employment decisions?',
    excerpt: 'An employee-record study separating reminders and completeness checks from document choice, discrimination, verification, and legal judgment.',
    service: '/services/recruiting-coordination', serviceName: 'Recruiting Coordination',
    question: 'Can an assistant coordinate Form I-9 deadlines and perform non-discretionary completeness checks without selecting documents, judging authenticity, discriminating, or acting outside an authorized representative role?',
    unit: 'one employee verification record linked to the accepted offer, start date, form version, employee-completed section, document-presentation event, authorized reviewer, corrections, retention date, reverification trigger, and access log',
    assistant: 'send approved neutral instructions, track owner-supplied deadlines, verify that required administrative fields are present, route the record to the employer’s authorized reviewer, preserve corrections, and restrict access under the approved retention plan',
    owner: 'The employer and its authorized HR, immigration, legal, security, and Form I-9 representative owners retain employment eligibility procedures, document examination, authenticity and identity judgments, anti-discrimination compliance, remote-examination eligibility, E-Verify action, reverification, correction decisions, retention, and employment action.',
    sample: 'Use synthetic employee records or a securely authorized sample covering a first job, rehire, name difference, missing field, preparer or translator, one List A document, a List B and C combination, receipt scenario, expiring employment authorization, document that should not be reverified, remote examination proposal, late form, correction, E-Verify mismatch routed to its owner, and a worker who asks which document to provide. Freeze the current form edition, official instructions, employer procedure, start-date source, representative roster, remote-examination eligibility decision, and secure retention rule before coordination.',
    facts: 'USCIS states that employers must complete and retain Form I-9 for people hired for employment in the United States and publishes the current form, instructions, handbook, retention guidance, and information about authorized representatives. USCIS instructions state that employees may choose which acceptable documentation to present and that employers generally may not specify which documents they want. The Department of Justice Immigrant and Employee Rights Section explains that employers may not discriminate in hiring, firing, recruitment, or the Form I-9 and E-Verify processes based on protected citizenship, immigration-status, or national-origin grounds within the law’s coverage. USCIS remote-examination materials describe an alternative procedure only for eligible employers using E-Verify and subject to specified steps. These sources establish process boundaries; they do not approve a local workflow or decide an individual’s status.',
    analysis: 'Administrative completeness is narrower than verification. The assistant can note that a required field is blank or that a signature date is absent, but should not coach an employee toward a preferred document or decide that a document appears genuine unless formally designated and trained for that employer role. A reminder should identify the official lists and employee choice without requesting extra proof. Start date, hire date, and form dates must come from named systems because an inferred date can create a false deadline. Corrections should preserve who changed what, when, why, and under which official procedure; silently replacing a file destroys that history. Remote inspection must not be used merely because staff are distributed. Access should be limited because forms contain identity information that can facilitate harm. Retention dates require the official rule and employment records, not a convenient annual deletion date.',
    exceptions: 'A worker asking which document to show, suspected fraud, inconsistent identity, immigration questions, accommodation or language needs, a late or missing form, receipt rules, expiring authorization, reverification, rehire, merger records, remote-examination eligibility, E-Verify tentative nonconfirmation, government inspection, subpoena, data incident, discrimination complaint, or proposed adverse action requires the designated HR, immigration, legal, or security owner. The assistant should not demand a green card, reject a document based on accent or appearance, ask for more documents than required, run E-Verify without authority, give immigration advice, backdate a form, or terminate a worker.',
    measures: 'Report records in scope, neutral instructions delivered, employee-choice questions escalated, administrative blanks detected, reviewer corrections by field, deadline exceptions, unauthorized extra-document requests prevented, access exceptions, remote-examination cases routed, reverification triggers confirmed by an owner, retention dispositions, and records with complete audit history. Separate form completeness from lawful procedure, document authenticity, work authorization, E-Verify status, and employment outcome. A completed form, system acceptance, or fast onboarding does not prove nondiscrimination or legal sufficiency.',
    conclusion: 'Form I-9 administration can be delegated as neutral instruction delivery, deadline tracking, limited completeness review, secure routing, and record control. Document choice, examination, status, discrimination, E-Verify, corrections, retention, and employment decisions remain with trained authorized owners.',
    sources: [source('USCIS — I-9, Employment Eligibility Verification', 'https://www.uscis.gov/i-9', 'official Form I-9 hub'), source('USCIS — Handbook for Employers M-274', 'https://www.uscis.gov/i-9-central/form-i-9-resources/handbook-for-employers-m-274', 'official employer handbook'), source('USCIS — Remote Examination of Documents', 'https://www.uscis.gov/i-9-central/remote-examination-of-documents', 'official alternative-procedure guidance'), source('DOJ — Immigrant and Employee Rights Section', 'https://www.justice.gov/crt/immigrant-and-employee-rights-section', 'official anti-discrimination enforcement overview'), nist, ftcData],
    related: ['/research/recruiting-coordination-delegation-boundaries', '/research/recruiting-interview-accommodation-routing-study', '/research/identity-and-accountability-in-remote-assistant-access']
  }
];

export const september28ResearchPosts: ResearchPost[] = specs.map((s) => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, published,
  methodology: `Research question: ${s.question} The unit of analysis is ${s.unit}. This desk study reviews the current primary and authoritative sources listed below, then specifies a prospective, bounded workflow test for a Philippines-based virtual assistant. It reports no observed company performance. Source facts, local analysis, proposed controls, uncertainty, and owner decisions remain separate. Sources were checked ${checked}.`,
  headlineStat: { value: '1', label: 'bounded workflow unit examined', source: 'Declared prospective study design' },
  keyStats: [{ value: String(s.sources.length), label: 'primary or authoritative sources reviewed' }, { value: '2', label: 'separate role decisions: prepare and approve' }, { value: '0', label: 'workforce or business-result claims' }],
  takeaways: [`The assistant may ${s.assistant}.`, s.owner, s.conclusion],
  sections: [
    { heading: 'Decision, roles, and evidence boundary', body: `The decision is whether a repeatable administrative preparation lane can be delegated without transferring authority that the evidence cannot support. The unit is ${s.unit}. The assistant may ${s.assistant}. ${s.owner} This separation must appear in permissions, scripts, templates, status labels, and the retained work record. Tool access does not authorize every available action, and a complete-looking record does not prove that the underlying decision is correct. Before testing, the owner should name allowed inputs, permitted actions, required output, reviewer, review window, stop conditions, communication rules, and fallback owner. The assistant should demonstrate the boundary with a safe example before live work.`, table: [['Decision field', 'Required record'], ['Unit', s.unit], ['Assistant lane', s.assistant], ['Owner lane', s.owner], ['Stop rule', 'Conflict, ambiguity, sensitive content, or unavailable authority']] },
    { heading: 'What the authoritative sources support', body: `${s.facts} The responsible reading is narrow. An authoritative source can support a defined principle, duty, or process, but it cannot prove that a business configured its workflow correctly or that a particular outcome is lawful. Applicable state, local, international, contractual, professional, and platform rules may add requirements. Each source fact should retain its publisher and scope. Each proposed local control should be labeled as analysis. Each unresolved issue should remain uncertainty until the accountable owner decides it. This prevents a citation from being used to decorate a conclusion the publisher never made.`, table: [['Evidence class', 'Treatment'], ['Source fact', 'Attribute it and preserve scope'], ['Local observation', 'Attach it to the dated unit'], ['Analysis', 'Label reasoning and alternatives'], ['Uncertainty', 'Keep open rather than convert to fact'], ['Owner choice', 'Record the authorized disposition']] },
    { heading: 'Prospective sample and method', body: `${s.sample} Define inclusion and exclusion rules before results are visible so easy cases cannot be selected afterward. Start in prepare-only or shadow mode: the assistant records a proposed route and evidence while the authorized owner independently reviews the same unit. Compare specific fields, not a vague pass score. Preserve disagreements, missing evidence, pending items, corrections, and stopped work. Include ordinary work, boundary cases, and unavailable or conflicting inputs. Any live employee, applicant, resident, customer, payment, identity, or marketing data must remain inside approved access, minimization, retention, and deletion controls. This proposed sample can expose weaknesses in one lane; it cannot establish a population rate or promise future performance.`, table: [['Method step', 'Evidence'], ['Freeze', 'Procedure, sources, permissions, and sample rule'], ['Prepare', 'Proposed action and cited input'], ['Review', 'Independent owner disposition'], ['Reconcile', 'Difference, reason, and correction'], ['Decide', 'Keep, narrow, revise, or pause']] },
    { heading: 'Analysis of the delegation boundary', body: `${s.analysis} For ${s.serviceName.toLowerCase()}, the useful result is not a count of clicks, documents, records, or hours online. It is whether another authorized person can reconstruct why the proposed action was within scope. The record should preserve the request, source state, rule version, proposed action, actor, timestamp, review, communication, and unresolved point. Access should reveal only what the lane requires. Expansion should proceed one stable case class at a time after representative review. A changed system, audience, policy, jurisdiction, data type, or authority must reopen the decision instead of inheriting approval from an older test.`, table: [['Control', 'Test'], ['Authority', 'Was the action explicitly permitted?'], ['Evidence', 'Can source and state be reconstructed?'], ['Access', 'Was only necessary information available?'], ['Communication', 'Did wording avoid unsupported commitments?'], ['Change', 'Would a new condition trigger review?']] },
    { heading: 'Exceptions, limitations, and recovery', body: `${s.exceptions} This is a prospective operating study, not legal, tax, employment, housing, privacy, financial, security, or other professional advice. It contains no live performance dataset and makes no claim about an individual assistant, the Philippines workforce, customer outcomes, or service results. A clean shadow test may reflect an easy sample, unusually available reviewer, or synthetic cases that omit real pressure. The owner should test access removal, downtime, correction, notification, and recovery before expansion. If an action is wrong, preserve the earlier state, stop similar work, correct through the authorized path, notify the accountable owner, and document what evidence or rule must change before work resumes.`, table: [['Failure', 'Recovery'], ['Ambiguous input', 'Hold and route without guessing'], ['Wrong action', 'Stop, preserve, correct, and review peers'], ['Access concern', 'Revoke or narrow access and notify owner'], ['Unavailable owner', 'Use the approved fallback or pause'], ['Rule change', 'Version the procedure and retest']] },
    { heading: 'Measures, interpretation, and conclusion', body: `${s.measures} Predeclare the denominator, review window, treatment of pending cases, and disagreement owner. A blended percentage can hide one severe miss among easy items, so material exceptions should appear separately. Compare like with like and retain the source population. An owner approval is evidence of disposition, not proof that the decision was legally or professionally correct. ${s.conclusion} The defensible next step is a reversible shadow test with a named owner, minimum access, versioned rules, and a written stop path. Expand only a case class whose evidence remains traceable; narrow or pause when work requires unauthorized inference or excess access.`, table: [['Decision', 'Evidence threshold'], ['Keep', 'Representative units are traceable and within scope'], ['Revise', 'A repeatable field caused correctable disagreement'], ['Narrow', 'Risk or authority exceeds preparation'], ['Pause', 'Owner, evidence, secure access, or recovery is missing']] }
  ],
  sourceNotes: `Sources checked ${checked}: ${s.sources.map((x) => `${x.name} (${x.url})`).join('; ')}. The workflow design and niche-specific conclusions are OverseasVirtualAssistant.com analysis, not findings or endorsements by the cited publishers.`,
  sources: s.sources, internalLinks: [s.service, '/research', '/contact'],
  faqs: [{ question: 'Does this study measure virtual assistant performance?', answer: 'No. It defines a prospective, bounded test and makes no claim about an individual, workforce, or service outcome.' }, { question: 'Can an owner use this article as professional advice?', answer: 'No. Applicable legal, tax, employment, housing, privacy, financial, security, platform, and contractual decisions require authorized owners and qualified advisers.' }, { question: 'When should this lane expand?', answer: 'Only after representative shadow work is reconstructable, exceptions reach a named owner, recovery is tested, and the next case class has explicit authority.' }],
  relatedResearch: s.related, image,
  serviceHandoff: { href: s.service, label: `Review ${s.serviceName}`, copy: 'Use the service page to translate this evidence boundary into a scoped Philippines-based support role. The business keeps approvals, sensitive exceptions, professional judgments, and final decisions.' },
  cta: 'Want this research translated into a scoped staffing role? Share the work, tools, schedule, sensitive-data limits, and owner rules with our staffing team.'
}));
