import type { ResearchPost } from './data';

const published='2026-09-09';
const image={src:'/images/remote-onboarding.jpg',alt:'Remote editorial team reviewing research records and article evidence'};
const gao={name:'U.S. GAO Yellow Book',url:'https://www.gao.gov/yellowbook',note:'standards for sufficient, appropriate evidence, documentation, and professional judgment'};
const nist={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'governance, roles, risk context, and improvement guidance'};
const wcag={name:'Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/',note:'testable accessibility success criteria and conformance requirements'};
const cisa={name:'CISA Secure Our World',url:'https://www.cisa.gov/secure-our-world',note:'practical account-security and phishing-resistance guidance'};
const ftc={name:'FTC Start with Security',url:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',note:'business guidance on access controls and limiting retained data'};
const plain={name:'U.S. Plain Language Guidelines',url:'https://www.plainlanguage.gov/guidelines/',note:'public guidance for organizing and writing reader-centered information'};
type Source=typeof gao; type Spec={slug:string;title:string;excerpt:string;question:string;method:string;interpretation:string;limitations:string;sources:Source[]};
const specs:Spec[]=[
 {slug:'claim-source-traceability-in-va-prepared-article-drafts',title:'Can reviewers trace claims in VA-prepared drafts to their sources?',excerpt:'A bounded audit design for measuring whether consequential article claims lead to relevant evidence.',question:'For a defined sample of draft claims, can an independent reviewer locate the cited passage and determine what it supports?',method:'Freeze the draft version and define consequential claims before inspection. Two reviewers independently follow each citation, code direct support, partial support, inference, conflict, or no accessible support, then reconcile disagreements without changing the original observations.',interpretation:'Report traceability and support as separate results. A reachable link may be irrelevant, while an inaccessible source may have been appropriate when the draft was prepared. Any inference must be labeled and tied to the observed codes.',limitations:'The audit does not establish that a source is true, complete, current outside the observation window, or suitable for another claim. A small editorial sample is not a population estimate or a worker-performance score.',sources:[gao,plain]},
 {slug:'handoff-completeness-before-overnight-editorial-review',title:'How complete are article handoffs before overnight editorial review?',excerpt:'A record-based method for checking whether editors receive the inputs needed to make a publication decision.',question:'At the recorded handoff time, which required draft, source, identity, exception, and approval fields are present and usable?',method:'Define the required handoff fields and eligible overnight queue before looking at outcomes. Inspect timestamped records as they existed at handoff, code absent, present, unclear, or not applicable, and have a second reviewer check ambiguous cases.',interpretation:'Completeness describes the packet, not the quality of the article or the diligence of a person. Present fields can still contain weak information, so retain usability notes rather than converting them into a single performance judgment.',limitations:'Results apply only to the sampled queue, field definition, systems, and dates. The method cannot determine why an item was missing or whether a different editor would have needed the same information.',sources:[gao,nist]},
 {slug:'metadata-content-alignment-after-daily-article-edits',title:'Does article metadata still align after final daily edits?',excerpt:'A reproducible comparison of visible copy, canonical identity, structured dates, and social-preview fields.',question:'After editorial lock, do the rendered title, description, canonical, datePublished, OG fields, and family-index label describe the same article identity?',method:'Freeze the approved identity sheet and exact deployed commit. Fetch each sampled route directly, record rendered and source metadata, compare fields using declared rules, and preserve screenshots or response extracts for mismatches.',interpretation:'Classify exact mismatches separately from reasonable description differences. A technical pass does not prove search-engine indexing or social-platform cache refresh; it proves only the observed response and rendered state.',limitations:'Checks are time-, route-, user-agent-, and environment-bound. They cannot prove availability between observations, future cache behavior, ranking, or reader comprehension.',sources:[gao,wcag,plain]},
 {slug:'least-access-fit-for-remote-content-research-tasks',title:'Does remote content research follow a least-access task model?',excerpt:'A scoped access review that maps research work to accounts, permissions, data, and named owners.',question:'For a defined set of content-research tasks, does each granted permission have a documented task need and responsible owner?',method:'Inventory task steps, accounts, roles, sensitive data, and approval owners at a stated date. Compare granted access with documented need, record unused or unexplained privileges, and send disputed business requirements to the system owner.',interpretation:'An unexplained permission is an exception for review, not proof of misuse. Findings should separate observed configuration from inferred risk and management decisions.',limitations:'This review is not a penetration test, compliance certification, legal opinion, or proof that credentials were used safely. It covers only inventoried systems, accounts, and observation time.',sources:[nist,cisa,ftc]},
 {slug:'repeatability-of-live-article-release-audits',title:'Are live article release audits repeatable across reviewers?',excerpt:'A paired-review design for testing whether two auditors reach the same route-level release results.',question:'When two reviewers use the same frozen route list and gate definitions, how often do their HTTP, date, canonical, index, sitemap, and image results agree?',method:'Specify every gate and expected value before testing. Reviewers independently inspect the same routes within a bounded window, retain raw observations, compare agreement per gate, and resolve differences only after the independent records are saved.',interpretation:'Agreement measures procedure repeatability, not whether the chosen gates are sufficient for every publishing risk. Report disagreements and missing observations instead of hiding them in an overall pass rate.',limitations:'Network state, caching, timing, tools, and human interpretation may affect results. A matched audit cannot prove continuous availability, complete accessibility, search indexing, or absence of untested defects.',sources:[gao,wcag,nist]},
];

export const september9ResearchPosts:ResearchPost[]=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published,methodology:`Research question: ${s.question} Scope: one explicitly defined and dated set of article records, routes, or permissions. ${s.method} The cited public guidance informs the review criteria; the study design and all local interpretations are ours.`,headlineStat:{value:'1',label:'bounded unit of analysis',source:'Declared article methodology'},keyStats:[{value:String(s.sources.length),label:'reputable public guidance sources consulted'},{value:'2',label:'independent reviewers where judgment is coded'},{value:'0',label:'population or worker-performance claims'}],takeaways:[s.interpretation,s.method,s.limitations],sections:[{heading:'Research question and scope',body:`${s.question} The unit of analysis is limited to the declared dated set; other teams, dates, and systems are outside scope.`,table:[['Boundary','Recorded value'],['Family','Research'],['Publication date',published],['Generalization','None beyond observed records']]},{heading:'Method and records',body:s.method,table:[['Layer','Required record'],['Expected','Predeclared field or state'],['Observed','Raw result'],['Decision','Named reviewer disposition']]},{heading:'Interpretation and inference limits',body:s.interpretation,table:[['Evidence class','Treatment'],['Observed','Report directly'],['Inferred','Label and bound'],['Unknown','Keep unresolved']]},{heading:'Limitations',body:s.limitations,table:[['Constraint','Effect'],['Time','Snapshot only'],['Sample','No population estimate'],['Authority','Publication decisions remain editorial']]},{heading:'Operational use',body:'A Philippines-based research assistant can assemble records, reproduce defined checks, and flag exceptions. Editors interpret evidence and own public claims; system owners and qualified specialists decide within protected domains.',table:[['Role','Responsibility'],['Assistant','Collect and flag'],['Editor','Interpret and approve'],['Specialist','Decide protected questions']]}],sourceNotes:`Sources consulted: ${s.sources.map(x=>x.url).join('; ')}. These organizations do not endorse OverseasVirtualAssistant.com and do not supply results for the proposed local review.`,sources:s.sources,internalLinks:['/research','/blog','/services/research-and-data-support'],faqs:[{question:'Does this method rate individual virtual assistants?',answer:'No. It examines a bounded process record, route set, or access configuration.'},{question:'Can the results be generalized to other teams?',answer:'No. Findings must remain attached to the stated sample, date, method, and limitations.'}],relatedResearch:['/research/repeatability-of-live-article-release-audits'],image,cta:'Apply the method to one frozen set, retain contrary evidence, and publish only conclusions supported within scope.'}));
