import type { ResearchPost } from './data';

const published = '2026-09-26';
const checked = 'September 26, 2026';
const image = { src: '/images/remote-onboarding.jpg', alt: 'A Philippines-based virtual assistant and business owner reviewing evidence for a bounded work handoff' };
type Source = { name: string; url: string; note: string };
type Spec = { slug:string; title:string; excerpt:string; service:string; serviceName:string; question:string; unit:string; assistant:string; owner:string; sample:string; facts:string; analysis:string; exceptions:string; measures:string; conclusion:string; sources:Source[]; related:string[] };
const source = (name:string, url:string, note:string):Source => ({ name, url, note: `${note}; checked ${checked}` });
const nist = source('NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework', 'primary risk-governance framework');
const ftcData = source('FTC — Protecting Personal Information: A Guide for Business', 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', 'official data minimization and security guidance');

const specs: Spec[] = [
  {
    slug:'legal-efiling-packet-preparation-boundary-study',
    title:'Can a legal administrative virtual assistant prepare an e-filing packet without exercising filing authority?',
    excerpt:'A filing-event study separating document and docket preparation from legal judgment, signer authority, and final submission.',
    service:'/services/legal-administrative-assistance', serviceName:'Legal Administrative Assistance',
    question:'Can each proposed filing packet be assembled from attorney-approved documents and court instructions while the authorized filer retains classification, redaction, deadline, and submission decisions?',
    unit:'one proposed filing event linked to a matter, approved document set, court-specific instruction, reviewer disposition, and resulting notice or hold',
    assistant:'collect the approved source documents, compare filenames and visible fields with a checklist, prepare a draft event record, flag conflicts, and preserve the reviewer’s disposition without pressing the final submit control',
    owner:'The attorney or other authorized filer retains legal advice, event selection, deadline calculation, signature authority, privilege and sealing decisions, redaction approval, representations to the court, payment, and final submission.',
    sample:'Use a training environment, synthetic matters, or an authorized de-identified sample that covers a routine notice, multiple attachments, a corrected document, a sealed or restricted indicator, a filing-fee prompt, a mismatched case number, an unavailable instruction, and a deadline that the assistant is not asked to calculate. Freeze the court, rule set, checklist version, and approved document set before comparison.',
    facts:'The Administrative Office of the U.S. Courts explains that CM/ECF permits court documents to be filed online and that filing access requires an account and special access issued by an individual court. PACER guidance says an attorney must be admitted and registered with the relevant court to file electronically, while court-specific procedures govern the event and document requirements. Federal Rule of Civil Procedure 5.2 identifies categories of personal identifiers that generally require redaction in court filings. These authorities show why access, court rules, and privacy review are material; they do not authorize an assistant to choose a legal filing or certify compliance.',
    analysis:'Packet preparation is distinguishable from filing authority when the draft cannot become a court representation without an independent owner action. The checklist should identify the court, matter, proposed event, source of that event choice, approved lead document, ordered attachments, file format, visible identifier check, and signer. A system preview is evidence to review, not permission to submit. The workflow should prevent a preparer from changing a pleading to make it fit an event, inferring a deadline, choosing a sealed event, or reusing credentials. The notice of electronic filing or rejection should return to the responsible legal owner before any status is communicated.',
    exceptions:'Sealed or highly sensitive documents, juvenile or criminal records, personal identifiers, emergency relief, filing deadlines, unavailable court systems, rejected filings, fee questions, amended pleadings, disputed service, and a mismatch between the document and proposed event require the authorized legal owner. The assistant should not interpret a rule, alter substance, sign for another person, tell a client that filing is complete before accepted evidence exists, or use one court’s instructions for another court.',
    measures:'Report eligible packets, packets with complete approved inputs, field-level reviewer agreement, case-number mismatches stopped, redaction flags, unauthorized-event attempts, rejected or held packets, notices reconciled, and owner corrections. Separate packet completeness from successful filing and legal sufficiency. Speed, a generated receipt, or the absence of a technical error does not prove that the filing was timely, authorized, accurate, or legally effective.',
    conclusion:'Legal e-filing support is suitable for delegation only as reversible packet preparation and evidence reconciliation. A licensed or otherwise authorized owner must retain every legal, privacy, signature, deadline, and submission decision.',
    sources:[source('U.S. Courts — Electronic Filing (CM/ECF)','https://www.uscourts.gov/court-records/electronic-filing-cm-ecf','official description of CM/ECF and filing access'),source('PACER — File a Case','https://pacer.uscourts.gov/file-case','official filing access and court-specific guidance'),source('Federal Rules of Civil Procedure — Rule 5.2','https://www.law.cornell.edu/rules/frcp/rule_5.2','Legal Information Institute reproduction of the federal privacy-protection rule'),nist,ftcData],
    related:['/research/legal-deadline-intake-assistant-control-study','/research/access-governance-for-delegated-operations','/research/documented-escalation-paths-for-delegated-work']
  },
  {
    slug:'podcast-sponsorship-disclosure-evidence-study',
    title:'Can a podcast virtual assistant prepare sponsorship disclosures without deciding what an audience needs to know?',
    excerpt:'An episode-level study of sponsor records, disclosure placement, and approval without transferring advertising judgment.',
    service:'/services/podcast-administration', serviceName:'Podcast Administration',
    question:'Can an episode record make every material sponsor or guest relationship visible to the producer before release while the owner retains disclosure wording and advertising approval?',
    unit:'one episode and its sponsor, host, guest, affiliate, product, platform, script, show-note, and approval records',
    assistant:'collect the approved commercial terms, map relationships to each planned channel, insert owner-approved disclosure language into a draft run sheet and show notes, flag missing records, and verify that the released assets match the approved version',
    owner:'The advertiser, publisher, or authorized producer retains the legal assessment of material connections, claim substantiation, disclosure wording and prominence, editorial independence, guest conflicts, audience targeting, and final release.',
    sample:'Select consecutive planned episodes plus simulations that include a host-read advertisement, free product, affiliate link, employee guest, agency-booked guest, dynamic ad insertion, a social clip, a newsletter mention, a changed sponsor, and an episode with no commercial relationship. Freeze the contract record and approved language before the assistant prepares the channel map.',
    facts:'The FTC Endorsement Guides address endorsements and material connections that audiences may not reasonably expect. FTC staff guidance explains that disclosures should be clear and conspicuous and placed with the endorsement, and it discusses disclosures in video, livestream, and social media contexts. The FTC’s advertising substantiation policy states that advertisers need a reasonable basis for objective claims before dissemination. These sources establish advertising principles, but they do not approve a particular script, guarantee that one disclosure works on every channel, or decide whether a guest’s relationship is material.',
    analysis:'The core control is a relationship-to-channel map, not a generic disclosure sentence. A listener may hear an embedded episode, read show notes, watch a clip, or encounter an affiliate link without seeing the other formats. The assistant can preserve who supplied value, which party approved the claim, where the message appears, and which exact language the owner approved. The assistant should not infer that a familiar brand relationship is obvious, shorten a disclosure to fit a caption, convert a personal experience into an objective product claim, or treat platform tooling as proof that a disclosure is adequate.',
    exceptions:'Health, earnings, financial, environmental, or comparative claims; unclear compensation; gifts routed through an agency; family or employment relationships; edited testimonials; children’s audiences; platform-specific limits; missing contracts; late sponsor changes; and requests to conceal a relationship require owner or qualified legal review. The preparer should not negotiate terms, certify results, invent personal experience, or publish an unapproved claim.',
    measures:'Count episodes in scope, commercial relationships with source records, channel placements reviewed, exact approved-language matches, missing or late disclosures stopped, claim changes, owner corrections, released-version mismatches, and post-release corrections. Report by channel and relationship type. Listener growth, click-through, sponsor renewal, or a platform approval does not establish that a disclosure was sufficient or a claim substantiated.',
    conclusion:'Podcast disclosure preparation can be delegated as relationship mapping, approved-language placement, and released-version checking. Materiality, substantiation, wording, prominence, and publication remain owner decisions.',
    sources:[source('FTC — Endorsements, Influencers, and Reviews','https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews','official endorsement guidance hub'),source('FTC — Disclosures 101 for Social Media Influencers','https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers','official staff disclosure guidance'),source('FTC Policy Statement Regarding Advertising Substantiation','https://www.ftc.gov/legal-library/browse/ftc-policy-statement-regarding-advertising-substantiation','official substantiation policy'),nist,ftcData],
    related:['/research/podcast-sponsor-guest-record-handoff-study','/research/social-media-publishing-approval-study','/research/source-quality-for-assistant-prepared-research']
  },
  {
    slug:'medical-prior-authorization-status-support-study',
    title:'What prior-authorization work can a medical administrative virtual assistant prepare without making a clinical decision?',
    excerpt:'A request-level study separating status preparation and record routing from diagnosis, medical necessity, and treatment decisions.',
    service:'/services/medical-administrative-assistance', serviceName:'Medical Administrative Assistance',
    question:'Can a prior-authorization request be prepared and tracked from clinician-approved records and payer fields without asking the assistant to choose clinical facts or interpret coverage?',
    unit:'one authorization request linked to the ordered service, authorized minimum record, payer destination, status event, clinician response, and final disposition',
    assistant:'confirm approved administrative fields, assemble only the clinician-selected records, submit or stage them through the organization’s authorized route, record status messages verbatim, and escalate missing or clinical questions',
    owner:'The healthcare organization and qualified clinicians retain diagnosis and coding judgments, medical-necessity statements, treatment choice, urgency, record selection, appeal substance, patient advice, disclosure authorization, and decisions about proceeding without approval.',
    sample:'Use synthetic cases or an authorized minimum-necessary sample spanning a complete request, missing administrative field, payer request for clinical information, duplicate request, changed destination, denial, peer-review request, urgent label, patient status question, and system outage. Freeze the payer rule, clinician-approved record list, and communication script used in the test.',
    facts:'CMS describes prior authorization as a process through which a payer may require approval before an item or service is provided and has issued interoperability and prior-authorization requirements for certain impacted payers. HHS guidance explains the HIPAA minimum-necessary standard and the role of business-associate safeguards. NIST provides a framework for governing and protecting information risk. These sources support structured exchange, minimum access, and clear ownership; they do not allow an assistant to determine medical necessity, select treatment, or interpret an individual plan.',
    analysis:'Administrative preparation ends where a field requires clinical meaning. Copying an approved diagnosis or code from the designated record is different from selecting one to satisfy a payer. A request for more information should return to the clinician with the payer’s exact wording, current deadline as shown by the authorized system, and the records already sent. The assistant’s status message to a patient should use approved neutral language and avoid predicting coverage, timing, cost, or treatment. The workflow needs a stable request identifier because duplicate submissions and payer portals can show inconsistent states.',
    exceptions:'Urgent clinical concerns, requests to change a diagnosis or code, an uncertain patient identity, sensitive records outside the approved set, substance-use or specially protected information, denial reasoning, appeal arguments, peer-to-peer review, expired orders, changed coverage, or advice about delaying care require the organization’s approved clinical, privacy, billing, or payer-relations owner. The assistant should not browse the chart for persuasive details or tell a patient what care to choose.',
    measures:'Report eligible requests, required administrative fields present, clinician-approved attachments used, duplicate attempts prevented, payer status events reconciled, clinical questions stopped, excess-record exposure, patient messages corrected, owner response, and final disposition. Separate administrative completeness from approval, coverage, medical necessity, and patient outcome. Faster submission or an authorization number does not establish that treatment is appropriate or payment is guaranteed.',
    conclusion:'Prior-authorization support can be delegated as minimum-data preparation, status capture, and exact-question routing. Clinical content, record selection, appeals, coverage interpretation, and patient decisions remain with authorized owners.',
    sources:[source('CMS — Interoperability and Prior Authorization Final Rule','https://www.cms.gov/priorities/key-initiatives/burden-reduction/interoperability/policies-and-regulations/cms-interoperability-and-prior-authorization-final-rule-cms-0057-f','official payer interoperability and prior-authorization policy'),source('HHS — Minimum Necessary Requirement','https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html','official HIPAA Privacy Rule guidance'),source('HHS — Business Associates','https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/business-associates/index.html','official business-associate safeguards guidance'),nist,ftcData],
    related:['/research/medical-scheduling-minimum-necessary-data-study','/research/data-minimization-for-delegated-assistant-work','/research/privacy-risk-questions-for-remote-assistant-roles']
  },
  {
    slug:'ecommerce-chargeback-evidence-preparation-study',
    title:'Can an ecommerce virtual assistant prepare chargeback evidence without deciding the dispute?',
    excerpt:'A dispute-level study separating record assembly and deadline tracking from representations, refunds, and contest decisions.',
    service:'/services/ecommerce-virtual-assistance', serviceName:'Ecommerce Virtual Assistance',
    question:'Can each payment dispute be assembled from authentic order, fulfillment, policy, and communication records while the merchant owner retains the response strategy and every representation?',
    unit:'one dispute linked to the payment record, reason notice, order evidence, customer communications, proposed packet, owner decision, and processor disposition',
    assistant:'retrieve records from approved systems, preserve their original dates and source, map them to owner-defined packet fields, flag missing or conflicting evidence, and track the processor-visible status without altering the underlying record',
    owner:'The merchant and its authorized payment or legal owners retain the decision to accept or contest, refund, characterize authorization or fraud, make legal or contractual claims, contact the customer, submit the response, and change store policy.',
    sample:'Use synthetic disputes or an authorized minimized sample across non-receipt, duplicate processing, cancellation, refund, damaged goods, subscription, digital delivery, partial shipment, address mismatch, suspected fraud, and a case with no defensible record. Freeze the reason notice, processor instructions, policy version, and source systems before assembly.',
    facts:'The Fair Credit Billing Act and Regulation Z establish consumer protections and procedures for certain billing errors; CFPB guidance describes the consumer dispute process. The FTC Mail, Internet, or Telephone Order Merchandise Rule addresses shipment promises and specified cancellation and refund duties for covered orders. FTC data guidance advises businesses to retain only needed personal information and protect it. These authorities provide context for accurate records and consumer rights, but they do not determine a merchant’s response to a specific network dispute or prove that a transaction was authorized.',
    analysis:'A persuasive narrative must not replace source evidence. The assistant can identify the order record, policy shown at the relevant time, delivery event, refund event, and customer message, but should not label a customer dishonest or infer consent from silence. Screenshots should retain the source, timestamp, and scope; cropped or reconstructed images can remove material context. If records conflict, both states should reach the owner. The packet should also exclude unrelated customer data and internal commentary that is not required for the processor’s approved field.',
    exceptions:'Alleged identity theft, compromised accounts, threats, regulator or attorney contact, recurring-payment consent, changed policies, high-value goods, partial refunds, delivery to another person, contradictory tracking, customer medical or other sensitive data, and expired response windows require the appropriate owner. The assistant should not backfill records, contact a customer to pressure withdrawal, promise a refund, or submit an unsupported explanation.',
    measures:'Count disputes eligible for preparation, packets linked to original records, missing evidence, conflicts escalated, unnecessary personal data removed, owner revisions, unauthorized statements prevented, processor receipts reconciled, and final dispositions. Show results by reason category and do not pool pending cases with decided cases. Win rate, recovered revenue, or submission speed does not establish evidence quality, fairness, compliance, or customer satisfaction.',
    conclusion:'Chargeback support can be delegated as source-preserving evidence assembly and status tracking. The merchant owner must decide the response, approve every representation, control customer remedies, and authorize submission.',
    sources:[source('Consumer Financial Protection Bureau — How to fix mistakes in your credit card bill','https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-a-charge-on-my-credit-card-bill-en-61/','official consumer billing-dispute overview'),source('Electronic Code of Federal Regulations — Regulation Z, billing error resolution','https://www.ecfr.gov/current/title-12/chapter-X/part-1026/subpart-B/section-1026.13','official regulation text'),source('FTC — Mail, Internet, or Telephone Order Merchandise Rule','https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule','official rule and business guidance hub'),nist,ftcData],
    related:['/research/ecommerce-return-exception-routing-study','/research/ecommerce-status-reconciliation-study','/research/approval-matrix-for-delegated-operations']
  },
  {
    slug:'executive-board-packet-version-control-study',
    title:'Can an executive virtual assistant coordinate a board packet without controlling its decisions?',
    excerpt:'A document-level study of intake, version control, access, and acknowledgement while executives retain substance and release authority.',
    service:'/services/executive-assistance', serviceName:'Executive Assistance',
    question:'Can each board-packet item move from an accountable owner to the approved audience with a traceable version and acknowledgement, without the assistant deciding substance, privilege, or disclosure?',
    unit:'one packet item linked to its accountable author, approved version, access group, release decision, delivery event, and correction history',
    assistant:'maintain an owner-approved index, request missing items, apply naming and version rules, stage approved files in the designated location, record delivery evidence, and route access or content conflicts',
    owner:'Executives, counsel, and the board’s authorized officers retain agenda priorities, substantive claims, forecasts, minutes approval, privilege, confidentiality classification, conflicts, distribution, retention, and every governance decision.',
    sample:'Use synthetic materials or an authorized low-risk packet across an agenda, prior minutes, operating report, financial draft, decision memo, late replacement, restricted appendix, external link, inaccessible format, removed recipient, and a correction after distribution. Freeze the index, access group, naming rule, deadline source, and approval states before testing.',
    facts:'NIST Cybersecurity Framework 2.0 connects governance with identification, protection, detection, response, and recovery. NIST digital-identity guidance distinguishes identity proofing, authentication, and authorization. CISA recommends multifactor authentication and phishing-resistant practices, while FTC data guidance emphasizes knowing what information a business holds, limiting access, and disposing of material no longer needed. These sources support controlled access and recoverable records; they do not determine corporate governance duties or whether a document is privileged or board-ready.',
    analysis:'A polished packet can still be unsafe if ownership, approval, or audience is ambiguous. The index should display each item’s owner, state, version, approval, and access class without exposing sensitive content to unauthorized recipients. “Latest” is not an adequate version label when files arrive through email, shared drives, and messaging tools. Distribution should use the approved channel and group rather than copied addresses. The assistant can report a missing approval or failed delivery, but cannot interpret silence as consent, downgrade a restriction, edit substantive minutes, or decide that a late file is immaterial.',
    exceptions:'Privileged legal advice, personal data, investigations, conflicts of interest, forecasts, transactions, executive compensation, security incidents, disputed minutes, external guests, changed directors, lost devices, broken links, and requests to use personal accounts require the authorized governance, legal, security, or executive owner. The assistant should not summarize away a disagreement, grant access because of seniority, or retain local copies outside policy.',
    measures:'Count indexed items, items with named owners, approved-version matches, late or missing approvals, unauthorized access attempts, failed delivery, recipient-list corrections, superseded files removed through the approved process, accessibility defects, and acknowledged owner dispositions. Separate administrative packet completeness from substantive accuracy or board approval. Delivery, an opened link, or a clean visual layout does not prove informed review or governance compliance.',
    conclusion:'Board-packet coordination is delegable as indexed intake, version control, approved distribution, and exception reporting. Executives, counsel, and authorized officers must retain substance, confidentiality, privilege, audience, and release decisions.',
    sources:[nist,source('NIST — Digital Identity Guidelines','https://pages.nist.gov/800-63-4/','primary identity, authentication, and federation guidance'),source('CISA — More than a Password','https://www.cisa.gov/secure-our-world/use-strong-passwords','official authentication guidance'),ftcData,source('U.S. Small Business Administration — Manage your business','https://www.sba.gov/business-guide/manage-your-business','official small-business management guidance hub')],
    related:['/research/executive-meeting-action-register-delegation-study','/research/secure-file-sharing-for-virtual-assistant-work','/research/access-governance-for-delegated-operations']
  }
];

export const september26ResearchPosts: ResearchPost[] = specs.map((s) => ({
  slug:s.slug, title:s.title, excerpt:s.excerpt, published,
  methodology:`Research question: ${s.question} The unit of analysis is ${s.unit}. This desk study reviews the current primary and authoritative sources listed below, then defines a prospective, bounded workflow test for a Philippines-based virtual assistant. It reports no observed company performance. Source facts, proposed controls, analysis, uncertainty, and owner decisions remain separate. Sources were checked ${checked}.`,
  headlineStat:{value:'1',label:'bounded workflow unit examined',source:'Declared prospective study design'},
  keyStats:[{value:String(s.sources.length),label:'primary or authoritative sources reviewed'},{value:'2',label:'separate role decisions: prepare and approve'},{value:'0',label:'workforce or business-result claims'}],
  takeaways:[`The assistant may ${s.assistant}.`,s.owner,s.conclusion],
  sections:[
    {heading:'Decision, roles, and evidence boundary',body:`The business decision is whether a repeatable preparation lane can be delegated without transferring authority that the evidence cannot support. The unit is ${s.unit}. The assistant may ${s.assistant}. ${s.owner} This separation must appear in permissions, instructions, templates, status labels, and the retained work record. Tool access does not authorize every available action, and a complete-looking record does not establish that the underlying decision is correct. Before a test begins, the owner should name the allowed inputs, permitted action, required output, reviewer, review period, stop conditions, and fallback owner. The assistant should be able to demonstrate the boundary with a safe example before any live work.`,table:[['Decision field','Required record'],['Unit',s.unit],['Assistant lane',s.assistant],['Owner lane',s.owner],['Stop rule','Conflict, ambiguity, sensitive content, or unavailable authority']]},
    {heading:'What the authoritative sources support',body:`${s.facts} The responsible reading is deliberately narrow. Authoritative guidance can support principles such as accountable governance, minimum access, reliable records, review, and recovery. It cannot prove that a local workflow is accurate, compliant, profitable, or suitable in every jurisdiction. The business must identify its own applicable laws, contracts, platform rules, and professional duties. A source fact should retain its publisher and scope. A proposed local control should be labeled as analysis. An unresolved issue should remain uncertainty until the appropriate owner decides it. This prevents a citation from being used to decorate a conclusion the publisher never made.`,table:[['Evidence class','Treatment'],['Source fact','Attribute to the publisher and preserve scope'],['Local observation','Attach to the dated sample and unit'],['Analysis','Label the reasoning and alternatives'],['Uncertainty','Keep open rather than converting it into fact'],['Owner choice','Record the authorized disposition']]},
    {heading:'Prospective sample and method',body:`${s.sample} Define inclusion and exclusion rules before results are visible so the easiest cases cannot be selected after the fact. Start in prepare-only or shadow mode: the assistant records the proposed action and evidence while the authorized owner independently reviews the same unit. Compare specific fields rather than assigning a vague pass score. Preserve disagreements, missing evidence, pending items, and corrected results. Include ordinary work, boundary cases, and at least one unavailable or conflicting input. Any live personal, customer, patient, legal, payment, or governance data must remain inside approved access, minimization, retention, and deletion controls. A described sample can reveal weaknesses in this lane; it cannot establish a population rate or promise future performance.`,table:[['Method step','Evidence'],['Freeze','Procedure, sources, permissions, and sample rule'],['Prepare','Proposed action and cited input'],['Review','Independent owner disposition'],['Reconcile','Difference, reason, and correction'],['Decide','Keep, narrow, revise, or pause']]},
    {heading:'Analysis of the delegation boundary',body:`${s.analysis} For ${s.serviceName.toLowerCase()}, the useful result is not a count of clicks, messages, documents, or hours online. It is whether another authorized person can reconstruct why the proposed action was within scope. The record should preserve the request, source state, rule version, proposed action, actor, timestamp, review, and unresolved point. External communication should use approved language, and access should reveal only what the lane requires. Expansion should proceed one stable case class at a time after representative review. A changed system, audience, policy, jurisdiction, data type, or authority should reopen the decision instead of inheriting approval from an older test.`,table:[['Control','Test'],['Authority','Was the action explicitly permitted?'],['Evidence','Can the source and state be reconstructed?'],['Access','Was only necessary information available?'],['Communication','Did wording avoid unsupported commitments?'],['Change','Would a new condition trigger review?']]},
    {heading:'Exceptions, limitations, and failure recovery',body:`${s.exceptions} This is a prospective operating study, not legal, medical, tax, security, financial, or other professional advice. It contains no live performance dataset and makes no claim about an individual assistant, the Philippines workforce, customer outcomes, or service results. A clean shadow test may reflect an easy sample, an unusually available reviewer, or synthetic cases that omit real pressure. The owner should test access removal, downtime, correction, notification, and recovery before expansion. If an action is wrong, preserve the earlier state, stop similar work, correct the record through the authorized path, notify the accountable owner, and document what evidence or rule must change before work resumes.`,table:[['Failure','Recovery'],['Ambiguous input','Hold and route without guessing'],['Wrong action','Stop, preserve, correct, and review peers'],['Access concern','Revoke or narrow access and notify owner'],['Unavailable owner','Use the approved fallback or pause'],['Rule change','Version the procedure and retest']]},
    {heading:'Measures, interpretation, and conclusion',body:`${s.measures} Predeclare the denominator, review window, treatment of pending cases, and disagreement owner. A blended percentage can hide one severe miss among many easy items, so material exceptions should appear separately. Compare like with like. An owner approval is evidence of disposition, not proof that the decision was legally or professionally correct. ${s.conclusion} The defensible next step is a reversible shadow test with a named owner, minimum access, and a written stop path. Expand only a class whose evidence remains traceable. Narrow or pause when the work cannot proceed without inference, sensitive excess access, or unauthorized judgment.`,table:[['Decision','Evidence threshold'],['Keep','Representative units are traceable and within scope'],['Revise','A repeatable field or rule caused correctable disagreement'],['Narrow','Risk or authority exceeds the preparation lane'],['Pause','Owner, evidence, secure access, or recovery path is missing']]}
  ],
  sourceNotes:`Sources checked ${checked}: ${s.sources.map((x)=>`${x.name} (${x.url})`).join('; ')}. The workflow design and niche-specific conclusions are OverseasVirtualAssistant.com analysis, not findings or endorsements by the cited publishers.`,
  sources:s.sources, internalLinks:[s.service,'/research','/contact'],
  faqs:[{question:'Does this study measure virtual assistant performance?',answer:'No. It defines a prospective, bounded test and makes no claim about an individual, workforce, or service outcome.'},{question:'Can an owner use this article as professional advice?',answer:'No. Applicable legal, medical, financial, security, platform, and contractual decisions require authorized owners and qualified advisers.'},{question:'When should this lane expand?',answer:'Only after representative shadow work is reconstructable, exceptions reach a named owner, recovery is tested, and the next case class has explicit authority.'}],
  relatedResearch:s.related, image,
  serviceHandoff:{href:s.service,label:`Review ${s.serviceName}`,copy:`Use the service page to translate this evidence boundary into a scoped Philippines-based support role. The business keeps approvals, sensitive exceptions, and professional decisions.`},
  cta:'Want this research translated into a scoped staffing role? Share the work, tools, schedule, sensitive-data limits, and owner rules with our staffing team.'
}));
