import type { ResearchPost } from './data';

const published = '2026-09-18';
const checked = 'September 18, 2026';
const image = { src: '/images/remote-onboarding.jpg', alt: 'A distributed team reviewing a documented virtual assistant workflow' };

const sba = { name: 'U.S. Small Business Administration — Manage your business', url: 'https://www.sba.gov/counseling/manage-your-business/', note: `role definition and management guidance; checked ${checked}` };
const nist = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: `governance, access, and risk-management guidance; checked ${checked}` };
const ftc = { name: 'Federal Trade Commission — Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', note: `data minimization and access-control guidance; checked ${checked}` };
const cisa = { name: 'CISA — Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: `authentication, phishing, updates, and account-security guidance; checked ${checked}` };
const eeoc = { name: 'U.S. Equal Employment Opportunity Commission — Employment Tests and Selection Procedures', url: 'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures', note: `job-related and consistently applied selection-procedure guidance; checked ${checked}` };
const dol = { name: 'U.S. Department of Labor — Hours Worked', url: 'https://www.dol.gov/general/topic/workhours', note: `authoritative working-time reference; checked ${checked}` };

type Source = typeof sba;
type Spec = {
  slug: string; title: string; excerpt: string; service: string; serviceName: string;
  question: string; decision: string; evidence: string; pilot: string; risks: string;
  measures: string; conclusion: string; sources: Source[];
};

const specs: Spec[] = [
  {
    slug: 'calendar-inbox-delegation-readiness-study',
    title: 'Is your calendar and inbox work ready for a virtual assistant?',
    excerpt: 'A record-based readiness study for deciding what a Philippines-based assistant may sort, prepare, schedule, and escalate without inheriting executive authority.',
    service: '/services/calendar-and-inbox-management', serviceName: 'Calendar and Inbox Management',
    question: 'Which recurring calendar and inbox events can be handled from written rules, and which events still require the owner to interpret intent, risk, or a commitment?',
    decision: 'The decision is not whether an inbox is busy. It is whether a defined lane contains enough repeatable evidence for another person to act safely. The unit of analysis is one event: an incoming message, invitation, reschedule request, follow-up, or exception. The owner first labels the action they would take and the reason. Only then should the team ask whether a rule, approved example, or preference explains that choice. Events that depend on an unstated relationship, negotiation, legal position, payment promise, or sensitive personal context remain owner decisions.',
    evidence: 'Build a consecutive sample rather than selecting only easy messages. For each event, preserve its arrival time, requested action, sender category, sensitivity, deadline, dependencies, final disposition, and approval owner. Mask private content that is not needed for the study. Code whether an existing rule was sufficient, partly sufficient, contradictory, or absent. This separates observed readiness from the hopeful inference that an experienced assistant will simply know what to do. SBA guidance supports defining responsibilities and management expectations; FTC and CISA guidance support limiting access and protecting accounts. Those sources inform the criteria, but they do not declare a particular inbox safe to delegate.',
    pilot: 'Run a shadow pilot in which the assistant prepares labels, draft replies, schedule options, and escalation notes without sending or committing. Compare the prepared action with the owner’s independent decision. Record agreement by event type, not as a single flattering percentage. A meeting request may be consistently routable while a customer escalation is not. After reconciliation, publish a small authority matrix: actions the assistant may complete, actions that require approval, events that must stop, and the named backup when the owner is unavailable. Expand access only after the matrix works on a second consecutive sample.',
    risks: 'The largest risks are silent authority expansion, overbroad mailbox access, and rules that become stale when priorities change. Shared passwords erase accountability and should not be treated as a delegation shortcut. VIP lists can also encode assumptions that require periodic owner review. A sample cannot reveal every future message, prove confidentiality compliance, or establish employment-law obligations. The study should therefore retain an exception lane and a revocation path. Security, legal, human-resources, and contractual questions go to the responsible specialist.',
    measures: 'Useful measures include the share of events with a current rule, the share routed without reconstruction, the number of owner-only exceptions by type, the age of unresolved items, and corrections discovered before an external action. Do not convert response speed into a quality claim. A fast but unauthorized reply is a failure. Review the lane after role changes, account changes, a security event, repeated ambiguity, or a material shift in customers and commitments.',
    conclusion: 'A calendar or inbox lane is ready when representative events can be classified from current written rules, the assistant can show the evidence behind each proposed action, owner-only decisions remain visible, and the account can be granted only the access the lane needs. The next step is a bounded shadow sample, not immediate control of the whole mailbox.',
    sources: [sba, ftc, cisa],
  },
  {
    slug: 'travel-expense-assistant-handoff-readiness',
    title: 'What should be documented before delegating travel and expense support?',
    excerpt: 'A decision framework for separating itinerary research and receipt preparation from purchases, reimbursements, policy exceptions, and traveler commitments.',
    service: '/services/travel-and-expense-support', serviceName: 'Travel and Expense Support',
    question: 'Can a travel or expense request be prepared from documented preferences and source records while purchase, payment, reimbursement, and exception authority stays with the named owner?',
    decision: 'Travel support combines research, scheduling, personal data, and money, so a vague request creates several different authority problems at once. The unit of analysis is one trip request or one expense packet. Record the traveler, business purpose, approved constraints, source documents, deadlines, currencies, change conditions, and person authorized to approve. Preparation includes collecting options and organizing evidence. It does not automatically include accepting terms, using a payment method, interpreting tax treatment, or promising reimbursement.',
    evidence: 'Select a consecutive set of real requests that represents routine trips, changes, cancellations, missing receipts, and policy exceptions. Preserve quotes with capture times because availability and prices change. For expenses, link each line to a receipt or approved alternative record and retain the original currency. Mark facts copied from a provider separately from calculations and assistant notes. SBA guidance informs role definition; FTC guidance supports collecting only needed personal information and controlling access; Department of Labor material supplies a public working-time reference when coverage windows are designed. None of these sources supplies the company’s travel policy or approves a transaction.',
    pilot: 'Use a prepare-only pilot. The assistant may create a comparison table, draft itinerary, receipt register, missing-evidence list, and approval packet. The owner independently checks a sample before any booking, cancellation, reimbursement, or payment. Reconcile differences in dates, names, constraints, totals, fare rules, and decision ownership. The output should be a traveler preference record, an expense evidence checklist, an approval threshold, and an explicit list of actions that require live confirmation. Test at least one change scenario because the initial booking path does not show whether the handoff survives disruption.',
    risks: 'Risks include exposing passport or payment data, relying on stale prices, treating a draft itinerary as confirmed, losing cancellation conditions, and allowing an assistant to interpret a policy exception. The safest workflow minimizes copied sensitive data and uses role-based access in approved systems. A review sample cannot certify payment-card compliance, tax treatment, employment obligations, immigration requirements, travel safety, or consumer rights. Those decisions require the company’s authorized owner and, where appropriate, qualified specialists.',
    measures: 'Measure packets with complete decision fields, options with a capture time and direct source, expenses tied to evidence, unresolved exceptions by owner, corrections before approval, and post-approval changes that reached the traveler. Avoid claiming savings from quoted versus final prices unless the comparison method controls for itinerary, terms, timing, and currency. The goal is traceable preparation, not a promotional cost claim.',
    conclusion: 'Travel and expense support is ready to delegate when each request has a source trail, current constraints, a named approval owner, protected data boundaries, and a visible line between preparation and commitment. A useful first assignment is a prepare-only packet for one routine trip or one closed expense period.',
    sources: [sba, ftc, dol],
  },
  {
    slug: 'ecommerce-catalog-maintenance-delegation-study',
    title: 'Can ecommerce catalog maintenance be safely delegated?',
    excerpt: 'A field-level study for deciding which product updates a remote assistant may prepare and which claims, prices, inventory, and customer promises require owner approval.',
    service: '/services/ecommerce-virtual-assistance', serviceName: 'Ecommerce Virtual Assistance',
    question: 'For each catalog field, is there a current authoritative source, an allowed transformation, a review rule, and a rollback path?',
    decision: 'Catalog work looks repetitive, but a single edit can change a price, product claim, availability signal, compatibility statement, or customer expectation. The unit of analysis is one field change on one product record. Classify the field as descriptive, operational, commercial, regulated, or system-generated. Then name its source of truth and approval owner. Copying an approved dimension from a supplier record is different from inventing benefit language; formatting an approved price is different from choosing that price.',
    evidence: 'Freeze a representative export before the pilot. Include high-traffic and low-traffic items, variants, unavailable products, incomplete records, and known exceptions. For each proposed change, retain the prior value, proposed value, source URL or internal record, capture date, transformation rule, reviewer, and disposition. FTC guidance is relevant to substantiated customer-facing representations and secure data practices; NIST supports governance, roles, and recoverability; SBA guidance supports clear responsibilities. The local catalog and policy remain the decisive evidence for what the assistant may change.',
    pilot: 'Start in a draft, staging, or import-preview state. Ask the assistant to correct only preapproved fields and to flag conflicts instead of resolving them by guesswork. A second reviewer samples both changed and unchanged records, because omission can be as consequential as an incorrect edit. Test variant inheritance, mobile rendering, image alternatives, links, structured fields, and the rollback procedure. Release only the reviewed set, then compare the live record with the approved change log. Do not mix merchandising strategy into a data-maintenance pilot.',
    risks: 'Common failure modes are source drift, bulk edits applied to the wrong variants, unsupported claims, accidental publication, overbroad store permissions, and no recoverable prior state. Inventory and delivery fields may be fed by systems the assistant cannot validate. Privacy, payment, legal, tax, safety, warranty, and regulated-product questions stay outside routine catalog authority. A successful sample proves only that the declared fields and rules worked for that sample at that time.',
    measures: 'Report source-complete proposed changes, reviewer acceptance by field class, conflicts escalated before release, rollback test results, and live-versus-approved differences. Do not rate the assistant by the number of rows touched; bulk volume rewards risky behavior. A stronger measure is the proportion of eligible records changed without an unapproved field mutation, alongside a transparent count of exclusions and unresolved conflicts.',
    conclusion: 'Catalog maintenance is delegable when field authority is explicit, every material edit is traceable, changes can be previewed and reversed, and commercial or regulated decisions remain with their owners. Begin with one narrow field family and a recoverable batch rather than full-store editing rights.',
    sources: [nist, ftc, sba],
  },
  {
    slug: 'recruiting-coordination-delegation-boundaries',
    title: 'Which recruiting tasks can a virtual assistant coordinate without making hiring decisions?',
    excerpt: 'A job-related workflow study that separates scheduling and record preparation from screening judgments, accommodations, selection, and offers.',
    service: '/services/recruiting-coordination', serviceName: 'Recruiting Coordination',
    question: 'Which recruiting events can be completed from consistent written instructions without the assistant interpreting candidate merit or exercising selection authority?',
    decision: 'Recruiting coordination can include posting approved material, acknowledging applications, checking declared completeness, scheduling, maintaining status records, and preparing interview packets. It should not silently become candidate ranking or rejection. The unit of analysis is one event in one requisition. Record the approved job criteria, permitted action, required evidence, candidate-facing template, exception trigger, and decision owner. If an action requires interpreting qualifications, accommodations, protected information, compensation, or offer terms, it leaves the coordination lane.',
    evidence: 'Use a consecutive sample from a single approved requisition so the rules do not change between candidates. Preserve the job description version, workflow state, timestamps, messages, corrections, and owner decisions while minimizing access to sensitive information. The EEOC explains that selection procedures should be job-related and consistently applied; SBA guidance supports clear job and management expectations; FTC guidance supports limiting information and access. This article does not translate those sources into legal advice or decide which employment rules apply to a company.',
    pilot: 'Run coordination in parallel before granting independent candidate-facing authority. The assistant prepares acknowledgments, availability options, reminders, packet checks, and missing-information escalations. The hiring owner independently reviews exceptions and confirms that identical event types received the same approved treatment. Audit both completed and dropped events, since a clean schedule can hide applicants who were misrouted. Publish a responsibility matrix covering coordinator actions, recruiter decisions, hiring-manager decisions, human-resources review, and specialist escalation.',
    risks: 'Risks include inconsistent messages, unapproved screening, exposure of sensitive candidate data, missed accommodation requests, status changes without authority, and promises about compensation or employment. Automation does not remove these risks; it can repeat an unclear rule at scale. The study cannot establish fairness, legal compliance, validity of a selection procedure, or candidate experience from workflow records alone. Qualified human-resources and legal owners must decide protected questions.',
    measures: 'Useful process measures include events completed from an approved rule, exceptions sent to the correct owner, scheduling corrections, stale statuses, candidate messages using current templates, and records with unnecessary sensitive data. Avoid using progression or rejection rates to evaluate a coordinator without a separate, qualified analysis of job criteria and selection decisions. Coordination quality is primarily traceability, consistency, timeliness, and correct escalation.',
    conclusion: 'Recruiting coordination is ready for delegation when approved job criteria and templates are versioned, routine events are distinguishable from selection judgments, candidate data is minimized, and every exception has a named human owner. A first pilot should cover scheduling and record completeness for one requisition, not candidate ranking.',
    sources: [eeoc, sba, ftc],
  },
  {
    slug: 'research-data-support-brief-reproducibility',
    title: 'How do you test whether a virtual assistant research brief is reproducible?',
    excerpt: 'A source-to-claim study for buyers deciding whether delegated research can support a real business decision without hiding uncertainty or owner judgment.',
    service: '/services/research-and-data-support', serviceName: 'Research and Data Support',
    question: 'Can an independent reviewer reconstruct each material claim from the recorded question, source, evidence location, checked date, transformation, and uncertainty note?',
    decision: 'A polished brief is not necessarily a reproducible brief. The unit of analysis is one material claim, comparison field, or calculated value. Before research starts, define the decision question, intended audience, inclusion rule, source hierarchy, freshness requirement, output fields, and stop rule. The assistant can gather and organize evidence; the owner decides how much uncertainty the business can accept. Claims that require legal, clinical, financial, security, or other professional judgment must be routed to the appropriate specialist.',
    evidence: 'Select a consequential subset of claims rather than checking only convenient citations. Give a second reviewer the brief and its source register but not the original researcher’s memory. The reviewer should open the recorded URL, locate the supporting passage or data, confirm publisher and date, repeat any calculation, and classify support as direct, partial, inferred, conflicting, unavailable, or outside scope. NIST guidance supports documented governance and risk context; FTC material supports careful information handling; SBA guidance supports defined responsibilities. These sources shape the workflow but do not validate a local business conclusion.',
    pilot: 'Pilot one bounded question with a small, declared source set. Require a source register containing title, publisher, URL, publication or update date when shown, checked date, evidence location, claim supported, and limitations. Preserve excluded sources with short reasons so the final set is not mistaken for everything found. Ask the independent reviewer to reproduce the central findings and record disagreements before reconciliation. Revise the method when disagreement traces to an ambiguous field; revise the claim when the evidence itself is weaker than the draft.',
    risks: 'Research can fail through invented demand, stale pages, circular citations, source laundering, copied definitions, hidden exclusions, irreproducible calculations, and confident prose that exceeds the evidence. Search rank is not authority, and multiple pages repeating one source are not independent confirmation. Confidential records create additional access and retention risks. A reproducibility check cannot guarantee truth, completeness, or fitness for every decision; it reveals whether a declared path from evidence to claim can be followed.',
    measures: 'Report material claims by support class, sources successfully reopened, calculations independently reproduced, conflicts retained, exclusions disclosed, and questions escalated. Keep denominators visible. A high citation count is not a quality result if the sources do not support consequential claims. Recheck time-sensitive claims near the decision date and record any change rather than silently replacing the original observation.',
    conclusion: 'Research and data support is ready to scale when a second person can retrace important claims, calculations, and exclusions without private explanation from the researcher. Begin with one decision question, a declared source hierarchy, and an independent reproduction pass before increasing volume.',
    sources: [nist, ftc, sba],
  },
];

export const september18ResearchPosts: ResearchPost[] = specs.map((s) => ({
  slug: s.slug,
  title: s.title,
  excerpt: s.excerpt,
  published,
  methodology: `Research question: ${s.question} This article uses a prospective, record-based decision study. It does not report a completed company experiment or claim measured business results. Sources were checked ${checked}. The proposed method separates source facts, local observations, analysis, inference, and owner decisions.`,
  headlineStat: { value: '1', label: 'bounded workflow unit evaluated before authority expands', source: 'Declared methodology' },
  keyStats: [
    { value: String(s.sources.length), label: 'primary or authoritative sources in the source register' },
    { value: '2', label: 'independent views required for judgment-based pilot checks' },
    { value: '0', label: 'unverified performance, savings, or workforce claims' },
  ],
  takeaways: [s.decision, s.conclusion, 'Treat missing or conflicting evidence as an escalation, not permission to guess.'],
  sections: [
    { heading: 'The buyer decision and unit of analysis', body: s.decision, table: [['Decision field', 'Required record'], ['Unit', 'One declared workflow event or record'], ['Authority', 'Named owner for consequential decisions'], ['Boundary', 'Observed facts kept separate from inference']] },
    { heading: 'Evidence collection', body: s.evidence, table: [['Evidence layer', 'Treatment'], ['Primary record', 'Preserve source and date'], ['Local observation', 'Report only within the sample'], ['Inference', 'Label and explain'], ['Unknown', 'Retain and escalate']] },
    { heading: 'A bounded pilot', body: s.pilot, table: [['Stage', 'Control'], ['Prepare', 'No external commitment'], ['Compare', 'Independent owner or reviewer check'], ['Reconcile', 'Preserve first results and differences'], ['Expand', 'Only the demonstrated task lane']] },
    { heading: 'Risks, uncertainty, and limitations', body: s.risks, table: [['Risk', 'Response'], ['Sensitive data', 'Minimize and restrict'], ['Ambiguous authority', 'Stop and route'], ['Sample limits', 'Do not generalize'], ['Material change', 'Reopen the decision']] },
    { heading: 'What to measure without inventing a result', body: s.measures, table: [['Measure class', 'Use'], ['Completeness', 'Find missing decision inputs'], ['Agreement', 'Find ambiguous rules'], ['Exceptions', 'Improve routing'], ['Corrections', 'Improve the controlled lane']] },
    { heading: 'Niche-specific conclusion', body: `${s.conclusion} For an overseas client working with a Philippines-based virtual assistant, geography does not prove skill, availability, compliance, or outcomes. The evidence must come from the role, records, pilot, and owner review.`, table: [['Next step', 'Owner'], ['Define one bounded sample', 'Business owner'], ['Prepare evidence', 'Assistant'], ['Approve authority', 'Authorized owner'], ['Resolve protected questions', 'Qualified specialist']] },
    { heading: `When ${s.serviceName} may fit`, body: `If the proposed pilot confirms a repeatable preparation lane and clear escalation rules, review the ${s.serviceName} service scope. The service conversation should start from the documented work, systems, schedule, access, and owner decisions—not from an assumption that every task in the category is ready to transfer.`, table: [['Bring to scope review', 'Why'], ['Representative records', 'Show real variation'], ['Authority matrix', 'Protect owner decisions'], ['Access inventory', 'Limit permissions'], ['Review cadence', 'Detect drift']] },
  ],
  sourceNotes: `Source register checked ${checked}: ${s.sources.map((x) => `${x.name} (${x.url})`).join('; ')}. The publishers did not review this article, endorse OverseasVirtualAssistant.com, or provide results for the proposed local study.`,
  sources: s.sources,
  internalLinks: ['/research', s.service, '/contact'],
  faqs: [
    { question: 'Does this article prove that delegation will improve performance?', answer: 'No. It proposes a bounded study for deciding whether one task lane has enough evidence and control to delegate.' },
    { question: 'Does the method replace legal, security, financial, or professional advice?', answer: 'No. Protected decisions remain with the authorized owner and qualified specialists.' },
    { question: 'Why use a consecutive or representative sample?', answer: 'A hand-picked set of easy records can hide exceptions. A declared sample makes the limits and exclusions inspectable.' },
  ],
  relatedResearch: ['/research/role-scope-evidence-for-virtual-assistant-hiring', '/research/risk-review-before-expanding-delegated-work', '/research/owner-review-routines-for-delegated-work'],
  image,
  serviceHandoff: { href: s.service, label: `Review ${s.serviceName}`, copy: `Use the evidence and boundaries above to scope a ${s.serviceName.toLowerCase()} lane with OverseasVirtualAssistant.com.` },
  cta: 'Bring one representative work sample, the systems involved, the required schedule, and the decisions that must remain with you.',
}));
