import type { BlogPost, ResearchPost } from './data';

const published = '2026-09-02';
const image = '/images/remote-onboarding.jpg';
const sba = { name: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'small-business guidance for managing a team' };
const nist = { name: 'NIST Small Business Cybersecurity Corner', url: 'https://www.nist.gov/itl/smallbusinesscyber', note: 'small-business cybersecurity resources' };
const cisa = { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'practical account-security guidance' };
const ftc = { name: 'FTC Start with Security', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', note: 'business guidance on access and data minimization' };

const blogSpecs = [
  ['morning-editorial-capacity-check-for-virtual-assistants', 'Run a morning editorial capacity check with a virtual assistant', 'Match the approved queue to available writing, review, and release capacity before the day begins.', 'release capacity', 'Count ready briefs, research effort, reviewers, correction work, and release owners. Drafting capacity alone cannot support a publication commitment.', 'Publish a bounded daily commitment with owners and a fallback order. When capacity changes, record which item moved and who accepted the tradeoff.'],
  ['reader-question-test-for-daily-va-articles', 'Use a reader-question test for daily VA articles', 'Give each article one answerable reader question so research, drafting, and review stay aligned.', 'reader intent', 'Translate the topic into the decision a prospective client is trying to make. State adjacent questions and sensitive conclusions that the article will not answer.', 'Test every heading and the final summary against the approved question. Route any material change in purpose back to the brief owner.'],
  ['approved-source-refresh-check-for-va-content', 'Create an approved-source refresh check for VA content', 'Recheck source authority, dates, URLs, and claim fit before an older evidence packet enters a new article.', 'source freshness', 'Map each proposed factual claim to its saved source, then open the original publisher page and inspect its current status and qualifications.', 'Record replaced references, reasons, dates, and reviewers. A familiar or working URL is not enough unless it still supports the exact claim.'],
  ['article-claim-risk-labels-for-remote-va-writers', 'Set article claim-risk labels for remote VA writers', 'Label sensitive and fast-changing claims early so every draft receives the right evidence and review path.', 'claim risk', 'Use a small defined set such as stable background, current fact, sensitive business claim, regulated topic, and unsupported interpretation.', 'Connect every label to a source, wording, approval, or exclusion rule. Labels describe claims and controls, never the writer.'],
  ['virtual-assistant-draft-self-review-routine', 'Build a virtual assistant draft self-review routine', 'Use a short evidence, structure, clarity, and metadata pass before sending an article to the editor.', 'draft self-review', 'Save the working version, compare it with the accepted brief, and trace material factual claims to the source record.', 'Read headings as an outline, remove repetition, test links, and report unresolved questions honestly. Self-review does not replace independent editorial acceptance.'],
  ['editor-feedback-resolution-log-for-va-articles', 'Keep an editor-feedback resolution log for VA articles', 'Turn editorial comments into traceable decisions, corrections, and process learning without retaining noisy chat threads.', 'feedback closure', 'Anchor feedback to one draft version and classify it as factual, structural, clarity, metadata, optional, or owner-decision work.', 'Give each material comment a resolved, declined, superseded, or escalated outcome. Review recurring causes without turning the log into a worker score.'],
  ['daily-blog-image-selection-from-approved-assets', 'Select daily blog images from approved site assets', 'Choose relevant existing images, write useful alt text, and document reuse without creating an unapproved asset workflow.', 'approved assets', 'Use a current inventory of permitted site assets and select for accurate context rather than novelty. Never download or generate a substitute without approval.', 'Record the exact asset path, contextual alt text, display check, and reviewer decision. Escalate a genuine library gap or use the approved no-image pattern.'],
  ['virtual-assistant-internal-link-opportunity-review', 'Run a virtual assistant internal-link opportunity review', 'Add internal links that help readers continue a task while protecting relevance, route accuracy, and editorial intent.', 'internal links', 'Map likely next questions, open every candidate page, and confirm that its current content and route match the proposed anchor.', 'Place only useful links near the relevant idea and verify rendered destinations. Avoid quotas, forced keywords, and links that resolve through unrelated redirects.'],
  ['daily-article-publish-approval-record', 'Create a daily article publish-approval record', 'Capture the exact version, checks, approver, route, and release decision before a daily article is published.', 'publish approval', 'Identify the content version, title, family, slug, canonical route, date, approved asset, completed checks, and exceptions.', 'Require an authorized owner to record approved, returned, or held. After build, append route verification without confusing it with prepublication approval.'],
  ['remote-va-publishing-exception-aging-review', 'Review aging publishing exceptions with a remote VA', 'Keep blocked articles visible by tracking exception age, decision ownership, impact, and the next useful action.', 'exception aging', 'Start the clock when an exception blocks the next gate and distinguish active work from waiting for policy, access, source, or approval input.', 'Escalate a specific decision with context and consequence. Resolve, defer, replace, rescope, or cancel stale work through an explicit disposition.'],
  ['end-of-shift-content-access-check-for-philippines-vas', 'Run an end-of-shift content access check for Philippines VAs', 'Close the shift by securing working files, reporting access issues, and preserving a clean next-owner handoff.', 'access closure', 'Return drafts and evidence to approved systems, identify the current version, and remove temporary copies according to policy.', 'Report unexpected permissions or authentication failures to the named owner. Never place passwords, recovery codes, or unnecessary personal data in editorial notes.'],
  ['daily-content-routine-improvement-note', 'Write a daily content-routine improvement note', 'Turn one observed publishing friction into a bounded improvement proposal with evidence, ownership, and a review date.', 'routine improvement', 'Describe the observed pattern without assuming a personal cause, then locate the earliest intake, research, review, or release control that could expose it.', 'Propose one measurable experiment with an owner and review date. The accountable process owner decides whether to adopt, revise, or retire the change.'],
] as const;

export const september2BlogPosts: BlogPost[] = blogSpecs.map(([slug, title, excerpt, subject, diagnosis, response], index) => ({
  slug, title, excerpt, minutes: 8 + (index % 4), updated: published,
  takeaways: [`Make ${subject} observable.`, 'Keep decisions with the accountable owner.', 'Preserve evidence for the next handoff.'],
  sections: [
    { heading: `Define the ${subject} question`, body: `${diagnosis} The assistant records facts, uncertainties, and the next required decision rather than filling missing context with an assumption.` },
    { heading: 'Assign the operating boundary', body: `Name who prepares the record, who reviews it, and who can approve an exception. Keep legal, financial, security, employment, and policy judgments with qualified owners. This boundary lets OverseasVirtualAssistant.com use remote support without transferring accountability.` },
    { heading: 'Run the daily control', body: `${response} Use the approved queue and systems of record so an editor can reproduce the state of the work without searching private messages.` },
    { heading: 'Close with evidence', body: `At handoff, identify the article, current version, completed check, open exception, next owner, and due time. Review the ${subject} record for repeated friction, but do not treat a workflow observation as an individual performance conclusion.` },
  ],
  faqs: [
    { question: `Who owns ${subject}?`, answer: 'The assistant can prepare and maintain the record; the named editorial or business owner retains material decisions and approvals.' },
    { question: 'How should the team introduce this routine?', answer: 'Pilot it on a bounded article lane, inspect the evidence, and revise the rule before expanding it.' },
  ],
  sources: index % 3 === 0 ? [sba, nist] : index % 3 === 1 ? [sba, ftc] : [nist, cisa],
  image: { src: image, alt: `Remote editorial team applying ${subject} controls` },
  internalLinks: ['/blog', '/research', '/services', '/contact'],
  cta: 'Need a Philippines-based assistant for a controlled daily article routine? Share the workflow with our staffing team.',
}));

const researchSpecs = [
  ['research-editorial-capacity-signals-for-daily-publishing', 'Research note: editorial capacity signals for daily publishing', 'An operational framework for distinguishing writing capacity from the review and release capacity needed for reliable daily articles.', 'Which signals support a realistic daily article commitment?', 'Draft counts overstate capacity. Ready briefs, evidence complexity, editor availability, correction inventory, approval coverage, and release ownership provide a more complete view.', 'A Philippines-based assistant can prepare the opening capacity record so the manager can select a reviewable batch and fallback order.', 'This is an operating model, not a productivity benchmark; workload varies by scope, risk, and reviewer requirements.'],
  ['research-claim-risk-routing-in-remote-content-teams', 'Research note: claim-risk routing in remote content teams', 'How defined claim categories can connect article evidence to appropriate review without becoming worker scores.', 'How can a remote workflow route sensitive claims before publication?', 'Claim labels help only when each category triggers a specific source, wording, approval, or exclusion rule.', 'The assistant can label claims during research while editors and qualified reviewers retain sensitive publication decisions.', 'Labels cannot establish compliance or correctness and may create false confidence when definitions are weak.'],
  ['research-version-specific-approval-for-article-releases', 'Research note: version-specific approval for article releases', 'Why a publish decision should identify the exact article body, metadata, route, and exceptions it authorizes.', 'What must an approval identify to show which artifact was authorized?', 'A reliable approval binds the decision to a content version, title, slug, canonical, date, asset, checks, exceptions, approver, and timestamp.', 'The assistant prepares the candidate record; the authorized owner decides; the release operator later records route evidence.', 'Approval does not prove the deployed page matches the candidate, so build and post-deployment checks remain separate.'],
  ['research-aging-exceptions-in-article-workflows', 'Research note: aging exceptions in article workflows', 'How cause, ownership, and disposition make editorial waiting time more useful than one cycle-time number.', 'Which fields distinguish delayed work from active editorial work?', 'Exception age is actionable when paired with discovery time, affected gate, cause, decision owner, consequence, next action, and disposition.', 'The assistant can maintain the exception lane and escalate a specific decision when an approved threshold is reached.', 'Age does not measure individual performance and must be interpreted with its cause and risk context.'],
  ['research-approved-asset-reuse-in-daily-articles', 'Research note: approved asset reuse in daily articles', 'How asset inventories, semantic fit, alt text, and release records support controlled image reuse.', 'What evidence supports safe reuse of an existing site image?', 'Controlled reuse depends on an approved inventory, accurate contextual fit, permitted use, suitable alternative text, and the exact asset path.', 'The assistant selects from the approved library and escalates a gap instead of downloading or generating a replacement.', 'This analysis does not determine copyright, license, accessibility, or brand approval; authorized specialists retain those decisions.'],
] as const;

export const september2ResearchPosts: ResearchPost[] = researchSpecs.map(([slug, title, excerpt, question, finding, application, limitation], index) => {
  const sources = index % 2 ? [sba, ftc] : [nist, cisa];
  return {
    slug, title, excerpt, published,
    methodology: 'This operational research note reviews the named public guidance and applies it to one bounded daily-publishing question. It separates source principles from editorial interpretation for OverseasVirtualAssistant.com.',
    headlineStat: { value: '1', label: 'bounded editorial control question', source: 'Article methodology' },
    keyStats: [{ value: '2', label: 'named public sources reviewed' }, { value: '4', label: 'analysis fields documented' }],
    takeaways: [finding, application, limitation],
    sections: [
      { heading: 'Research question', body: `Published September 2, 2026. ${question}`, table: [['Field', 'Recorded scope'], ['Article family', 'Research'], ['Publication date', published], ['Method', 'Bounded operational analysis']] },
      { heading: 'Finding', body: finding, table: [] },
      { heading: 'Application to a daily VA routine', body: application, table: [] },
      { heading: 'Limitations', body: limitation, table: [] },
    ],
    sourceNotes: `Sources consulted: ${sources.map(source => source.url).join('; ')}. Recommendations are operational analysis and do not claim measured worker outcomes.`,
    sources, internalLinks: ['/research', '/blog', '/services', '/contact'],
    faqs: [{ question: 'Does this note measure an individual assistant?', answer: 'No. It evaluates a bounded workflow control and does not infer individual outcomes.' }, { question: 'How should a manager use the finding?', answer: 'Pilot the control, preserve decision ownership, and inspect actual release evidence before expanding it.' }],
    relatedResearch: researchSpecs.filter(item => item[0] !== slug).slice(0, 3).map(item => `/research/${item[0]}`),
    image: { src: image, alt: `Remote team reviewing ${title.toLowerCase()}` },
    cta: 'Ask our staffing team to translate this finding into a scoped Philippines-based content-support routine.', serviceHandoff: undefined,
  };
});
