import type { ResearchPost } from './data';

const published = '2026-09-22';
const checked = 'September 22, 2026';
const image = { src: '/images/remote-onboarding.jpg', alt: 'A distributed team reviewing a documented virtual assistant workflow' };

type Source = { name: string; url: string; note: string };
type Spec = {
  slug: string; title: string; excerpt: string; service: string; serviceName: string;
  question: string; unit: string; boundary: string; sample: string; facts: string;
  analysis: string; pilot: string; risks: string; measures: string; conclusion: string;
  sources: Source[]; related: string[];
};

const source = (name: string, url: string, note: string): Source => ({ name, url, note: `${note}; checked ${checked}` });
const sba = source('U.S. Small Business Administration — Manage your business', 'https://www.sba.gov/counseling/manage-your-business/', 'guidance on defining and managing business responsibilities');
const nist = source('NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework', 'authoritative governance, access, and risk-management framework');
const ftc = source('Federal Trade Commission — Protecting Personal Information', 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', 'business guidance on collecting, retaining, and protecting personal information');

const specs: Spec[] = [
  {
    slug: 'executive-meeting-action-register-delegation-study',
    title: 'Can an executive assistant own the meeting action register without owning executive decisions?',
    excerpt: 'A record-based study of how a Philippines-based executive assistant can capture decisions, owners, deadlines, and follow-up while authority stays with the executive.',
    service: '/services/executive-assistance', serviceName: 'Executive Assistance',
    question: 'Which parts of meeting follow-through can be reconstructed from the agenda, attendee corrections, approved notes, and named owners without asking an assistant to infer an executive commitment?',
    unit: 'one proposed action or decision record from one business meeting',
    boundary: 'The assistant may prepare the record, request missing fields, send an approved reminder, and report status. The executive confirms whether a decision was actually made, who accepted an obligation, whether a deadline is realistic, and what may be shared outside the meeting.',
    sample: 'Use a consecutive sample of recurring operating meetings and include routine actions, changed decisions, confidential topics, cross-team dependencies, and items that were discussed but never approved. Do not select only tidy meetings with complete agendas.',
    facts: 'The National Archives advises federal employees to ensure records are created when meetings make decisions, resolve issues, or establish policy. That guidance governs federal records, not a private company, but it offers a useful completeness principle. NARA also explains that video conferences should follow established policies for documenting substantive decisions and that not every meeting must be recorded. NIST contributes a governance principle: context, roles, and risk should be understood before controls are assigned. SBA guidance supports explicit responsibilities. None of these authorities says that a remote assistant may approve a private-company decision.',
    analysis: 'A useful action register is not a transcript. It is a controlled map from an approved decision to an owner, due condition, evidence of completion, and next review. “Discuss pricing” is not equivalent to “send the approved price sheet by Friday,” and silence from an attendee is not acceptance. The register should therefore preserve the proposed wording, the confirming person, the confirmation time, and later corrections. The assistant can expose ambiguity without resolving it. This makes the work appropriate for a structured executive-support lane while preventing meeting notes from silently becoming policy or a customer promise.',
    pilot: 'For two meeting cycles, have the assistant prepare the register without sending commitments. The executive independently marks decisions, owners, dates, confidentiality, and external-message permissions. Compare records item by item, reconcile disagreements, and retain the original draft so the team can locate the missing rule. On the second cycle, allow approved internal reminders for stable item types while keeping external messages, money, legal positions, personnel matters, and policy exceptions behind approval. End with a short authority matrix and a documented cancellation path for an incorrectly recorded action.',
    risks: 'The material risks are false attribution, loss of context, disclosure of confidential discussion, stale deadlines, and reminders that imply authority the sender does not have. Recording or transcribing meetings can also introduce consent, retention, security, and jurisdiction-specific duties. This study does not decide those duties. A company should use its own approved tools and policies, collect no more content than the follow-up purpose requires, and route legal or employment questions to qualified owners.',
    measures: 'Count action records with a confirmed owner, due condition, source meeting, approval state, and closure evidence. Report corrections by field and items returned because no decision existed. Track overdue items separately from disputed items: the former may need follow-up, while the latter need an owner decision. Do not claim that more actions or faster closure proves executive productivity. The outcome is a more reconstructable handoff, not a performance guarantee.',
    conclusion: 'Executive meeting follow-through is ready for delegation when the assistant can prepare a complete register from approved evidence, ambiguities return to a named executive, and no reminder creates a new commitment. A bounded two-cycle pilot is stronger evidence than transferring every meeting and hoping judgment stays visible.',
    sources: [source('U.S. National Archives — Records management guidance for federal employees', 'https://www.archives.gov/records-mgmt/transition/records-management-guidance-federal-employees', 'current official guidance on documenting decisions and work'), source('U.S. National Archives — Video conference records bulletin', 'https://www.archives.gov/records-mgmt/bulletins/2023/2023-04', 'official guidance on documenting video conferences'), nist, sba],
    related: ['/research/calendar-inbox-delegation-readiness-study', '/research/handoff-reliability-in-distributed-teams', '/research/owner-review-routines-for-delegated-work'],
  },
  {
    slug: 'real-estate-listing-change-control-assistant-study',
    title: 'Which real-estate listing updates can a virtual assistant prepare safely?',
    excerpt: 'A field-level study for separating source-backed listing administration from pricing, representation, fair-housing, and licensed real-estate judgments.',
    service: '/services/real-estate-virtual-assistance', serviceName: 'Real Estate Virtual Assistance',
    question: 'For each proposed listing change, can the team identify an authoritative record, an allowed transformation, a confirming owner, and a rollback path before publication?',
    unit: 'one field change on one property record in one publication channel',
    boundary: 'An assistant may collect authorized property facts, normalize approved formatting, prepare image and document checks, and queue changes for review. The responsible broker, agent, property owner, or other authorized professional retains pricing, representation, disclosure, availability, offer, fair-housing, and legal decisions.',
    sample: 'Freeze a representative export containing active, pending, changed, and withdrawn records; include missing fields and known exceptions. For every proposed edit, preserve the old value, proposed value, source record, capture date, channel, reviewer, and rollback state. Sample across field types rather than reviewing only spelling fixes.',
    facts: 'HUD states that the Fair Housing Act protects people from discrimination in housing-related activities. HUD’s advertising guidance and fair-housing materials make housing language a consequential area, but they do not approve a particular listing. NIST provides a framework for governing access and change risk. FTC guidance supports limiting personal information to the business need. SBA supports defined roles. These sources establish boundaries and control principles; the property source of truth and applicable local real-estate rules must come from the responsible business and qualified local owner.',
    analysis: 'The central distinction is between transcription and judgment. Copying an approved bedroom count from a controlled property record is different from deciding how a room may legally be described. Resizing an approved image is different from selecting an image that changes the representation. A field matrix should classify changes as clerical, operational, commercial, regulated, or system-generated. Each class needs an approved source and reviewer. When two sources conflict, the assistant should hold the change and show the conflict instead of choosing the more convenient value.',
    pilot: 'Begin in a staging copy or prepare-only queue. The assistant proposes a small batch; the authorized owner independently checks source fit, prohibited language, publication channels, and rollback data. Reconcile every difference before release. After approval, verify the public record against the change log and check that syndicated channels did not truncate or alter a material field. Expand only the field classes that passed twice. Keep pricing, status, disclosure, and customer-facing commitments under explicit approval even if the clerical portion becomes routine.',
    risks: 'Risks include discriminatory or exclusionary wording, stale availability, unsupported property claims, accidental status changes, private occupant data, lost image rights, and inconsistent syndicated records. A source-backed workflow cannot certify legal compliance, title, condition, measurements, licensing, disclosure sufficiency, or platform rules. Those matters stay with the authorized professional. Access should be role-based, exports should be controlled, and the team needs a fast rollback route.',
    measures: 'Measure proposed changes with an authoritative source, owner approvals completed before release, post-publication mismatches, blocked conflicts, rollbacks, and time-to-correction. Report results by field class and channel. Do not treat upload volume, listing views, leads, or sale outcomes as evidence that administrative edits were correct; those outcomes depend on many uncontrolled factors.',
    conclusion: 'Listing support is ready for delegation when each allowed field has a source, transformation rule, approver, and rollback path, while regulated and commercial judgments remain visible. The safe first lane is a prepare-only batch of low-risk fields, followed by an owner check and public reconciliation.',
    sources: [source('U.S. Department of Housing and Urban Development — Fair Housing Act overview', 'https://www.hud.gov/helping-americans/fair-housing-act-overview', 'official overview of federal fair-housing protections'), source('HUD — Fair housing rights and obligations', 'https://www.hud.gov/stat/fheo/rights-obligations', 'official fair-housing guidance including advertising'), nist, ftc],
    related: ['/research/property-admin-escalation-evidence', '/research/access-governance-for-delegated-operations', '/research/quality-controls-for-remote-assistant-work'],
  },
  {
    slug: 'medical-scheduling-minimum-necessary-data-study',
    title: 'What is the minimum information a medical administrative assistant needs for scheduling?',
    excerpt: 'A workflow study for defining the smallest scheduling record a Philippines-based assistant needs without transferring clinical judgment or unnecessary health information.',
    service: '/services/medical-administrative-assistance', serviceName: 'Medical Administrative Assistance',
    question: 'Can each recurring scheduling event be completed from an approved minimum field set while clinical questions, urgent symptoms, privacy exceptions, and record disclosures return to qualified owners?',
    unit: 'one scheduling, reminder, rescheduling, or referral-coordination event',
    boundary: 'The assistant may use approved scripts and systems to prepare or complete administrative scheduling events within a written authority matrix. The practice retains clinical triage, medical advice, urgency decisions, identity exceptions, disclosure decisions, consent interpretation, and policy exceptions.',
    sample: 'Use a de-identified or properly authorized consecutive sample that represents new appointments, follow-ups, cancellations, interpreter or accessibility needs, referral gaps, duplicate records, and messages that may sound urgent. Record only fields needed to test the workflow. Do not export a full medical record to make the review easier.',
    facts: 'HHS explains that covered entities generally must take reasonable steps to limit protected health information to the minimum necessary for an intended purpose, while also listing exceptions and requiring organization-specific policies. HHS security guidance describes administrative, physical, and technical safeguards for electronic protected health information. FTC business guidance reinforces data minimization and controlled access, and NIST supplies a general governance framework. Whether a specific organization is covered, which rule applies, and whether a use falls within an exception are legal and compliance decisions outside this study.',
    analysis: 'A minimum scheduling record is purpose-specific, not a universal list. A reminder may require different fields from a referral intake, and treatment communications can have different rules from routine administration. The team should map each event type to its purpose, approved fields, permitted message, authentication step, system of record, retention rule, and escalation owner. Free-text notes deserve particular scrutiny because they can accumulate diagnoses, family details, or speculation that the scheduling task never needed. Missing information should create a controlled hold, not an invitation to infer clinical meaning.',
    pilot: 'Run the workflow in shadow mode using authorized records and approved privacy controls. The assistant prepares the action and script selection; a trained practice owner independently checks identity, field necessity, routing, and whether clinical review is required. Include at least one urgent-sounding message and one privacy exception so the pilot tests stops, not merely routine confirmations. Reconcile differences, revise the event matrix, and grant only the system permissions required for the demonstrated lane.',
    risks: 'Risks include unnecessary access, messaging the wrong person, placing clinical content in an administrative field, treating symptoms as a scheduling choice, revealing appointment information, and retaining copied data in uncontrolled tools. Geography does not change the organization’s obligations or prove compliance. This article is not legal, privacy, security, or clinical advice. The covered entity or responsible practice must approve vendors, access, scripts, retention, incident response, and workforce arrangements.',
    measures: 'Count events completed with the approved field set, unnecessary fields encountered, identity exceptions, clinical escalations, incorrect routes caught before contact, messages using current templates, and copied records removed from temporary locations. Report the denominator and event types. Speed and appointment volume do not establish privacy or clinical quality. A successful pilot shows that the administrative boundary can be followed and audited.',
    conclusion: 'Medical scheduling support is ready for a bounded assistant lane when every event type has a purpose-specific minimum record, approved script, identity control, clinical stop rule, and named practice owner. Begin with routine scheduling in approved systems; do not begin with triage or broad chart access.',
    sources: [source('U.S. Department of Health and Human Services — Minimum Necessary Requirement', 'https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html', 'official HIPAA Privacy Rule guidance and stated exceptions'), source('HHS — Security Rule guidance material', 'https://www.hhs.gov/hipaa/for-professionals/security/guidance/index.html', 'official guidance on safeguards for electronic protected health information'), ftc, nist],
    related: ['/research/privacy-boundaries-in-virtual-assistant-research-notes', '/research/data-minimization-for-delegated-assistant-work', '/research/access-governance-for-delegated-operations'],
  },
  {
    slug: 'legal-deadline-intake-assistant-control-study',
    title: 'Can a legal administrative assistant enter deadline evidence without calculating legal deadlines?',
    excerpt: 'A dual-review study that separates document intake and calendar preparation from jurisdictional rules, legal interpretation, and attorney approval.',
    service: '/services/legal-administrative-assistance', serviceName: 'Legal Administrative Assistance',
    question: 'Can an assistant capture the source document, stated date, service details, matter identity, and uncertainty without deciding which legal rule creates the operative deadline?',
    unit: 'one received document or event that may create, change, or cancel a matter deadline',
    boundary: 'The assistant may preserve the received item, extract plainly stated fields, link the matter, prepare a calendar entry marked pending, and escalate missing or conflicting data. A licensed or otherwise authorized legal professional selects the governing rule, calculates the deadline, decides reminders, and approves the operative entry.',
    sample: 'Use a controlled historical or simulated sample approved by the firm. Include plainly stated dates, amended notices, different service methods, ambiguous matter numbers, duplicate documents, and an event that cancels or moves an earlier date. Preserve first receipt time and every version; do not use only uncomplicated examples.',
    facts: 'The ABA Model Rules say a lawyer must provide competent representation and make reasonable efforts to ensure nonlawyer conduct is compatible with professional obligations. The rules are models, not the law of every jurisdiction, and the responsible lawyer must determine local duties. NIST provides governance and access-control principles; FTC guidance supports protecting retained personal information. These sources support supervision and controlled records but do not calculate a deadline or authorize nonlawyer legal judgment.',
    analysis: 'Deadline intake and deadline calculation are different tasks. A document can state a hearing date while leaving response periods, service rules, holidays, extensions, and local procedures unresolved. The intake record should therefore distinguish verbatim source fields from derived dates. It should show document version, received channel, service information exactly as observed, matter match confidence, pending reviewer, and superseded entries. A red pending state is safer than a polished calendar entry whose legal basis cannot be reconstructed.',
    pilot: 'Have the assistant process a bounded sample into a non-operative review queue. A qualified legal owner independently identifies the event and determines any deadline. Compare document matching, copied fields, version handling, uncertainty flags, and routing—not the assistant’s legal conclusions, because the assistant should not make them. Test amendment and cancellation flows. Only after two reconciled rounds should approved administrative entries move into the production workflow, and each operative deadline should retain reviewer identity and source evidence.',
    risks: 'Risks include wrong-matter attachment, missing service details, overwriting a prior version, treating a mentioned date as the controlling deadline, disclosing confidential information, and creating the appearance of legal judgment. This article is not legal advice and cannot establish compliance with professional rules, court rules, confidentiality duties, supervision requirements, or unauthorized-practice restrictions. The firm’s lawyers and qualified technology or ethics advisers own those decisions.',
    measures: 'Measure items preserved with complete provenance, correct matter matches, ambiguous items held, amended documents linked, pending entries reviewed, and discrepancies caught before an operative calendar change. Track failures by cause. Do not use raw entry speed or zero reported errors as proof of safety; a weak sample or hidden correction channel can produce a flattering number. Review overrides and near misses as evidence for the next control.',
    conclusion: 'A legal deadline intake lane is ready for delegation only when the assistant records source evidence without selecting legal rules, every uncertain event stops, and a qualified owner approves the operative deadline. Start with a non-operative queue and amendment test, not direct control of the firm calendar.',
    sources: [source('American Bar Association — Model Rule 1.1: Competence', 'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_1_1_competence/', 'model professional-conduct rule on lawyer competence'), source('American Bar Association — Model Rule 5.3: Responsibilities Regarding Nonlawyer Assistance', 'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_5_3_responsibilities_regarding_nonlawyer_assistant/', 'model rule on supervision of nonlawyer assistance'), nist, ftc],
    related: ['/research/data-minimization-for-delegated-assistant-work', '/research/documented-escalation-paths-for-delegated-work', '/research/access-governance-for-delegated-operations'],
  },
  {
    slug: 'podcast-sponsor-guest-record-handoff-study',
    title: 'What evidence should a podcast assistant preserve before an episode is released?',
    excerpt: 'A release-readiness study for guest approval, asset provenance, sponsor disclosures, and owner sign-off in a remote podcast administration lane.',
    service: '/services/podcast-administration', serviceName: 'Podcast Administration',
    question: 'Can an independent reviewer verify the approved guest identity, asset rights record, sponsor treatment, episode claims, and release owner from one episode packet?',
    unit: 'one episode version and its linked guest, asset, sponsor, and approval records',
    boundary: 'The assistant may collect forms, normalize filenames, prepare show notes, flag claims, assemble the disclosure record, and queue distribution. The host or authorized producer approves editorial claims, guest treatment, sponsorship language, rights exceptions, and final release.',
    sample: 'Review a consecutive set that includes a guest episode, a sponsor mention, third-party audio or imagery, a correction, and a version change. Preserve excluded assets and unresolved permissions rather than sampling only episodes that already shipped cleanly.',
    facts: 'The FTC explains that endorsements must be honest and not misleading and that unexpected material connections that affect credibility should be disclosed clearly and conspicuously. Its current business guidance discusses podcasts and cross-channel posts, while the Copyright Office explains that copyright protects original works and provides public registration information. NIST contributes access and governance principles. These authorities do not approve an episode, determine ownership of a particular asset, or replace counsel’s analysis.',
    analysis: 'An episode packet should separate evidence from editorial approval. A signed guest form may record agreed uses but does not prove rights in every photo the guest supplied. A sponsor brief may specify required language but does not validate every product claim. A disclosure approved for audio may not fit a clipped social post. The packet should connect each public element to a source, permitted use, channel, version, approver, and unresolved condition. The assistant can make gaps visible; the producer decides whether to replace, edit, disclose, delay, or seek professional advice.',
    pilot: 'Build one packet before publication and ask a second reviewer to reconstruct the episode without relying on chat history. They should locate the final audio, transcript or notes, guest approval state, asset source, sponsor instructions, claim flags, disclosure by channel, correction history, and release owner. Reconcile missing or contradictory records. Run the same check after a last-minute edit because version drift is where a correct approval can become attached to the wrong file.',
    risks: 'Risks include publishing the wrong cut, using an asset without a documented basis, omitting a material connection, carrying a guest claim into promotional copy without review, exposing private contact data, and treating silence as consent. This study cannot determine copyright ownership, publicity rights, contract interpretation, advertising compliance, defamation, or platform rules. Qualified owners must decide those questions. Access to feeds and distribution accounts should be limited and revocable.',
    measures: 'Count packets with a uniquely identified final version, approvals tied to that version, assets with provenance, sponsor elements with channel-specific treatment, unresolved claims escalated, and public outputs matched after release. Track corrections and why they occurred. Download counts, audience growth, and sponsor performance do not show whether the episode packet was complete. The measure is reconstructability before authority expands.',
    conclusion: 'Podcast administration is ready for a delegated release lane when one packet lets a reviewer reconstruct the final episode, permissions, sponsor treatment, and owner approval, and any gap can stop distribution. Start with packet preparation and post-release matching while the producer keeps the publish control.',
    sources: [source('Federal Trade Commission — Endorsement Guides: What People Are Asking', 'https://www.ftc.gov/business-guidance/resources/ftcs-endorsement-guides-what-people-are-asking', 'current staff guidance on endorsements, material connections, and podcast examples'), source('Federal Trade Commission — Endorsements, Influencers, and Reviews', 'https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews', 'official business guidance hub for endorsements and disclosures'), source('U.S. Copyright Office — Copyright basics', 'https://www.copyright.gov/what-is-copyright/', 'official overview of copyright protection and registration'), nist],
    related: ['/research/handoff-context-completeness-study', '/research/source-quality-for-assistant-prepared-research', '/research/documented-escalation-paths-for-delegated-work'],
  },
];

const commonMethod = (s: Spec) => `Research question: ${s.question} This prospective decision study uses ${s.unit} as its unit of analysis. It compares current authoritative guidance with a bounded local sample design; it does not report a completed company experiment. Sources were checked ${checked}. Source facts, proposed observations, analysis, inference, uncertainty, and owner decisions are kept separate.`;

export const september22ResearchPosts: ResearchPost[] = specs.map((s) => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, published,
  methodology: commonMethod(s),
  headlineStat: { value: '1', label: 'bounded workflow unit reviewed before authority expands', source: 'Declared prospective methodology' },
  keyStats: [
    { value: String(s.sources.length), label: 'authoritative sources recorded with checked dates' },
    { value: '2', label: 'independent views used during the controlled pilot' },
    { value: '0', label: 'unverified performance, savings, compliance, or workforce claims' },
  ],
  takeaways: [s.boundary, s.conclusion, 'A missing, conflicting, or sensitive record is a stop condition, not permission to guess.'],
  sections: [
    { heading: 'Decision, scope, and unit of analysis', body: `${s.question} The unit is ${s.unit}. ${s.boundary} This framing matters for OverseasVirtualAssistant.com buyers because a job title is not an authority grant. A Philippines-based assistant may be capable of broad work, but the evidence for delegation must come from the documented lane, representative records, approved tools, and review behavior. The study asks whether the task can be reconstructed, reviewed, and stopped; it does not infer competence, compliance, or business results from geography.`, table: [['Scope field', 'Required decision'], ['Unit', s.unit], ['Assistant boundary', 'Prepare, record, and escalate within written rules'], ['Owner boundary', 'Approve consequential judgment and exceptions']] },
    { heading: 'What authoritative sources establish', body: `${s.facts} The sources are used for the propositions they actually support. They are not blended into a synthetic rule, and repetition across websites is not treated as independent confirmation. Where the company’s local policy is stricter, the local owner must document it. Where a source is silent, the article marks uncertainty instead of presenting a convenient operating preference as law or fact.`, table: [['Evidence type', 'Treatment'], ['Authoritative source', 'Record publisher, title, URL, scope, and checked date'], ['Local policy', 'Identify owner and version'], ['Observation', 'Limit it to the declared sample'], ['Inference', 'Label reasoning and preserve uncertainty']] },
    { heading: 'Representative evidence collection', body: `${s.sample} The evidence record should identify the source item, event time, task state, permitted action, exception reason, reviewer, and final disposition. Preserve first observations before reconciliation so later agreement does not erase where the rule failed. Exclude private data that the review does not need, and document exclusions that could change interpretation. A consecutive or stratified sample is preferable to a convenience sample because ordinary-looking success can hide rare but consequential exceptions.`, table: [['Collection check', 'Pass condition'], ['Selection', 'Declared before results are reviewed'], ['Provenance', 'Original record and time remain traceable'], ['Variation', 'Routine and exception cases are represented'], ['Privacy', 'Only purpose-needed fields are included']] },
    { heading: 'Analysis and inference', body: `${s.analysis} The study should classify support as direct, partial, inferred, conflicting, unavailable, or outside scope. Direct evidence can support a narrow action; partial evidence needs a stated condition; conflict and absence require an owner. The analysis should not convert a small pilot into a population claim. It should explain which event types behaved consistently, which depended on hidden context, and which should never enter the delegated lane without a different control.`, table: [['Finding', 'Decision response'], ['Direct and repeatable', 'Consider a bounded rule'], ['Partial', 'Add condition or owner check'], ['Conflicting', 'Hold and reconcile'], ['Outside scope', 'Route to qualified owner']] },
    { heading: 'Controlled pilot and review', body: `${s.pilot} The pilot should name the start and end, tools, people, review deadline, and stop conditions. Permission should follow demonstrated task scope rather than job title. The owner should review failures and near misses, not merely completed work, then decide whether to keep, narrow, revise, or expand the lane. Expansion should add one task or permission class at a time so the evidence remains attributable.`, table: [['Pilot stage', 'Evidence'], ['Prepare', 'No unapproved external commitment'], ['Compare', 'Independent owner view retained'], ['Reconcile', 'Differences and revised rule recorded'], ['Expand', 'Only demonstrated task and access class']] },
    { heading: 'Risks and limitations', body: `${s.risks} A bounded sample can reveal missing controls and recurring ambiguity, but it cannot prove that every future event will fit. It cannot validate facts outside the sampled records, remove the need for supervision, or turn an administrative workflow into professional advice. Reopen the decision after a material system, policy, owner, service, source, or access change.`, table: [['Risk class', 'Control'], ['Authority drift', 'Named owner and stop rule'], ['Sensitive data', 'Minimum access and approved systems'], ['Version drift', 'Source and approval tied to one version'], ['Overgeneralization', 'Report sample and limitations']] },
    { heading: 'Measures that do not invent a result', body: `${s.measures} Publish denominators and definitions with any local finding. Separate a missing record from an incorrect decision and a corrected draft from an external error. A zero in a short sample is not proof of zero risk. Trend measures are useful only when the task, sampling rule, and denominator remain comparable. The owner should use results to improve the lane, not to manufacture a testimonial or claim about Filipino virtual assistants generally.`, table: [['Measure', 'Interpretation boundary'], ['Completeness', 'Shows required fields, not correctness alone'], ['Agreement', 'Shows rule clarity within the sample'], ['Exceptions', 'Shows where owner attention is needed'], ['Corrections', 'Shows learning before or after release']] },
    { heading: 'Niche-specific conclusion and staffing handoff', body: `${s.conclusion} For a company considering a Philippines-based virtual assistant, the practical next step is to bring representative work, approved systems, required coverage, and owner-only decisions into a staffing conversation. Time-zone overlap should be chosen around the task and reviewer availability. The service scope should preserve this evidence boundary instead of assuming the role name settles it.`, table: [['Staffing input', 'Why it matters'], ['Representative work', 'Shows real variation'], ['Authority matrix', 'Keeps consequential decisions visible'], ['Access inventory', 'Limits permissions to the lane'], ['Review cadence', 'Detects drift and exceptions']] },
  ],
  sourceNotes: `Source register checked ${checked}: ${s.sources.map((x) => `${x.name} (${x.url})`).join('; ')}. These publishers did not review this article, endorse OverseasVirtualAssistant.com, or report results for the proposed local study.`,
  sources: s.sources,
  internalLinks: ['/research', s.service, '/contact'],
  faqs: [
    { question: 'Does this study prove that a virtual assistant will improve performance?', answer: 'No. It defines a prospective, bounded method for deciding whether one workflow lane is sufficiently documented and controlled.' },
    { question: 'Does it replace legal, clinical, security, privacy, or other professional advice?', answer: 'No. Applicable duties and protected judgments stay with authorized owners and qualified professionals.' },
    { question: 'Why retain the first review before correcting it?', answer: 'The first comparison shows where instructions, evidence, or routing were ambiguous. Erasing it would hide the information needed to improve the workflow.' },
  ],
  relatedResearch: s.related,
  image,
  serviceHandoff: { href: s.service, label: `Review ${s.serviceName}`, copy: `Use this evidence boundary to scope a controlled ${s.serviceName.toLowerCase()} lane with OverseasVirtualAssistant.com.` },
  cta: 'Bring one representative sample, the systems involved, the required schedule, and the decisions that must remain with you.',
}));
